### ISSUE TITLE
pgadmin4 (RHEL7) doesn't start after update to 4.1.5 (Failed to launch the application server) (RM #2451)

### ISSUE THREAD

**Issue by dpage** [pgadmin-org/pgadmin4#1187]
***Issue migrated from Redmine: https://redmine.postgresql.org/issues/2451***
*Originally created by **Georg Hartmann** at 2017-06-01 13:07:17 UTC.*

Hi, since I've applied the update to pgadmin4 v1.5-2.rhel7 pgadmin4 doesn't start anymore on my RHEL7.3 workstations (a colleague is also affected).
Update came from repo pgdg96 (PostGreSQL 9.6 7Workstation - x86_64)
Given error is 
"Failed to launch the application server, server thread exiting." 

Stack Trace:
$ pgadmin4
Python path:  "/usr/lib/python2.7/site-packages:/usr/lib64/python2.7/site-packages:/usr/lib/python3.4" 
Python Home:  "" 
Webapp path:  "/usr/lib/python2.7/site-packages/pgadmin4-web/pgAdmin4.py" 
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/pgadmin4-web/pgAdmin4.py", line 37, in <module>
    app = create_app()
  File "/usr/lib/python2.7/site-packages/pgadmin4-web/pgadmin/__init__.py", line 276, in create_app
    driver.init_app(app)
  File "/usr/lib/python2.7/site-packages/pgadmin4-web/pgadmin/utils/driver/__init__.py", line 40, in init_app
    DriverRegistry.load_drivers()
  File "/usr/lib/python2.7/site-packages/pgadmin4-web/pgadmin/utils/driver/registry.py", line 88, in load_drivers
    module = import_module(module_name)
  File "/usr/lib64/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/usr/lib/python2.7/site-packages/pgadmin4-web/pgadmin/utils/driver/psycopg2/__init__.py", line 41, in <module>
    from backports import csv
ImportError: cannot import name csv
"Failed to launch the application server, server thread exiting." 

Installed Packages
pgadmin4-babel.noarch                              1.3-1.rhel7                       @pgdg96
pgadmin4-babel-doc.noarch                          1.3-1.rhel7                       @pgdg96
pgadmin4-python-Flask-Mail.noarch                  0.9.1-3.rhel7                     @pgdg96
pgadmin4-python-babel.noarch                       1.3-1.rhel7                       @pgdg96
pgadmin4-python-beautifulsoup4.noarch              4.5.1-2.rhel7                     @pgdg96
pgadmin4-python-blinker.noarch                     1.4-2.rhel7                       @pgdg96
pgadmin4-python-dateutil.noarch                    1:2.5.3-4.rhel7                   @pgdg96
pgadmin4-python-dateutil-doc.noarch                1:2.5.3-4.rhel7                   @pgdg96
pgadmin4-python-fixtures.noarch                    3.0.0-4.rhel7                     @pgdg96
pgadmin4-python-flask.noarch                       1:0.11.1-7.rhel7                  @pgdg96
pgadmin4-python-flask-babel.noarch                 0.11.1-3.rhel7                    @pgdg96
pgadmin4-python-flask-gravatar.noarch              0.4.2-2.rhel7                     @pgdg96
pgadmin4-python-flask-htmlmin.noarch               1.2-4.rhel7                       @pgdg96
pgadmin4-python-flask-login.noarch                 0.3.2-1.rhel7                     @pgdg96
pgadmin4-python-flask-principal.noarch             0.4.0-13.rhel7                    @pgdg96
pgadmin4-python-flask-security.noarch              1.7.5-3.rhel7                     @pgdg96
pgadmin4-python-flask-sqlalchemy.noarch            2.1-5.rhel7                       @pgdg96
pgadmin4-python-flask-wtf.noarch                   0.12-2.rhel7                      @pgdg96
pgadmin4-python-html5lib.noarch                    1:1.0b3-1.rhel7                   @pgdg96
pgadmin4-python-htmlmin.noarch                     0.1.10-7.gitcc611c3.rhel7         @pgdg96
pgadmin4-python-htmlmin-doc.noarch                 0.1.10-7.gitcc611c3.rhel7         @pgdg96
pgadmin4-python-itsdangerous.noarch                0.24-9.rhel7                      @pgdg96
pgadmin4-python-jinja2.noarch                      2.8-8.rhel7                       @pgdg96
pgadmin4-python-markupsafe.x86_64                  0.23-12.rhel7                     @pgdg96
pgadmin4-python-markupsafe-debuginfo.x86_64        0.23-12.rhel7                     @pgdg96
pgadmin4-python-mimeparse.noarch                   1.5.2-2.rhel7                     @pgdg96
pgadmin4-python-pyrsistent.x86_64                  0.11.13-3.rhel7                   @pgdg96
pgadmin4-python-simplejson.x86_64                  3.8.2-1.rhel7                     @pgdg96
pgadmin4-python-simplejson-debuginfo.x86_64        3.8.2-1.rhel7                     @pgdg96
pgadmin4-python-sqlalchemy.x86_64                  1.0.14-2.rhel7                    @pgdg96
pgadmin4-python-sqlalchemy-debuginfo.x86_64        1.0.14-2.rhel7                    @pgdg96
pgadmin4-python-sqlparse.noarch                    0.2.1-4.rhel7                     @pgdg96
pgadmin4-python-werkzeug.noarch                    0.11.11-3.rhel7                   @pgdg96
pgadmin4-python-wtforms.noarch                     2.1-2.rhel7                       @pgdg96
pgadmin4-pytz.noarch                               2016.6.1-3.rhel7                  @pgdg96
pgadmin4-v1.x86_64                                 1.5-2.rhel7                       @pgdg96
pgadmin4-v1-debuginfo.x86_64                       1.5-2.rhel7                       @pgdg96
pgadmin4-v1-docs.noarch                            1.5-2.rhel7                       @pgdg96
pgadmin4-v1-web.noarch                             1.5-2.rhel7                       @pgdg96
Available Packages
pgadmin4-python-pyrsistent-debuginfo.x86_64        0.11.13-3.rhel7                   pgdg96

kind regards
Georg

**Comment by dpage** [comment]
Issue closed on Redmine.
