### ISSUE TITLE
Expection displayed f user drop SYNONYM from query tool windows and click on properties of that SYNONYM (RM #2503)

### ISSUE THREAD

**Issue by dpage** [pgadmin-org/pgadmin4#1223]
***Issue migrated from Redmine: https://redmine.postgresql.org/issues/2503***
*Originally created by **Fahar Abbas** at 2017-06-20 06:21:29 UTC.*

Tested platform:
Ubuntu 16.04  64 bit

Python 3

Commit ID:
----------
commit a21dad4c456f62a3581dc3152a3ef988a25ba15e

Pre-req:

Install EPAS-10

Steps:
------
1. Open Query tool Window
2. CREATE OR REPLACE PUBLIC SYNONYM "PRIVATE" FOR public.emp;
3. created.
4. Click on this particular PUBLIC SYNONYM
5. open quey tool window
DROP PUBLIC SYNONYM "PRIVATE"
6. Press execute
7. Click on PUBLIC SYNONYM
8. Click on properties section
9. following expecting displayed in terminal:

Exception in thread Thread-768:
Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3.5/socketserver.py", line 628, in process_request_thread
    self.handle_error(request, client_address)
  File "/usr/lib/python3.5/socketserver.py", line 625, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python3.5/socketserver.py", line 354, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.5/socketserver.py", line 681, in __init__
    self.handle()
  File "/home/fahar/venv/lib/python3.5/site-packages/werkzeug/serving.py", line 200, in handle
    rv = BaseHTTPRequestHandler.handle(self)
  File "/usr/lib/python3.5/http/server.py", line 422, in handle
    self.handle_one_request()
  File "/home/fahar/venv/lib/python3.5/site-packages/werkzeug/serving.py", line 235, in handle_one_request
    return self.run_wsgi()
  File "/home/fahar/venv/lib/python3.5/site-packages/werkzeug/serving.py", line 177, in run_wsgi
    execute(self.server.app)
  File "/home/fahar/venv/lib/python3.5/site-packages/werkzeug/serving.py", line 165, in execute
    application_iter = app(environ, start_response)
  File "/home/fahar/venv/lib/python3.5/site-packages/flask/app.py", line 2000, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/fahar/venv/lib/python3.5/site-packages/flask/app.py", line 1991, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/home/fahar/venv/lib/python3.5/site-packages/flask/app.py", line 1567, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/fahar/venv/lib/python3.5/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/home/fahar/venv/lib/python3.5/site-packages/flask/app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/fahar/venv/lib/python3.5/site-packages/flask/app.py", line 1641, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/fahar/venv/lib/python3.5/site-packages/flask/app.py", line 1544, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/fahar/venv/lib/python3.5/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/home/fahar/venv/lib/python3.5/site-packages/flask/app.py", line 1639, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/fahar/venv/lib/python3.5/site-packages/flask/app.py", line 1625, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/fahar/venv/lib/python3.5/site-packages/flask/views.py", line 84, in view
    return self.dispatch_request(*args, **kwargs)
  File "/home/fahar/Projects/pgadmin4/web/pgadmin/browser/utils.py", line 235, in dispatch_request
    return method(*args, **kwargs)
  File "/home/fahar/Projects/pgadmin4/web/pgadmin/browser/server_groups/servers/databases/schemas/synonyms/__init__.py", line 208, in wrap
    return f(*args, **kwargs)
  File "/home/fahar/Projects/pgadmin4/web/pgadmin/browser/server_groups/servers/databases/schemas/synonyms/__init__.py", line 339, in get_target_objects
    trgTyp=data['trgTyp'],
KeyError: 'trgTyp'

10. User can not cancel the dialog due to above exception:

Expected Result:
----------------
No exception should displayed on if user drop SYNONYM from query tool windows and click on properties of that SYNONYM

**Comment by dpage** [comment]
Issue closed on Redmine.
