### ISSUE TITLE
Statusbar to see the actual database (+comment?) (RM #3652)

### ISSUE THREAD

**Issue by dpage** [pgadmin-org/pgadmin4#2078]
***Issue migrated from Redmine: https://redmine.postgresql.org/issues/3652***
*Originally created by **Durum Dara** at 2018-09-17 11:56:21 UTC.*

Dear Developers!

It would be very nice if we can see the actual selected database name (+ comment) in a statusbar.

The user can disable/enable it in preferences.

It could be a normal statusbar at the bottom (like in LibreOffice, Firefox, etc.) which shows the actual database (+ comment). 

Many times I didn't see what is the actual selected database (if I scrolled up / down, or the metadata list is very-very long - too many tables, generator, etc.).

Thank you for it!

**Comment by FaharAbbasRizvi** [comment]
I am facing a problem while creating a sequence:
2023-05-03 12:25:15,729: ERROR	pgadmin:	'description'
Traceback (most recent call last):
  File "/usr/pgadmin4/venv/lib64/python3.9/site-packages/flask/app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/pgadmin4/venv/lib64/python3.9/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/usr/pgadmin4/venv/lib64/python3.9/site-packages/flask/views.py", line 107, in view
    return current_app.ensure_sync(self.dispatch_request)(**kwargs)
  File "/usr/pgadmin4/web/pgadmin/browser/utils.py", line 311, in dispatch_request
    return method(*args, **kwargs)
  File "/usr/pgadmin4/web/pgadmin/browser/server_groups/servers/databases/schemas/sequences/__init__.py", line 157, in wrapped
    return f(self, *args, **kwargs)
  File "/usr/pgadmin4/web/pgadmin/browser/server_groups/servers/databases/schemas/sequences/__init__.py", line 246, in nodes
    description=row['description']
KeyError: 'description'

**Comment by FaharAbbasRizvi** [comment]
@adityatoshniwal Comments are not displayed in the materialized view as well.

**Comment by FaharAbbasRizvi** [comment]
<img width="1018" alt="Screen Shot 2023-05-03 at 12 47 32 PM" src="https://user-images.githubusercontent.com/43006122/235859009-d742f202-d8aa-411e-85b9-2a5086e59c2e.png">

**Comment by FaharAbbasRizvi** [comment]
I am getting an error message while expanding Package node:

Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\pgAdmin 4\v7\python\lib\site-packages\flask\app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Administrator\AppData\Local\Programs\pgAdmin 4\v7\python\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "C:\Users\Administrator\AppData\Local\Programs\pgAdmin 4\v7\python\lib\site-packages\flask\views.py", line 107, in view
    return current_app.ensure_sync(self.dispatch_request)(**kwargs)
  File "C:\Users\Administrator\AppData\Local\Programs\pgAdmin 4\v7\web\pgadmin\browser\utils.py", line 311, in dispatch_request
    return method(*args, **kwargs)
  File "C:\Users\Administrator\AppData\Local\Programs\pgAdmin 4\v7\web\pgadmin\browser\server_groups\servers\databases\schemas\packages\__init__.py", line 171, in wrapped
    return f(self, *args, **kwargs)
  File "C:\Users\Administrator\AppData\Local\Programs\pgAdmin 4\v7\web\pgadmin\browser\server_groups\servers\databases\schemas\packages\__init__.py", line 254, in nodes
    description=row['description']
KeyError: 'description'

**Comment by FaharAbbasRizvi** [comment]
Users can not see comments on primary keys and foreign keys:

<img width="1013" alt="Screen Shot 2023-05-03 at 1 09 20 PM" src="https://user-images.githubusercontent.com/43006122/235863053-bea593ae-2662-44d1-89fa-79990b5e72d2.png">

**Comment by FaharAbbasRizvi** [comment]
Comments are not being displayed for the tablespaces:
<img width="1005" alt="Screen Shot 2023-05-03 at 1 18 24 PM" src="https://user-images.githubusercontent.com/43006122/235864973-f2135003-d19b-4764-89a4-0831b413d96d.png">

**Comment by adityatoshniwal** [comment]
> I am getting an error message while creating the comments trigger function through properties: <img alt="Screen Shot 2023-05-03 at 1 04 43 PM" width="1010" src="https://user-images.githubusercontent.com/43006122/235862445-8d6dc88e-7e60-48ac-9e68-539affbba97e.png">
> 
> (Query-id: 4484273): Error Message:function public.emp_sal_trig_emp() does not exist
> 
> --------------[UI error]--------------- Error: Request failed with status code 500 at e.exports (http://127.0.0.1:49733/static/js/generated/vendor.others.js?ver=70100:109:169883) at e.exports (http://127.0.0.1:49733/static/js/generated/vendor.others.js?ver=70100:109:172306) at XMLHttpRequest.v (http://127.0.0.1:49733/static/js/generated/vendor.others.js?ver=70100:109:165203) ------------[UI End]----------------

I am not able to reproduce this. Works fine at my end. Also, it doesn't look like related to this feature.

**Comment by FaharAbbasRizvi** [comment]
The user can not expand the system catalogs for Redwood(sys).

2023-05-03 01:57:42,704: ERROR	pgadmin:	'description'
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\pgAdmin 4\v7\python\lib\site-packages\flask\app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Administrator\AppData\Local\Programs\pgAdmin 4\v7\python\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "C:\Users\Administrator\AppData\Local\Programs\pgAdmin 4\v7\python\lib\site-packages\flask\views.py", line 107, in view
    return current_app.ensure_sync(self.dispatch_request)(**kwargs)
  File "C:\Users\Administrator\AppData\Local\Programs\pgAdmin 4\v7\web\pgadmin\browser\utils.py", line 311, in dispatch_request
    return method(*args, **kwargs)
  File "C:\Users\Administrator\AppData\Local\Programs\pgAdmin 4\v7\web\pgadmin\browser\server_groups\servers\databases\schemas\catalog_objects\__init__.py", line 173, in wrap
    return f(*args, **kwargs)
  File "C:\Users\Administrator\AppData\Local\Programs\pgAdmin 4\v7\web\pgadmin\browser\server_groups\servers\databases\schemas\catalog_objects\__init__.py", line 239, in nodes
    description=row['description']
KeyError: 'description'

**Comment by FaharAbbasRizvi** [comment]
<img width="1010" alt="Screen Shot 2023-05-03 at 1 23 57 PM" src="https://user-images.githubusercontent.com/43006122/235873111-242b4d1c-e831-48c5-a93b-4c57f2667d75.png">

**Comment by FaharAbbasRizvi** [comment]
All reported issues have been fixed in the updated candidate build for v7.1.
I tested this feature in all supported versions of PostgreSQL and EPAS v11 till v15
