### ISSUE TITLE
500 Internal Server Error after second run (RM #4135)

### ISSUE THREAD

**Issue by dpage** [pgadmin-org/pgadmin4#2490]
***Issue migrated from Redmine: https://redmine.postgresql.org/issues/4135***
*Originally created by **Konrad Szczerba** at 2019-04-04 06:34:02 UTC.*

I installed pgAdmin 4 v4.3 (released March 7, 2019)
On Windows 10 (1809). Got python 2.7.15 in CMD.
Also got WLS installed.

First run was ok. After shutdown and start again I got 500 Internal Server Error.
This is also after computer restart.

Logs:

@
2019-04-04 08:25:54,784: ERROR	werkzeug:	Error on request:
Traceback (most recent call last):
  File "C:\Program Files (x86)\pgAdmin 4\v3\venv\Lib\site-packages\werkzeug\serving.py", line 270, in run_wsgi
    execute(self.server.app)
  File "C:\Program Files (x86)\pgAdmin 4\v3\venv\Lib\site-packages\werkzeug\serving.py", line 258, in execute
    application_iter = app(environ, start_response)
  File "C:\Program Files (x86)\pgAdmin 4\v3\venv\Lib\site-packages\flask\app.py", line 1997, in __call__
    return self.wsgi_app(environ, start_response)
  File "C:\Program Files (x86)\pgAdmin 4\v3\venv\Lib\site-packages\flask\app.py", line 1985, in wsgi_app
    response = self.handle_exception(e)
  File "C:\Program Files (x86)\pgAdmin 4\v3\venv\Lib\site-packages\flask\app.py", line 1540, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Program Files (x86)\pgAdmin 4\v3\venv\Lib\site-packages\flask\_compat.py", line 33, in reraise
    raise value
  File "C:\Program Files (x86)\pgAdmin 4\v3\venv\Lib\site-packages\flask\app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Program Files (x86)\pgAdmin 4\v3\venv\Lib\site-packages\flask\app.py", line 1615, in full_dispatch_request
    return self.finalize_request(rv)
  File "C:\Program Files (x86)\pgAdmin 4\v3\venv\Lib\site-packages\flask\app.py", line 1632, in finalize_request
    response = self.process_response(response)
  File "C:\Program Files (x86)\pgAdmin 4\v3\venv\Lib\site-packages\flask\app.py", line 1858, in process_response
    self.save_session(ctx.session, response)
  File "C:\Program Files (x86)\pgAdmin 4\v3\venv\Lib\site-packages\flask\app.py", line 924, in save_session
    return self.session_interface.save_session(self, session, response)
  File "C:\Program Files (x86)\pgAdmin 4\v3\web\pgadmin\utils\session.py", line 319, in save_session
    expires=cookie_exp, httponly=True, domain=domain
  File "C:\Program Files (x86)\pgAdmin 4\v3\venv\Lib\site-packages\werkzeug\wrappers.py", line 1116, in set_cookie
    samesite=samesite
  File "C:\Program Files (x86)\pgAdmin 4\v3\venv\Lib\site-packages\werkzeug\http.py", line 1064, in dump_cookie
    expires = cookie_date(expires)
  File "C:\Program Files (x86)\pgAdmin 4\v3\venv\Lib\site-packages\werkzeug\http.py", line 786, in cookie_date
    return _dump_date(expires, '-')
  File "C:\Program Files (x86)\pgAdmin 4\v3\venv\Lib\site-packages\werkzeug\http.py", line 766, in _dump_date
    ('Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun')[d.tm_wday],
AttributeError: 'datetime.timedelta' object has no attribute 'tm_wday'
�E�kj�?l��MְX
@

**Comment by dpage** [comment]
Issue closed on Redmine.
