### ISSUE TITLE
debugger not showing all arguments anymore after hitting sql error while debug (RM #5101)

### ISSUE THREAD

**Issue by dpage** [pgadmin-org/pgadmin4#3250]
***Issue migrated from Redmine: https://redmine.postgresql.org/issues/5101***
*Originally created by **Georg Hartmann** at 2020-01-17 16:41:25 UTC.*

Hello,
I had to debug a plpgsql function with 25 IN / INOUT arguments and ran into a sql error (what always may happen).
After restarting the debugger it didn't show all arguments anymore (only 18 displayed, screenshot pgadmin4_17_debuggerbug.png) and I wasn't able to get them back nor to reset the debugger for this function.
As expected, starting the debug process anyway resulted in an pg error (no function matches the given name and argument types, screenshot pgadmin4_17_debugger_error.png)
Reopen the debugger again showed my old values in wrong fields (screenshot pgadmin4_17_debuggerbug_randomizedInputs.png). btw it would be helpful to have a vertical scrollbar in case the debugger window doesn't show all arguments when opened.
The full function signature including out parameters I've added at the end of the ticket in case it matters.

I've tried without success: 
- refresh the function + database tree
- re-deploying the function
- restart pgadmin server
- cleaned browsers cache+cookies + restarted pgadmin server again

So at the moment I'm not able to debug this certain function anymore.
How can I reset the debugger without dropping pgadmin4.db which contains all of my db connections (afaik)?

excerpt from pgadmin4.log

2020-01-17 16:08:07,129: ERROR	flask.app:	Failed to execute query (execute_async) for the server #8 - CONN:723711(Query-id: 8184250):
Error Message:ERROR:  function msp.createorupdateabsencereq(character varying, character varying, integer, integer, integer, character varying, time without time zone, date, time without time zone, date, integer, character varying, integer, time without time zone, time without time zone, character varying, character varying, time without time zone) does not exist
LINE 1:     SELECT msp.createorupdateabsencereq (
                   ^
HINT:  No function matches the given name and argument types. You might need to add explicit type casts.
SQL state: 42883
Character: 12
2020-01-17 16:40:17,638: ERROR	flask.app:	'CONN:723711'
Traceback (most recent call last):
  File "C:/Program Files (x86)/pgAdmin 4/v4/venv/Lib/site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:/Program Files (x86)/pgAdmin 4/v4/venv/Lib/site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Program Files (x86)\pgAdmin 4\v4\web\pgadmin\tools\debugger\__init__.py", line 797, in close
    close_debugger_session(trans_id)
  File "C:\Program Files (x86)\pgAdmin 4\v4\web\pgadmin\tools\debugger\__init__.py", line 2068, in close_debugger_session
    manager.release(conn_id=dbg_obj['conn_id'])
  File "C:\Program Files (x86)\pgAdmin 4\v4\web\pgadmin\utils\driver\psycopg2\server_manager.py", line 389, in release
    del self.connections[my_id]
KeyError: 'CONN:723711'

I'm using on win10 pro (build 1803)
pgadmin4 Version 4.17 (snapshot from 20200110 because of solved issue 5074)
Python Version 3.7.3 (v3.7.3:ef4ec6ed12, Mar 25 2019, 21:26:53) [MSC v.1916 32 bit (Intel)]
Flask Version 1.0.2
Application Mode Desktop
Current User pgadmin4@pgadmin.org

with google Chrome Version 79.0.3945.130 (Offizieller Build) (64-Bit)
against
PostgreSQL 11.6 on x86_64-pc-linux-gnu, compiled by gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-39), 64-bit 
with pldgbapi v1.1

--==== full function signature

CREATE OR REPLACE FUNCTION createorupdateabsencereq(
	puserid character varying,
	puserrole character varying,
	INOUT pkey integer,
	pscheduleunitkey integer,
	OUT pstatus character varying,
	paction character varying,
	pemployeekey integer,
	pdaytypeskeys character varying,
	pendtime time without time zone,
	penddate date,
	pstarttime time without time zone,
	pstartdate date,
	pabsencetypekey integer,
	pworkchoice character varying,
	pshiftkey integer,
	pworkstarttime time without time zone,
	pworkendtime time without time zone,
	preqcomment character varying,
	OUT prequname character varying,
	OUT preqfname character varying,
	OUT preqemail character varying,
	OUT preqaction character varying,
	papprvcomment character varying,
	OUT papprvuname character varying,
	OUT papprvfname character varying,
	OUT papprvemail character varying,
	OUT papprvaction character varying,
	OUT pmoduname character varying,
	OUT pmodfname character varying,
	OUT pmoddate date,
	OUT pmodtime time without time zone,
	OUT pmodaction character varying,
	OUT pcrtuname character varying,
	OUT pcrtfname character varying,
	pxbefore boolean,
	pxbetween boolean,
	pxafter boolean,
	pabsencetype2key integer,
	pstarttime2 time without time zone,
	pendtime2 time without time zone,
	OUT papprovalbymanager boolean,
	pabsencecancelreasonkey integer)
    RETURNS record
    LANGUAGE 'plpgsql'
    COST 100
    VOLATILE 
AS $BODY$
	BEGIN
-- body content removed
	END;--
$BODY$;	
	
kind regards
Georg

**Comment by dpage** [comment]
Issue closed on Redmine.
