### ISSUE TITLE
pgAdmin 4Connection Error with PostgreSQL 12.2 on refreshing large Mview (RM #5213)

### ISSUE THREAD

**Issue by dpage** [pgadmin-org/pgadmin4#3336]
***Issue migrated from Redmine: https://redmine.postgresql.org/issues/5213***
*Originally created by **Randall Williams** at 2020-02-23 22:05:42 UTC.*

Here is the logfile:

2020-02-23 16:42:18,839: ERROR	flask.app:	Connection (id #None) lost for the server (#4) on database (analysis)
Traceback (most recent call last):
  File "/Applications/pgAdmin 4.app/Contents/Resources/web/pgadmin/utils/driver/psycopg2/connection.py", line 1183, in execute_dict
    self.__internal_blocking_execute(cur, query, params)
  File "/Applications/pgAdmin 4.app/Contents/Resources/web/pgadmin/utils/driver/psycopg2/connection.py", line 663, in __internal_blocking_execute
    cur.execute(query, params)
  File "/Applications/pgAdmin 4.app/Contents/Resources/web/pgadmin/utils/driver/psycopg2/cursor.py", line 202, in execute
    return _cursor.execute(self, query, params)
psycopg2.OperationalError: server closed the connection unexpectedly
	This probably means the server terminated abnormally
	before or while processing the request.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Applications/pgAdmin 4.app/Contents/Resources/web/pgadmin/browser/server_groups/servers/databases/schemas/views/__init__.py", line 1857, in refresh_data
    status, res_data = self.conn.execute_dict(SQL)
  File "/Applications/pgAdmin 4.app/Contents/Resources/web/pgadmin/utils/driver/psycopg2/connection.py", line 1190, in execute_dict
    formatted_exception_msg
  File "/Applications/pgAdmin 4.app/Contents/Resources/web/pgadmin/utils/driver/psycopg2/connection.py", line 1105, in __attempt_execution_reconnect
    None if self.conn_id[0:3] == u'DB:' else self.conn_id[5:]
pgadmin.utils.exception.ConnectionLost: Connection (id #None) lost for the server (#4) on database (analysis)

This error occurs when two particular materialized views (of 32) are refreshed with data (from the contextual menu). The macOS version is 10.14.6 and I am running as a non-administrative user. The issue first occurred this morning during the routine updating of data tables and materialized. The size of most of the tables and materialized views is about 82.5K lines.

**Comment by dpage** [comment]
Issue closed on Redmine.
