### ISSUE TITLE
no url_encode in werkzeug (RM #5217)

### ISSUE THREAD

**Issue by dpage** [pgadmin-org/pgadmin4#3339]
***Issue migrated from Redmine: https://redmine.postgresql.org/issues/5217***
*Originally created by **Rein Petersen** at 2020-02-25 02:04:02 UTC.*

On ubuntu 16.04:

<pre>
(.pgadmin4) xxxx@db-srvrmgr:/usr/share/pgadmin4/web# python setup.py
Traceback (most recent call last):
  File "setup.py", line 17, in <module>
    from pgadmin.model import db, User, Version, ServerGroup, Server, \
  File "/usr/share/pgadmin4/web/pgadmin/__init__.py", line 25, in <module>
    from flask_security import Security, SQLAlchemyUserDatastore, current_user
  File "/root/.pgadmin4/local/lib/python2.7/site-packages/flask_security/__init__.py", line 13, in <module>
    from .core import Security, RoleMixin, UserMixin, AnonymousUser, current_user
  File "/root/.pgadmin4/local/lib/python2.7/site-packages/flask_security/core.py", line 28, in <module>
    from .forms import ChangePasswordForm, ConfirmRegisterForm, \
  File "/root/.pgadmin4/local/lib/python2.7/site-packages/flask_security/forms.py", line 17, in <module>
    from flask_wtf import FlaskForm as BaseForm
  File "/root/.pgadmin4/local/lib/python2.7/site-packages/flask_wtf/__init__.py", line 17, in <module>
    from .recaptcha import *
  File "/root/.pgadmin4/local/lib/python2.7/site-packages/flask_wtf/recaptcha/__init__.py", line 2, in <module>
    from .fields import *
  File "/root/.pgadmin4/local/lib/python2.7/site-packages/flask_wtf/recaptcha/fields.py", line 3, in <module>
    from . import widgets
  File "/root/.pgadmin4/local/lib/python2.7/site-packages/flask_wtf/recaptcha/widgets.py", line 5, in <module>
    from werkzeug import url_encode
ImportError: cannot import name url_encode
</pre>

**Comment by dpage** [comment]
Issue closed on Redmine.
