### ISSUE TITLE
Permission denied '/var/lib/pgadmin/sessions' whit python --load-servers on macOS (RM #5486)

### ISSUE THREAD

**Issue by dpage** [pgadmin-org/pgadmin4#3543]
***Issue migrated from Redmine: https://redmine.postgresql.org/issues/5486***
*Originally created by **Murmansk Manny** at 2020-05-06 11:31:05 UTC.*

I'm trying to import a json file with my servers on a mac laptop, that I've exported from my windows PC.

I've just updated pgAdmin to the last version (4.21).

The command that I'm running is:
<pre>
/Applications/pgAdmin\ 4.app/Contents/Resources/venv/bin/python /Applications/pgAdmin\ 4.app/Contents/Resources/web/setup.py --load-servers /Users/myuser/Desktop/server.json
</pre>

The error it throws is:
<pre>
WARNING: Failed to set ACL on the directory containing the configuration database: [Errno 1] Operation not permitted: '/var/lib/pgadmin'
Traceback (most recent call last):
  File "/Applications/pgAdmin 4.app/Contents/Resources/web/setup.py", line 411, in <module>
    load_servers(args)
  File "/Applications/pgAdmin 4.app/Contents/Resources/web/setup.py", line 171, in load_servers
    app = create_app()
  File "/Applications/pgAdmin 4.app/Contents/Resources/web/pgadmin/__init__.py", line 244, in create_app
    create_app_data_directory(config)
  File "/Applications/pgAdmin 4.app/Contents/Resources/web/pgadmin/setup/data_directory.py", line 40, in create_app_data_directory
    _create_directory_if_not_exists(config.SESSION_DB_PATH)
  File "/Applications/pgAdmin 4.app/Contents/Resources/web/pgadmin/setup/data_directory.py", line 16, in _create_directory_if_not_exists
    os.mkdir(_path)
PermissionError: [Errno 13] Permission denied: '/var/lib/pgadmin/sessions'
</pre>

I tried usint the --user parameter:
<pre>
/Applications/pgAdmin\ 4.app/Contents/Resources/venv/bin/python /Applications/pgAdmin\ 4.app/Contents/Resources/web/setup.py --load-servers /Users/ffebles/Desktop/server.json --user  myuser
</pre>

But it throws the same error:
<pre>
WARNING: Failed to set ACL on the directory containing the configuration database: [Errno 1] Operation not permitted: '/var/lib/pgadmin'
Traceback (most recent call last):
  File "/Applications/pgAdmin 4.app/Contents/Resources/web/setup.py", line 411, in <module>
    load_servers(args)
  File "/Applications/pgAdmin 4.app/Contents/Resources/web/setup.py", line 171, in load_servers
    app = create_app()
  File "/Applications/pgAdmin 4.app/Contents/Resources/web/pgadmin/__init__.py", line 244, in create_app
    create_app_data_directory(config)
  File "/Applications/pgAdmin 4.app/Contents/Resources/web/pgadmin/setup/data_directory.py", line 40, in create_app_data_directory
    _create_directory_if_not_exists(config.SESSION_DB_PATH)
  File "/Applications/pgAdmin 4.app/Contents/Resources/web/pgadmin/setup/data_directory.py", line 16, in _create_directory_if_not_exists
    os.mkdir(_path)
PermissionError: [Errno 13] Permission denied: '/var/lib/pgadmin/sessions'
</pre>

It worked when using sudo, but when I launched pgAdmin it didn't have the loaded servers. I suppose that the configuration was loaded to the root user.

Anything I could test?

**Comment by dpage** [comment]
Issue closed on Redmine.

**Comment by kaurov** [comment]
so what is the solution?

I have the similar issue:
` Failed to create the directory /var/lib/pgadmin/sessions:`

I even added
`    command: bash -c "mkdir -p /var/lib/pgadmin/sessions"`
to my docker-compose.yaml
still have this issue.
