### ISSUE TITLE
Oauth2 login sometimes gives http 500 (RM #7473)

### ISSUE THREAD

**Issue by dpage** [pgadmin-org/pgadmin4#5145]
***Issue migrated from Redmine: https://redmine.postgresql.org/issues/7473***
*Originally created by **pg usr** at 2022-06-14 10:06:44 UTC.*

Hi team, 
We're trying out an oauth2 setup with Azure AAD on K8s. At random times we're sometimes getting a http 500. We tried version 6.10 as well as the latest snapshot and it occurs in both versions. It does seem similar to issue https://redmine.postgresql.org/issues/7059, but that one is solved in the latest snapshot if I understand correct. 

The logs don't show much detail except for a python stack trace. Any help on further pinpointing or resolving the issue is appreciated. 

<pre><code class="shell">
[2022-06-14 09:50:20 +0000] [34] [ERROR] Error handling request /authenticate/login
Traceback (most recent call last):
  File "/venv/lib/python3.9/site-packages/gunicorn/workers/gthread.py", line 271, in handle
    keepalive = self.handle_request(req, conn)
  File "/venv/lib/python3.9/site-packages/gunicorn/workers/gthread.py", line 323, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
  File "/venv/lib/python3.9/site-packages/flask/app.py", line 2095, in __call__
    return self.wsgi_app(environ, start_response)
  File "/pgadmin4/pgAdmin4.py", line 77, in __call__
    return self.app(environ, start_response)
  File "/venv/lib/python3.9/site-packages/werkzeug/middleware/proxy_fix.py", line 187, in __call__
    return self.app(environ, start_response)
  File "/venv/lib/python3.9/site-packages/flask_socketio/__init__.py", line 43, in __call__
    return super(_SocketIOMiddleware, self).__call__(environ,
  File "/venv/lib/python3.9/site-packages/engineio/middleware.py", line 74, in __call__
    return self.wsgi_app(environ, start_response)
  File "/venv/lib/python3.9/site-packages/flask/app.py", line 2080, in wsgi_app
    response = self.handle_exception(e)
  File "/venv/lib/python3.9/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/venv/lib/python3.9/site-packages/flask/app.py", line 1526, in full_dispatch_request
    return self.finalize_request(rv)
  File "/venv/lib/python3.9/site-packages/flask/app.py", line 1547, in finalize_request
    response = self.process_response(response)
  File "/venv/lib/python3.9/site-packages/flask/app.py", line 1892, in process_response
    self.session_interface.save_session(self, ctx.session, response)
  File "/pgadmin4/pgadmin/utils/session.py", line 307, in save_session
    self.manager.put(session)
  File "/pgadmin4/pgadmin/utils/session.py", line 166, in put
    self.parent.put(session)
  File "/pgadmin4/pgadmin/utils/session.py", line 270, in put
    dump(
_pickle.PicklingError: Can't pickle <class 'wtforms.form.Meta'>: attribute lookup Meta on wtforms.form failed
::ffff:10.244.4.67 - - [14/Jun/2022:09:50:20 +0000] "POST /authenticate/login HTTP/1.1" 500 0 "-" "-"
</code></pre>

**Comment by EvertonSA** [comment]
we are also facing this issue with gitlab, it happen often, not always

**Comment by lmaraite** [comment]
Tried the new version 6.15 and it's working now. Thanks a lot!
