### ISSUE TITLE
Can't start pgAdmin on Windows 10 (RM #7557)

### ISSUE THREAD

**Issue by dpage** [pgadmin-org/pgadmin4#5209]
***Issue migrated from Redmine: https://redmine.postgresql.org/issues/7557***
*Originally created by **Frédéric Harison RAMANDANIARIVO** at 2022-07-20 04:57:57 UTC.*

I made a fresh installation of postgresql 13 on Windows 10 from postgresql-13.7-1-windows-x64.exe

Can't launch pgAdmin after, it shows only splash screen

At log file, I see this repeated thorowly:

<pre>
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\PostgreSQL\13\pgAdmin 4\python\Lib\site-packages\werkzeug\serving.py", line 324, in run_wsgi
    execute(self.server.app)
  File "C:\Program Files\PostgreSQL\13\pgAdmin 4\python\Lib\site-packages\werkzeug\serving.py", line 313, in execute
    application_iter = app(environ, start_response)
  File "C:\Program Files\PostgreSQL\13\pgAdmin 4\python\Lib\site-packages\flask\app.py", line 2095, in __call__
    return self.wsgi_app(environ, start_response)
  File "C:\Program Files\PostgreSQL\13\pgAdmin 4\python\Lib\site-packages\flask_socketio\__init__.py", line 43, in __call__
    return super(_SocketIOMiddleware, self).__call__(environ,
  File "C:\Program Files\PostgreSQL\13\pgAdmin 4\python\Lib\site-packages\engineio\middleware.py", line 74, in __call__
    return self.wsgi_app(environ, start_response)
  File "C:\Program Files\PostgreSQL\13\pgAdmin 4\python\Lib\site-packages\flask\app.py", line 2080, in wsgi_app
    response = self.handle_exception(e)
  File "C:\Program Files\PostgreSQL\13\pgAdmin 4\python\Lib\site-packages\flask\app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Program Files\PostgreSQL\13\pgAdmin 4\python\Lib\site-packages\flask\app.py", line 1518, in full_dispatch_request
    self.try_trigger_before_first_request_functions()
  File "C:\Program Files\PostgreSQL\13\pgAdmin 4\python\Lib\site-packages\flask\app.py", line 1570, in try_trigger_before_first_request_functions
    self.ensure_sync(func)()
  File "C:\Program Files\PostgreSQL\13\pgAdmin 4\web\pgadmin\utils\__init__.py", line 55, in create_module_preference
    self.register_preferences()
  File "C:\Program Files\PostgreSQL\13\pgAdmin 4\web\pgadmin\browser\server_groups\servers\__init__.py", line 330, in register_preferences
    ServerType.register_preferences()
  File "C:\Program Files\PostgreSQL\13\pgAdmin 4\web\pgadmin\browser\server_groups\servers\types.py", line 124, in register_preferences
    paths.migrate_user_preferences(st.utility_path.pid,
  File "C:\Program Files\PostgreSQL\13\pgAdmin 4\web\pgadmin\utils\preferences.py", line 656, in migrate_user_preferences
    pref.value = converter_func(pref.value)
  File "C:\Program Files\PostgreSQL\13\pgAdmin 4\web\pgadmin\browser\server_groups\servers\types.py", line 108, in path_converter
    {item['version']: item for item in json.loads(old_path)}
  File "json\__init__.py", line 346, in loads
    
  File "json\decoder.py", line 337, in decode
    
  File "json\decoder.py", line 355, in raw_decode
    
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

2022-07-20 07:24:14,413: ERROR	werkzeug:	Error on request:
Traceback (most recent call last):
  File "json\decoder.py", line 353, in raw_decode
    
StopIteration: 0
</pre>

**Comment by FaharAbbasRizvi** [comment]
Tested in the candidate build for v6.14
