### ISSUE TITLE
Warning in console while Saving database properties (RM #7703)

### ISSUE THREAD

**Issue by dpage** [pgadmin-org/pgadmin4#5332]
***Issue migrated from Redmine: https://redmine.postgresql.org/issues/7703***
*Originally created by **Yogesh Mahajan** at 2022-09-13 08:22:45 UTC.*

<pre>
DecorationManager.js:20 Uncaught (in promise) TypeError: Cannot destructure property 'applicable' of 'this.getDecorationData(...)' as it is null.
    at DecorationsManager.targetDecoration (DecorationManager.js:20:21)
    at eval (index.js:40:30)
    at Set.forEach (<anonymous>)
    at Notificar.dispatch (index.js:40:14)
    at Decoration.addTarget (Decoration.js:62:21)
    at _callee4$ (index.tsx:386:39)
    at tryCatch (runtime.js:63:40)
    at Generator.invoke [as _invoke] (runtime.js:294:22)
    at Generator.eval [as next] (runtime.js:119:21)
    at asyncGeneratorStep (index.tsx:122:103)
</pre>

Issue is observed in 6.13 released version also

**Comment by pravesh-sharma** [comment]
tested in latest code and is fixed.
