### ISSUE TITLE
pgadmin4 on python3.10 alpine3.16

### ISSUE THREAD

**Issue by RekGRpth** [pgadmin-org/pgadmin4#5336]
pgadmin4 is installed via
```sh
pip install --no-cache-dir --prefix /usr/local pgadmin4
```
got error
```python
Traceback (most recent call last):

  File "/usr/local/lib/python3.10/site-packages/pgadmin4/pgAdmin4.py", line 38, in <module>

    import config

  File "/usr/local/lib/python3.10/site-packages/pgadmin4/config.py", line 25, in <module>

    from pgadmin.utils import env, IS_WIN, fs_short_path

  File "/usr/local/lib/python3.10/site-packages/pgadmin4/pgadmin/__init__.py", line 28, in <module>

    from flask_login import user_logged_in, user_logged_out

  File "/usr/lib/python3.10/site-packages/flask_login/__init__.py", line 16, in <module>

    from .login_manager import LoginManager

  File "/usr/lib/python3.10/site-packages/flask_login/login_manager.py", line 24, in <module>

    from .utils import (login_url as make_login_url, _create_identifier,

  File "/usr/lib/python3.10/site-packages/flask_login/utils.py", line 13, in <module>

    from werkzeug.security import safe_str_cmp

ImportError: cannot import name 'safe_str_cmp' from 'werkzeug.security' (/usr/local/lib/python3.10/site-packages/werkzeug/security.py)

unable to load app 0 (mountpoint='/pgadmin4') (callable not found or import error)
```

**Comment by RekGRpth** [comment]
duplicate https://github.com/pgadmin-org/pgadmin4/issues/5285
