### ISSUE TITLE
Oauth2 issue while logging wasn't finished

### ISSUE THREAD

**Issue by piramix** [pgadmin-org/pgadmin4#5339]
Hi,

I'm getting Internal Server Error in a specific case when logging in process isn't finished.
When I start logging in using Oauth2 and won't finish the process and enter again on login page of pgadmin to start again the process using Oauth2 I'm getting Internal Server Error and in logs I have this:
```
[2022-09-15 12:41:26 +0000] [87] [ERROR] Error handling request /authenticate/login
Traceback (most recent call last):
  File "/venv/lib/python3.10/site-packages/gunicorn/workers/gthread.py", line 271, in handle
    keepalive = self.handle_request(req, conn)
  File "/venv/lib/python3.10/site-packages/gunicorn/workers/gthread.py", line 323, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
  File "/venv/lib/python3.10/site-packages/flask/app.py", line 2091, in __call__
    return self.wsgi_app(environ, start_response)
  File "/pgadmin4/pgAdmin4.py", line 76, in __call__
    return self.app(environ, start_response)
  File "/venv/lib/python3.10/site-packages/werkzeug/middleware/proxy_fix.py", line 187, in __call__
    return self.app(environ, start_response)
  File "/venv/lib/python3.10/site-packages/flask_socketio/__init__.py", line 43, in __call__
    return super(_SocketIOMiddleware, self).__call__(environ,
  File "/venv/lib/python3.10/site-packages/engineio/middleware.py", line 74, in __call__
    return self.wsgi_app(environ, start_response)
  File "/venv/lib/python3.10/site-packages/flask/app.py", line 2076, in wsgi_app
    response = self.handle_exception(e)
  File "/venv/lib/python3.10/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/venv/lib/python3.10/site-packages/flask/app.py", line 1520, in full_dispatch_request
    return self.finalize_request(rv)
  File "/venv/lib/python3.10/site-packages/flask/app.py", line 1541, in finalize_request
    response = self.process_response(response)
  File "/venv/lib/python3.10/site-packages/flask/app.py", line 1888, in process_response
    self.session_interface.save_session(self, ctx.session, response)
  File "/pgadmin4/pgadmin/utils/session.py", line 307, in save_session
    self.manager.put(session)
  File "/pgadmin4/pgadmin/utils/session.py", line 166, in put
    self.parent.put(session)
  File "/pgadmin4/pgadmin/utils/session.py", line 270, in put
    dump(
_pickle.PicklingError: Can't pickle <class 'wtforms.form.Meta'>: attribute lookup Meta on wtforms.form failed
```

**Comment by Florian-Sabonchi** [comment]
Hello thanks for your comment. I will look on it at weekend

**Comment by adityatoshniwal** [comment]
@piramix If you can find `/var/lib/pgadmin` then you can try:
1. Stop pgAdmin
2. Remove `/var/lib/pgadmin/sessions` directory
3. Start pgAdmin.

**Comment by nikhil-mohite** [comment]
duplicates #5145
