### ISSUE TITLE
Password recovery link doesn't work - Method not allowed

### ISSUE THREAD

**Issue by SmallhillCZ** [pgadmin-org/pgadmin4#5397]
Clicking the password recovery link yields Method not allowed error.

I'm running in Docker behing Traefik, but it seems to be an issue in pgAdmin.

Here is the log of pgAdmin:

```
admin.pgadmin  | 2022-10-04 15:14:12,125: ERROR pgadmin:        405 Method Not Allowed: The method is not allowed for the requested URL.
admin.pgadmin  | Traceback (most recent call last):
admin.pgadmin  |   File "/venv/lib/python3.10/site-packages/flask/app.py", line 1517, in full_dispatch_request
admin.pgadmin  |     rv = self.dispatch_request()
admin.pgadmin  |   File "/venv/lib/python3.10/site-packages/flask/app.py", line 1493, in dispatch_request
admin.pgadmin  |     self.raise_routing_exception(req)
admin.pgadmin  |   File "/venv/lib/python3.10/site-packages/flask/app.py", line 1475, in raise_routing_exception
admin.pgadmin  |     raise request.routing_exception  # type: ignore
admin.pgadmin  |   File "/venv/lib/python3.10/site-packages/flask/ctx.py", line 397, in match_request
admin.pgadmin  |     result = self.url_adapter.match(return_rule=True)  # type: ignore
admin.pgadmin  |   File "/venv/lib/python3.10/site-packages/werkzeug/routing.py", line 2042, in match
admin.pgadmin  |     raise MethodNotAllowed(valid_methods=list(have_match_for))
admin.pgadmin  | werkzeug.exceptions.MethodNotAllowed: 405 Method Not Allowed: The method is not allowed for the requested URL.
admin.pgadmin  | 212.80.67.246 - - [04/Oct/2022:15:14:12 +0000] "GET /browser/reset_password/TOKEN_REMOVED HTTP/1.1" 405 153 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36"
```

**Comment by khushboovashi** [comment]
Which docker image have you used to install pgAdmin 4? 
The password recover url should be /browser/reset_password/  NOT /browser/reset_password/TOKEN_REMOVED (as per your logs).

**Comment by SmallhillCZ** [comment]
the latest one, docker CLI lists it as
```
REPOSITORY                                                   TAG         IMAGE ID       CREATED         SIZE
dpage/pgadmin4                                               latest      94c0924749b6   2 weeks ago     366MB
```

and the token is passed how? the `TOKEN_REMOVED` is replaced where the token actually was

**Comment by FaharAbbasRizvi** [comment]
This is tested in the latest snapshot build.
