### ISSUE TITLE
Insternal Server Error

### ISSUE THREAD

**Issue by Kaczuc** [pgadmin-org/pgadmin4#5431]
Hey I'm using pgadmin in a docker container with a reverse proxy and cloudflare ran into such a problem when logging in

```
wtforms.validators.ValidationError: The CSRF token is invalid.
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/venv/lib/python3.10/site-packages/flask/app.py", line 1515, in full_dispatch_request
    rv = self.preprocess_request()
  File "/venv/lib/python3.10/site-packages/flask/app.py", line 1857, in preprocess_request
    rv = self.ensure_sync(before_func)()
  File "/venv/lib/python3.10/site-packages/flask_wtf/csrf.py", line 229, in csrf_protect
    self.protect()
  File "/venv/lib/python3.10/site-packages/flask_wtf/csrf.py", line 264, in protect
    self._error_response(e.args[0])
  File "/venv/lib/python3.10/site-packages/flask_wtf/csrf.py", line 307, in _error_response
    raise CSRFError(reason)
```

**Comment by Kaczuc** [comment]
I solved the problem disabling the cache add-ons however there is a problem with 
![image](https://user-images.githubusercontent.com/43011737/195445028-8725476c-d2e8-489c-90bd-c06e699a5324.png)

**Comment by khushboovashi** [comment]
@Kaczuc, set PGADMIN_CONFIG_WTF_CSRF_ENABLED to False and try.

**Comment by yogeshmahajan-1903** [comment]
@Kaczuc 
Can you please share complete docker-compose file?

**Comment by pravesh-sharma** [comment]
No response from author hence closing.
