### ISSUE TITLE
SSLCertVerificationError with oAuth2 identity provider

### ISSUE THREAD

**Issue by FunLow** [pgadmin-org/pgadmin4#5492]
Hey,

I am trying to setup pgadmin oauth with a keycloak as identity provider. PGadmin is deployed as container into an kubernetes environment. The keycloak itself is using a self signed certificate for the domains. Oauth seems to work as far as i got but pgadmin is failing after authentication to access to the token endpoint of keycloak due to an SSLCertVerificationError.
```
Traceback (most recent call last):
File "/venv/lib/python3.10/site-packages/flask/app.py", line 1517, in full_dispatch_request
rv = self.dispatch_request()
File "/venv/lib/python3.10/site-packages/flask/app.py", line 1503, in dispatch_request
return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
File "/pgadmin4/pgadmin/authenticate/oauth2.py", line 55, in oauth_authorize
status, msg = auth_obj.login()
File "/pgadmin4/pgadmin/authenticate/init.py", line 268, in login
status, msg = self.source.login(self.form)
File "/pgadmin4/pgadmin/authenticate/oauth2.py", line 121, in login
profile = self.get_user_profile()
File "/pgadmin4/pgadmin/authenticate/oauth2.py", line 146, in get_user_profile
self.oauth2_current_client].authorize_access_token()
File "/venv/lib/python3.10/site-packages/authlib/integrations/flask_client/remote_app.py", line 76, in authorize_access_token
token = self.fetch_access_token(**params)
File "/venv/lib/python3.10/site-packages/authlib/integrations/base_client/remote_app.py", line 112, in fetch_access_token
token = client.fetch_token(token_endpoint, **kwargs)
File "/venv/lib/python3.10/site-packages/authlib/oauth2/client.py", line 203, in fetch_token
return self._fetch_token(
File "/venv/lib/python3.10/site-packages/authlib/oauth2/client.py", line 220, in _fetch_token
resp = self.session.request(
File "/venv/lib/python3.10/site-packages/authlib/integrations/requests_client/oauth2_session.py", line 112, in request
return super(OAuth2Session, self).request(
File "/venv/lib/python3.10/site-packages/requests/sessions.py", line 542, in request
resp = self.send(prep, **send_kwargs)
File "/venv/lib/python3.10/site-packages/requests/sessions.py", line 655, in send
r = adapter.send(request, **kwargs)
File "/venv/lib/python3.10/site-packages/requests/adapters.py", line 514, in send
raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='>keycloak_domain>', port=443): Max retries exceeded with url: /auth/realms/<my_realm>/protocol/openid-connect/token (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:997)')))
```

I already saw a very similiar issue that is refering to the exact same issue but all suggested solutions doesnt work. [See this Issue](https://github.com/pgadmin-org/pgadmin4/issues/4978).
/pgadmin4/cacert.crt

I tried to add the CA and CA chain to trust the domain with different approaches:

1. Add CA to the trust store of the container
2. Add CA to the default config path specified in the config_distro.py /pgadmin4/cacert.crt
3. Add CA to a custom place and configure CA_FILE to use the proper certificate

Using Curl it successfully verifies the certificate authority but pgadmin still doesn't.

But nothing seems to work here. Any further ideas how to solve this ? Is there maybe a virtual environment used by python that is not able to access the trust store in some way ?

**Comment by yogeshmahajan-1903** [comment]
@FunLow  Try sending the environment variable PGADMIN_CONFIG_CA_FILE to the docker image.
PGADMIN_CONFIG_CA_FILE = custom cert path
Please refer to the https://www.pgadmin.org/docs/pgadmin4/6.15/container_deployment.html#environment-variables

**Comment by pravesh-sharma** [comment]
No response from author hence closing.

**Comment by FunLow** [comment]
Using the environment variables mentioned by you and the documentation was not working. The only way to work around this were using the environment variable of python REQUEST_CA_BUNDLE.
