### ISSUE TITLE
Docker container logs IndexError: list index out of range

### ISSUE THREAD

**Issue by bigteejay** [pgadmin-org/pgadmin4#5518]
I believe I've followed the instructions for [container deployment](https://www.pgadmin.org/docs/pgadmin4/latest/container_deployment.html) (and found no other issues reported with this same/specific scenario).  Hosting two different programs/systems behind a single reverse proxy, traffic directed by path under root.

The code below results in an error in `gunicorn` while executing, `path_info = path_info.split(script_name, 1)[1]`... and removal of the `SCRIPT_NAME` environment variable in the `docker-compose` file below does avoid the error message (but is then unreachable).

It appears to be trying to split a path in a base library, based on the `script_name` variable, once, and grabs the second (zero-based index) element returned?  At the bottom of the [docs](https://www.pgadmin.org/docs/pgadmin4/development/container_deployment.html) where it refers to the SCRIPT_NAME variable, it appears to indicate usage as I'm using below (rather than an array of some sort, which I also tried).

I imagine it has to be a misconfiguration on my part as, using `dpage/pgadmin4:6.15` through `6.8` (`6.8` was just the last one I checked) I get the same error message...

<details><summary>.env</summary>

> ```
> PGADMIN_ADMINEMAIL="no-reply@example.com"
> PGADMIN_DEFAULTPASSWORD="secret"
> ```

</details>

<details><summary>nginx.conf</summary>

> ```
> worker_processes 1;
> events { worker_connections 1024; }
> 
> http {
>     server {
>         listen 81;
>         listen [::]:81;
> 
>         server_name _;
>         access_log /var/log/nginx/site.access.log;
>         error_log /var/log/nginx/site.error.log;
> 
>         location /localdb/ {
>             proxy_set_header X-Script-Name /localdb;
>             proxy_set_header Host $host;
>             proxy_pass http://pgadmin:80/;
>             proxy_redirect off;
>         }
> 
>         location ~* /(admin|dashboard)/ {
>             proxy_pass http://app2:1880;
>             proxy_redirect off;
>         }
>     }
> }
> ```

</details>

<details><summary>docker-compose.yml</summary>

> ```
> networks:
>   frontend:
>     name: frontend
>   backend:
>     name: backend
> 
> services:
>   revproxy:
>     image: nginx:1.23.2-alpine
>     container_name: revproxy
>     restart: unless-stopped
>     networks:
>       - frontend
>       - backend
>     ports:
>       - "81:81"
>     volumes:
>       - ./nginx.conf:/etc/nginx/nginx.conf
> 
>   pgadmin:
>     image: dpage/pgadmin4:6.15  # or 6.14, 13, 12, ...8 (6.8 was the last I checked)
>     container_name: pgadmin
>     restart: unless-stopped
>     environment:
>       - PGADMIN_DEFAULT_EMAIL=${PGADMIN_ADMINEMAIL}
>       - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULTPASSWORD}
>       - SCRIPT_NAME=/localdb
>     networks:
>       - backend
> 
>   app2:
>     image: nodered/node-red:3.0.1-16-minimal
>     container_name: app2
>     restart: unless-stopped
>     networks:
>       - backend
> ```

</details>

<details><summary>Starting...</summary>

> ```
> > docker compose up
> [+] Running 5/5
>  - Network backend     Created                                                                                     0.1s
>  - Network frontend    Created                                                                                     0.1s
>  - Container app2      Started                                                                                     1.3s
>  - Container pgadmin   Started                                                                                     1.2s
>  - Container revproxy  Started                                                                                     1.5s
> Attaching to app2, pgadmin, revproxy
> app2      | Welcome to Node-RED
> {...SNIP...}
> app2      | 12 Nov 23:53:04 - [info] Started flows
> pgadmin   | NOTE: Configuring authentication for SERVER mode.
> pgadmin   |
> pgadmin   | pgAdmin 4 - Application Initialisation
> pgadmin   | ======================================
> pgadmin   |
> pgadmin   | [2022-11-12 23:53:21 +0000] [1] [INFO] Starting gunicorn 20.1.0
> pgadmin   | [2022-11-12 23:53:21 +0000] [1] [INFO] Listening at: http://[::]:80 (1)
> pgadmin   | [2022-11-12 23:53:21 +0000] [1] [INFO] Using worker: gthread
> pgadmin   | [2022-11-12 23:53:21 +0000] [91] [INFO] Booting worker with pid: 91
> ```

</details>

<details><summary>Output</summary>

In web browser, http://localhost:81/localdb/...

> Internal Server Error

Terminal with docker compose now shows...

> ```
> pgadmin   | [2022-11-12 23:53:21 +0000] [91] [INFO] Booting worker with pid: 91
> pgadmin   | [2022-11-12 23:53:38 +0000] [91] [ERROR] Error handling request /
> pgadmin   | Traceback (most recent call last):
> pgadmin   |   File "/venv/lib/python3.10/site-packages/gunicorn/workers/gthread.py", line 271, in handle
> pgadmin   |     keepalive = self.handle_request(req, conn)
> pgadmin   |   File "/venv/lib/python3.10/site-packages/gunicorn/workers/gthread.py", line 308, in handle_request
> pgadmin   |     resp, environ = wsgi.create(req, conn.sock, conn.client,
> pgadmin   |   File "/venv/lib/python3.10/site-packages/gunicorn/http/wsgi.py", line 183, in create
> pgadmin   |     path_info = path_info.split(script_name, 1)[1]
> pgadmin   | IndexError: list index out of range
> pgadmin   | ::ffff:192.168.80.4 - - [12/Nov/2022:23:53:38 +0000] "GET / HTTP/1.0" 500 0 "-" "-"
> ```

</details>

`docker compose down` to remove the provisioned resources once done.

**Comment by bigteejay** [comment]
This [issue](https://github.com/benoitc/gunicorn/issues/679#issuecomment-32309679) from another project documented the issue and the fix (remove trailing "`/`" from proxy_pass)
