### ISSUE TITLE
Query tool does not open when user is not defined

### ISSUE THREAD

**Issue by jouve** [pgadmin-org/pgadmin4#5575]
when opening the query tool, I see the following message:
`{"success":0,"errormsg":"'NoneType' object has no attribute 'replace'","info":"","result":null,"data":null}` instead of the query tool.

how to reproduce:
* create a Server with only General>Name & Connection>Service (configuration in pg_service.conf)
* connect to the database (OK)
* open query tool 

workaround: add a Username in Connection>Username, the query tool works again

logs:
```
2022-11-25 14:52:12,005: ERROR	pgadmin:	'NoneType' object has no attribute 'replace'
Traceback (most recent call last):
  File "/Applications/pgAdmin 4.app/Contents/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/flask/app.py", line 1517, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Applications/pgAdmin 4.app/Contents/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/flask/app.py", line 1503, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/Applications/pgAdmin 4.app/Contents/Resources/web/pgadmin/tools/sqleditor/__init__.py", line 317, in panel
    params['user'] = underscore_escape(s.username)
  File "/Applications/pgAdmin 4.app/Contents/Resources/web/pgadmin/browser/utils.py", line 47, in underscore_escape
    text = text.replace(c, r)
AttributeError: 'NoneType' object has no attribute 'replace'
```

**Comment by nboisteault** [comment]
@jouve Many thanks for the bug issue and the workaround. I've spent many hours trying to understand this issue.

**Comment by pravesh-sharma** [comment]
This is tested on candidate build and is fixed.
