### ISSUE TITLE
Docker container: PGADMIN_DEFAULT_EMAIL is set but PGADMIN still requiring ENTER_EMAIL_ADDRESS

### ISSUE THREAD

**Issue by appost** [pgadmin-org/pgadmin4#5592]
The command
`docker run -p 8003:80 --name pgadmin4 --restart=no -e 'PGADMIN_DEFAULT_EMAIL=admin@admin.com' --env 'PGADMIN_DEFAULT_PASSWORD=secret' --env 'PGADMIN_LISTEN_PORT=80'`

fails with the following error:
```
Traceback (most recent call last):
  File "/pgadmin4/pgadmin/__init__.py", line 372, in backup_db_file
    db_upgrade(app)
  File "/pgadmin4/pgadmin/setup/db_upgrade.py", line 25, in db_upgrade
    flask_migrate.upgrade(migration_folder)
  File "/venv/lib/python3.10/site-packages/flask_migrate/__init__.py", line 98, in wrapped
    f(*args, **kwargs)
  File "/venv/lib/python3.10/site-packages/flask_migrate/__init__.py", line 185, in upgrade
    command.upgrade(config, revision, sql=sql, tag=tag)
  File "/venv/lib/python3.10/site-packages/alembic/command.py", line 322, in upgrade
    script.run_env()
  File "/venv/lib/python3.10/site-packages/alembic/script/base.py", line 569, in run_env
    util.load_python_file(self.dir, "env.py")
  File "/venv/lib/python3.10/site-packages/alembic/util/pyfiles.py", line 94, in load_python_file
    module = load_module_py(module_id, path)
  File "/venv/lib/python3.10/site-packages/alembic/util/pyfiles.py", line 110, in load_module_py
    spec.loader.exec_module(module)  # type: ignore
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/pgadmin4/pgadmin/setup/../../migrations/env.py", line 93, in <module>
    run_migrations_online()
  File "/pgadmin4/pgadmin/setup/../../migrations/env.py", line 86, in run_migrations_online
    context.run_migrations()
  File "<string>", line 8, in run_migrations
  File "/venv/lib/python3.10/site-packages/alembic/runtime/environment.py", line 853, in run_migrations
    self.get_context().run_migrations(**kw)
  File "/venv/lib/python3.10/site-packages/alembic/runtime/migration.py", line 623, in run_migrations
    step.migration_fn(**kw)
  File "/pgadmin4/migrations/versions/fdc58d9bd449_.py", line 43, in upgrade
    email, password = user_info()
  File "/pgadmin4/pgadmin/setup/user_info.py", line 75, in user_info
    email, p1 = user_info_server()
  File "/pgadmin4/pgadmin/setup/user_info.py", line 52, in user_info_server
    email = input(ENTER_EMAIL_ADDRESS)
EOFError: EOF when reading a line
```

**Comment by yogeshmahajan-1903** [comment]
@appost 
Hello,  I am able to launch pgAdmin container successfully with above command.

```yogeshmahajan@Laptop510-pn-in pgadmin4 % docker run -p 8003:80 --name pgadmin4 --restart=no -e 'PGADMIN_DEFAULT_EMAIL=admin@admin.com' --env 'PGADMIN_DEFAULT_PASSWORD=secret' --env 'PGADMIN_LISTEN_PORT=80' -d dpage/pgadmin4
52ae3e4cb637ec272e167fcda088e7a6b30801ca04ed298e267c635e1cfe04c1
yogeshmahajan@Laptop510-pn-in pgadmin4 % docker ps -a
CONTAINER ID   IMAGE            COMMAND            CREATED         STATUS         PORTS                           NAMES
52ae3e4cb637   dpage/pgadmin4   "/entrypoint.sh"   6 seconds ago   Up 5 seconds   443/tcp, 0.0.0.0:8003->80/tcp   pgadmin4

yogeshmahajan@Laptop-pn-in pgadmin4 % docker logs 52ae3e4cb637
NOTE: Configuring authentication for SERVER mode.

pgAdmin 4 - Application Initialisation
======================================

[2022-11-30 05:26:36 +0000] [1] [INFO] Starting gunicorn 20.1.0
[2022-11-30 05:26:36 +0000] [1] [INFO] Listening at: http://[::]:80 (1)
[2022-11-30 05:26:36 +0000] [1] [INFO] Using worker: gthread
[2022-11-30 05:26:36 +0000] [90] [INFO] Booting worker with pid: 90

```

**Comment by appost** [comment]
Thanks your comment has been very helpful.
The problem was actually in the volume permission with rootless docker (which I omitted in the run command). I solved by deleting the folder on the host and creating a new one with permission as 777

**Comment by yogeshmahajan-1903** [comment]
Glad it worked.
