### ISSUE TITLE
Error: Missing "jwks_uri" in metadata during OAuth2 Authentication

### ISSUE THREAD

**Issue by tsschubert** [pgadmin-org/pgadmin4#5711]
**Describe the bug**

Authenticating using OAuth2 (Okta in this case) results in the following error to the client browser:
`{"success":0,"errormsg":"Missing \"jwks_uri\" in metadata","info":"","result":null,"data":null}`
This is only experienced in 6.18

**To Reproduce**

1. Set up PgAdmin4:6.18 with oauth2
2. Click on "Login with (oauth2 provider)"
3. See the error

**Expected behavior**

The user is authenticated to PgAdmin and can see the landing page.

**Error message**
```
2023-01-04 23:46:48,260: DEBUG	pgadmin:	Authentication initiated via source: oauth2
<IP> - - [04/Jan/2023:23:46:48 +0000] "POST /authenticate/login HTTP/1.1" 302 793 "https://pgadmin-pgadmin.application.staging.tech-qa.com/login?next=%2F" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36"
2023-01-04 23:46:49,396: ERROR	pgadmin:	Missing "jwks_uri" in metadata
Traceback (most recent call last):
  File "/venv/lib/python3.10/site-packages/flask/app.py", line 1517, in full_dispatch_request
    rv = self.dispatch_request()
  File "/venv/lib/python3.10/site-packages/flask/app.py", line 1503, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/pgadmin4/pgadmin/authenticate/oauth2.py", line 55, in oauth_authorize
    status, msg = auth_obj.login()
  File "/pgadmin4/pgadmin/authenticate/__init__.py", line 268, in login
    status, msg = self.source.login(self.form)
  File "/pgadmin4/pgadmin/authenticate/oauth2.py", line 121, in login
    profile = self.get_user_profile()
  File "/pgadmin4/pgadmin/authenticate/oauth2.py", line 163, in get_user_profile
    self.oauth2_current_client].authorize_access_token()
  File "/venv/lib/python3.10/site-packages/authlib/integrations/flask_client/apps.py", line 108, in authorize_access_token
    userinfo = self.parse_id_token(token, nonce=state_data['nonce'], claims_options=claims_options)
  File "/venv/lib/python3.10/site-packages/authlib/integrations/base_client/sync_openid.py", line 66, in parse_id_token
    claims = _jwt.decode(
  File "/venv/lib/python3.10/site-packages/authlib/jose/rfc7519/jwt.py", line 96, in decode
    data = self._jws.deserialize_compact(s, load_key, decode_payload)
  File "/venv/lib/python3.10/site-packages/authlib/jose/rfc7515/jws.py", line 101, in deserialize_compact
    algorithm, key = self._prepare_algorithm_key(jws_header, payload, key)
  File "/venv/lib/python3.10/site-packages/authlib/jose/rfc7515/jws.py", line 254, in _prepare_algorithm_key
    key = key(header, payload)
  File "/venv/lib/python3.10/site-packages/authlib/integrations/base_client/sync_openid.py", line 38, in load_key
    jwk_set = JsonWebKey.import_key_set(self.fetch_jwk_set())
  File "/venv/lib/python3.10/site-packages/authlib/integrations/base_client/sync_openid.py", line 14, in fetch_jwk_set
    raise RuntimeError('Missing "jwks_uri" in metadata')
RuntimeError: Missing "jwks_uri" in metadata
<IP> - - [04/Jan/2023:23:46:49 +0000] "GET /oauth2/authorize?code=<>&state=<> HTTP/1.1" 500 95 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36"
```

**Additional context**

This has only been experienced with pgadmin4:6.18. Password authentication still works.

**Comment by tsschubert** [comment]
Looks like this is likely a duplicate of  https://github.com/pgadmin-org/pgadmin4/issues/5666
