### ISSUE TITLE
Unable to run pgadmin4 with dnspython v. 2.3.0

### ISSUE THREAD

**Issue by ya-pekatoros** [pgadmin-org/pgadmin4#5744]
Hello! I faced the following problem with running pgadmin4.

The problem seems to be described here:
https://github.com/eventlet/eventlet/issues/781

Anyway with dnspython < 2.3.0 everything works fine.

```
(pgadmin4)  SQL $ pgadmin4
Traceback (most recent call last):
  File "/home/ypekatoros/SQL/pgadmin4/bin/pgadmin4", line 5, in <module>
    from pgadmin4.pgAdmin4 import main
  File "/home/ypekatoros/SQL/pgadmin4/lib/python3.10/site-packages/pgadmin4/pgAdmin4.py", line 38, in <module>
    import config
  File "/home/ypekatoros/SQL/pgadmin4/lib/python3.10/site-packages/pgadmin4/config.py", line 25, in <module>
    from pgadmin.utils import env, IS_WIN, fs_short_path
  File "/home/ypekatoros/SQL/pgadmin4/lib/python3.10/site-packages/pgadmin4/pgadmin/__init__.py", line 24, in <module>
    from flask_socketio import SocketIO
  File "/home/ypekatoros/SQL/pgadmin4/lib/python3.10/site-packages/flask_socketio/__init__.py", line 9, in <module>
    from socketio import socketio_manage  # noqa: F401
  File "/home/ypekatoros/SQL/pgadmin4/lib/python3.10/site-packages/socketio/__init__.py", line 9, in <module>
    from .zmq_manager import ZmqManager
  File "/home/ypekatoros/SQL/pgadmin4/lib/python3.10/site-packages/socketio/zmq_manager.py", line 5, in <module>
    import eventlet.green.zmq as zmq
  File "/home/ypekatoros/SQL/pgadmin4/lib/python3.10/site-packages/eventlet/__init__.py", line 17, in <module>
    from eventlet import convenience
  File "/home/ypekatoros/SQL/pgadmin4/lib/python3.10/site-packages/eventlet/convenience.py", line 7, in <module>
    from eventlet.green import socket
  File "/home/ypekatoros/SQL/pgadmin4/lib/python3.10/site-packages/eventlet/green/socket.py", line 21, in <module>
    from eventlet.support import greendns
  File "/home/ypekatoros/SQL/pgadmin4/lib/python3.10/site-packages/eventlet/support/greendns.py", line 66, in <module>
    setattr(dns, pkg, import_patched('dns.' + pkg))
  File "/home/ypekatoros/SQL/pgadmin4/lib/python3.10/site-packages/eventlet/support/greendns.py", line 61, in import_patched
    return patcher.import_patched(module_name, **modules)
  File "/home/ypekatoros/SQL/pgadmin4/lib/python3.10/site-packages/eventlet/patcher.py", line 132, in import_patched
    return inject(
  File "/home/ypekatoros/SQL/pgadmin4/lib/python3.10/site-packages/eventlet/patcher.py", line 109, in inject
    module = __import__(module_name, {}, {}, module_name.split('.')[:-1])
  File "/home/ypekatoros/SQL/pgadmin4/lib/python3.10/site-packages/dns/zone.py", line 86, in <module>
    class Zone(dns.transaction.TransactionManager):
  File "/home/ypekatoros/SQL/pgadmin4/lib/python3.10/site-packages/dns/zone.py", line 757, in Zone
    ) -> dns.rdtypes.ANY.SOA.SOA:
AttributeError: module 'dns.rdtypes' has no attribute 'ANY'
```

**Comment by khushboovashi** [comment]
We have fixed this issue in the latest release.
