### ISSUE TITLE
Seems to be bug in internal connection form validation

### ISSUE THREAD

**Issue by ya-pekatoros** [pgadmin-org/pgadmin4#5745]
Hello! After installing pgadmin4 and setting user email and pass I get the following error. I've tried using different browsers and several times, and I've also tried re-installing pgadmin several times. I use python 3.10.6 and follow this instruction: https://www.pgadmin.org/download/pgadmin-4-python/.  

The problem seems to be somewhere here (sorry that I didn't reach the root of the problem, I've tried, but I am not experienced in Flask and its environment):
![image](https://user-images.githubusercontent.com/115944825/212878370-6835cfa2-ecc4-40cb-82f6-1b2b08292b2f.png)

For example: if we change underlined callings to 'True' we can log in correctly.

```
(pgadmin4)  SQL $ pgadmin4
NOTE: Configuring authentication for SERVER mode.

Enter the email address and password to use for the initial pgAdmin user account:

Email address: myemail@mail.com
Password:
Retype password:
pgAdmin 4 - Application Initialisation
======================================

Starting pgAdmin 4. Please navigate to http://127.0.0.1:5050 in your browser.
2023-01-17 13:32:31,990: WARNING        werkzeug:       WebSocket transport not available. Install simple-websocket for improved performance.
 * Serving Flask app 'pgadmin' (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
The email address is not valid. It must have exactly one @-sign.
2023-01-17 13:36:38,860: ERROR  pgadmin:        LoginForm.validate() takes 1 positional argument but 2 were given
Traceback (most recent call last):
  File "/home/ypekatoros/SQL/pgadmin4/lib/python3.10/site-packages/flask/app.py", line 1517, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/ypekatoros/SQL/pgadmin4/lib/python3.10/site-packages/flask/app.py", line 1503, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/ypekatoros/SQL/pgadmin4/lib/python3.10/site-packages/pgadmin4/pgadmin/authenticate/__init__.py", line 116, in login
    if not auth_obj.validate():
  File "/home/ypekatoros/SQL/pgadmin4/lib/python3.10/site-packages/pgadmin4/pgadmin/authenticate/__init__.py", line 239, in validate
    status, err_msg = source.validate(self.form)
  File "/home/ypekatoros/SQL/pgadmin4/lib/python3.10/site-packages/pgadmin4/pgadmin/authenticate/internal.py", line 102, in validate
    submit = form.validate_on_submit()
  File "/home/ypekatoros/SQL/pgadmin4/lib/python3.10/site-packages/flask_wtf/form.py", line 86, in validate_on_submit
    return self.is_submitted() and self.validate(extra_validators)
TypeError: LoginForm.validate() takes 1 positional argument but 2 were given
```

**Comment by khushboovashi** [comment]
Hello,

Please pin Flask-WTF to 1.0.1, that will solve your issue.

**Comment by ya-pekatoros** [comment]
> Hello,
> 
> Please pin Flask-WTF to 1.0.1, that will solve your issue.

Thank you!
