### ISSUE TITLE
Add partition to existing table gives console error

### ISSUE THREAD

**Issue by adityatoshniwal** [pgadmin-org/pgadmin4#5748]
**Describe the bug**
Using properties, add partition to an existing partition table. The new partition is not added to parititions  collection. Instead, there is a console error:
```
browser.js:1775 Uncaught (in promise) TypeError: _lodash.default.mapObject is not a function
    at Object.addChildTreeNodes (browser.js:1775:94)
    at insertChildrenNodes (table.js:345:25)
    at Function.onTableUpdated (table.js:408:11)
    at eval (EventBus.js:102:35)
```

**Comment by yogeshmahajan-1903** [comment]
This is working fine.
