### ISSUE TITLE
Full query result being loaded into RAM despite ON_DEMAND_RECORD_COUNT=1000

### ISSUE THREAD

**Issue by mac-chaffee** [pgadmin-org/pgadmin4#5797]
**Describe the bug**

When running something like `select * from bigtable` on a table with many rows, RAM usage of pgAdmin baloons to the size of the table size. This happens on the "query tool", which is supposed to fetch and display only 1000 rows at a time, which makes me think this is a bug.

**To Reproduce**

1. Create a table with lots of rows, say 2GB in size
2. Constantly record RAM usage of the pgAdmin server process with a high frequency
3. In the query tool, run `select * from bigtable`

Observe that RAM usage spiked about 2GB in size while the query was executing, then dropped back down.

**Expected behavior**

RAM usage should remain fairly low, about the size it would take to hold 1000 rows (give or take). You can see this expected behavior by doing the same query in plain `psql` after running `\set FETCH_COUNT 1000`.

**Error message**

If RAM usage was large enough to invoke the OOMKiller, user will see an error like "Error communicating with the pgAdmin server process".

**Desktop (please complete the following information):**
 - OS: Linux
 - Version: 6.17
 - Mode: Desktop
 - Package type: DEB

**Comment by mac-chaffee** [comment]
I'm thinking the issue may be related to the decision not to use server-side cursors here: https://github.com/pgadmin-org/pgadmin4/issues/947

My understanding is that both sync and async queries load the whole result into RAM. The only difference is that async queries don't block when they start doing that. So async queries give you the increased responsiveness, but not reduced RAM usage.

**Comment by mac-chaffee** [comment]
Also wanted to add: while testing I was noticing memory leaking. I'd run a large query then a small query, but the RAM usage of the large query would stick around, even after closing the query tool. But it wasn't super consistent

**Comment by adityatoshniwal** [comment]
Hi @mac-chaffee,
Can please share how did check the RAM usage of the large query? Screenshots will help.

**Comment by mac-chaffee** [comment]
@adityatoshniwal I ran `top -p $(pgrep -f pgAdmin4.py) -d 0.2` to measure RAM usage on Linux. On macOS, ActivityMonitor can be used if you configure a faster refresh rate (I think). Not sure about Windows

**Comment by mac-chaffee** [comment]
If running pgAdmin in the official container, just `top -d 0.2` will work. 

I also think I know why I saw memory-leaky issues. Without server-side cursors, every time you run a query, the full result is loaded into RAM, just in the background. This is controlled by [StartRunningQuery](https://github.com/pgadmin-org/pgadmin4/blob/master/web/pgadmin/tools/sqleditor/utils/start_running_query.py). But since the transaction object is designed to out-live the request cycle, running a large query means you have a large transaction objects still occupying RAM even if the user has closed the query tool. So server-side cursors should fix that issue as well.

(Running a different query after running a large query does seem to free up the RAM usage of the large query, so I take back what I said earlier. I only see memory leak when closing the query tool.)

**Comment by adityatoshniwal** [comment]
@mac-chaffee From what I can see, server side cursors are already used. The RAM usage must be because of UI storing the rows. Need to dig more.

**Comment by mac-chaffee** [comment]
I tried just setting `server_cursor=True` and got this error:

```
2023-02-08 15:32:50,920: ERROR    pgadmin:    asynchronous connections cannot produce named cursors                                                                               
Traceback (most recent call last):                                                                                                                                                
  File "/pgadmin4/pgadmin/utils/driver/psycopg2/connection.py", line 694, in __cursor                                                                                             
    cur = self.conn.cursor(                                                                                                                                                       
psycopg2.ProgrammingError: asynchronous connections cannot produce named cursors                                                                                                  
2023-02-08 15:32:50,937: ERROR    pgadmin:    Failed to create cursor for psycopg2 connection with error message for the server#1:omop_covid:                                     
asynchronous connections cannot produce named cursors                                                                                                                             
2023-02-08 15:32:50,938: ERROR    pgadmin:    'NoneType' object has no attribute 'execute'                                                                                        
Traceback (most recent call last):                                                                                                                                                
  File "/venv/lib/python3.10/site-packages/flask/app.py", line 1517, in full_dispatch_request                                                                                     
    rv = self.dispatch_request()                                                                                                                                                  
  File "/venv/lib/python3.10/site-packages/flask/app.py", line 1503, in dispatch_request                                                                                          
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)                                                                                                  
  File "/venv/lib/python3.10/site-packages/flask_login/utils.py", line 290, in decorated_view                                                                                     
    return current_app.ensure_sync(func)(*args, **kwargs)                                                                                                                         
  File "/pgadmin4/pgadmin/tools/sqleditor/__init__.py", line 831, in start_query_tool                                                                                             
    return StartRunningQuery(blueprint, current_app.logger).execute(                                                                                                              
  File "/pgadmin4/pgadmin/tools/sqleditor/utils/start_running_query.py", line 88, in execute                                                                                      
    result, status = self.__execute_query(                                                                                                                                        
  File "/pgadmin4/pgadmin/tools/sqleditor/utils/start_running_query.py", line 139, in __execute_query                                                                             
    status, result = conn.execute_async(sql)                                                                                                                                      
  File "/pgadmin4/pgadmin/utils/driver/psycopg2/connection.py", line 1086, in execute_async                                                                                       
    cur.execute(query, params)                                                                                                                                                    
AttributeError: 'NoneType' object has no attribute 'execute'
```

Seems you can't mix async queries and server-side cursors together

**Comment by pravesh-sharma** [comment]
Found below issue during testing:

1. pagination button is enabled and when we move to next page we can not got back to previous
2. If we click on commit or rollback button empty result grid is shown it should be moved to message tab as on the case of normal execution

https://github.com/user-attachments/assets/4a953057-4a5d-4281-bc0d-b3fc105f36f0

**Comment by khushboovashi** [comment]
> Found below issue during testing:
> 
> 1. pagination button is enabled and when we move to next page we can not got back to previous

Fixed and raised PR.
> 3. If we click on commit or rollback button empty result grid is shown it should be moved to message tab as on the case of normal execution> 
>  Screen.Recording.2025-07-17.at.3.48.58.PM.mov

**Comment by pravesh-sharma** [comment]
Working fine. Tested on latest snapshot build.
