### ISSUE TITLE
Database migration of release 6.20 fails

### ISSUE THREAD

**Issue by sberlin** [pgadmin-org/pgadmin4#5870]
**_Please note that security bugs or issues should be reported to security@pgadmin.org._**

**Describe the bug**

Database migration of release 6.20 fails with the error message `sqlalchemy.exc.NoSuchTableError: user_old`, preventing PGAdmin to start.

**To Reproduce**

1. Run a prior version (4.30 in our case) in Kubernetes as a stateful set
2. Change the PGAdmin image from dpage/pgadmin4:4 to dpage/pgadmin4:6
3. Pod crashes and restarts
4. Logs show below message

**Expected behavior**

Upgrade runs smoothly

**Actual behavior**
with parameters 
```
PGADMIN_DEFAULT_EMAIL: pgadmin@example.org
PGADMIN_LISTEN_PORT: "5050"
```
```
/pgadmin4 $ /entrypoint.sh
sudo: The "no new privileges" flag is set, which prevents sudo from running as root.
sudo: If sudo is running in a container, you may need to adjust the container configuration to disable the flag.
[2023-02-16 14:59:01 +0000] [27] [INFO] Starting gunicorn 20.1.0
[2023-02-16 14:59:01 +0000] [27] [INFO] Listening at: http://[::]:5050 (27)
[2023-02-16 14:59:01 +0000] [27] [INFO] Using worker: gthread
[2023-02-16 14:59:01 +0000] [34] [INFO] Booting worker with pid: 34
2023-02-16 14:59:08,938: ERROR  pgadmin:        Database migration failed
2023-02-16 14:59:08,943: ERROR  pgadmin:        Traceback (most recent call last):
  File "/pgadmin4/pgadmin/__init__.py", line 390, in upgrade_db
    db_upgrade(app)
  File "/pgadmin4/pgadmin/setup/db_upgrade.py", line 25, in db_upgrade
    flask_migrate.upgrade(migration_folder)
  File "/venv/lib/python3.10/site-packages/flask_migrate/__init__.py", line 111, in wrapped
    f(*args, **kwargs)
  File "/venv/lib/python3.10/site-packages/flask_migrate/__init__.py", line 200, in upgrade
    command.upgrade(config, revision, sql=sql, tag=tag)
  File "/venv/lib/python3.10/site-packages/alembic/command.py", line 378, in upgrade
    script.run_env()
  File "/venv/lib/python3.10/site-packages/alembic/script/base.py", line 569, in run_env
    util.load_python_file(self.dir, "env.py")
  File "/venv/lib/python3.10/site-packages/alembic/util/pyfiles.py", line 94, in load_python_file
    module = load_module_py(module_id, path)
  File "/venv/lib/python3.10/site-packages/alembic/util/pyfiles.py", line 110, in load_module_py
    spec.loader.exec_module(module)  # type: ignore
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/pgadmin4/pgadmin/setup/../../migrations/env.py", line 95, in <module>
    run_migrations_online()
  File "/pgadmin4/pgadmin/setup/../../migrations/env.py", line 87, in run_migrations_online
    context.run_migrations()
  File "<string>", line 8, in run_migrations
  File "/venv/lib/python3.10/site-packages/alembic/runtime/environment.py", line 867, in run_migrations
    self.get_context().run_migrations(**kw)
  File "/venv/lib/python3.10/site-packages/alembic/runtime/migration.py", line 624, in run_migrations
    step.migration_fn(**kw)
  File "/pgadmin4/migrations/versions/f656e56dfdc8_.py", line 92, in upgrade
    migrate_connection_params('server')
  File "/pgadmin4/migrations/versions/f656e56dfdc8_.py", line 37, in migrate_connection_params
    meta.reflect(only=(table_name,))
  File "/venv/lib/python3.10/site-packages/sqlalchemy/sql/schema.py", line 4901, in reflect
    Table(name, self, **reflect_opts)
  File "<string>", line 2, in __new__
  File "/venv/lib/python3.10/site-packages/sqlalchemy/util/deprecations.py", line 375, in warned
    return fn(*args, **kwargs)
  File "/venv/lib/python3.10/site-packages/sqlalchemy/sql/schema.py", line 618, in __new__
    with util.safe_reraise():
  File "/venv/lib/python3.10/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/venv/lib/python3.10/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/venv/lib/python3.10/site-packages/sqlalchemy/sql/schema.py", line 614, in __new__
    table._init(name, metadata, *args, **kw)
  File "/venv/lib/python3.10/site-packages/sqlalchemy/sql/schema.py", line 689, in _init
    self._autoload(
  File "/venv/lib/python3.10/site-packages/sqlalchemy/sql/schema.py", line 724, in _autoload
    conn_insp.reflect_table(
  File "/venv/lib/python3.10/site-packages/sqlalchemy/engine/reflection.py", line 795, in reflect_table
    self._reflect_fk(
  File "/venv/lib/python3.10/site-packages/sqlalchemy/engine/reflection.py", line 992, in _reflect_fk
    sa_schema.Table(
  File "<string>", line 2, in __new__
  File "/venv/lib/python3.10/site-packages/sqlalchemy/util/deprecations.py", line 375, in warned
    return fn(*args, **kwargs)
  File "/venv/lib/python3.10/site-packages/sqlalchemy/sql/schema.py", line 618, in __new__
    with util.safe_reraise():
  File "/venv/lib/python3.10/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/venv/lib/python3.10/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/venv/lib/python3.10/site-packages/sqlalchemy/sql/schema.py", line 614, in __new__
    table._init(name, metadata, *args, **kw)
  File "/venv/lib/python3.10/site-packages/sqlalchemy/sql/schema.py", line 689, in _init
    self._autoload(
  File "/venv/lib/python3.10/site-packages/sqlalchemy/sql/schema.py", line 724, in _autoload
    conn_insp.reflect_table(
  File "/venv/lib/python3.10/site-packages/sqlalchemy/engine/reflection.py", line 789, in reflect_table
    raise exc.NoSuchTableError(table_name)
sqlalchemy.exc.NoSuchTableError: user_old

2023-02-16 14:59:08,944: ERROR  pgadmin:        Exception in database migration.
NOTE: Configuring authentication for SERVER mode.

Enter the email address and password to use for the initial pgAdmin user account:

Email address: ^C[2023-02-16 14:59:22 +0000] [27] [INFO] Handling signal: int
[2023-02-16 14:59:22 +0000] [34] [INFO] Worker exiting (pid: 34)
[2023-02-16 14:59:22 +0000] [27] [INFO] Shutting down: Master
```

**Desktop**
 - OS: Kubernetes
 - Version:  1.24.8
 - Mode: Server
 - Package type: Container

**Additional context**

As pointed out by the logs, a migration set from the most recent release is the culprit: https://github.com/pgadmin-org/pgadmin4/blob/REL-6_20/web/migrations/versions/f656e56dfdc8_.py see #4728 

An intermediate upgrade to dpage/pgadmin4:5 works, but upgrading then to 6.20 leads to the same problem.

**Workaround**

Upgrade to release 6.19 instead, which works

**Comment by adityatoshniwal** [comment]
Hi @sberlin,

We're looking into it. Meanwhile, can you please upgrade to 6.19 first and then try for 6.20?

Thanks.

**Comment by akshay-joshi** [comment]
@sberlin 

The major changes that we did in the pgAdmin 4 v6.16 release where we have used alembic calls to create/update/delete database objects. Please refer [here](https://github.com/pgadmin-org/pgadmin4/commit/e17c50d304a5d7b508f79d385fffb08ef4ae5206).

As you are migrating from 4.30 it runs all the migration scripts after 4.30, not sure why it is looking for the 'user_old' table while running the migration for v6.20. Not using the 'user_old' table since v6.16.

I would suggest upgrading to v6.19 and then trying upgrading to 6.20.

**Comment by cpetit-sigma-fr** [comment]
Same problem here migrating from 6.16/6.17 to 6.20...

Why did you close this issue?

**Comment by timbit123** [comment]
The only way I was able to fix it was to redo all the foreign keys that had server_old or user_old

**Comment by akshay-joshi** [comment]
We are able to reproduce the issue when you upgrade directly from v6.2 and below to v6.16 and above then the issue is reproducible. We have fixed the issue and it will be available in the next release v6.21 on coming Thursday.

**Comment by yogeshmahajan-1903** [comment]
This is working fine.

**Comment by sberlin** [comment]
Thank you for the follow up. I'll test it after 6.21 is released.

**Comment by yogeshmahajan-1903** [comment]
You can test this on nightly build from [here](https://hub.docker.com/r/dpage/pgadmin4/tags) -  docker pull dpage/pgadmin4:2023-03-06-1
