### ISSUE TITLE
RuntimeError: Working outside of application context.

### ISSUE THREAD

**Issue by Stars-** [pgadmin-org/pgadmin4#5883]
When trying to install pgAdmin4 from git repository on the latest Arch Linux the application fail to open with `RuntimeError: Working outside of application context`. I have tried multiple versions of python to no avail. Trying to figure out what is going on as I like using this program for managing my databases.

1. Clone repo from Git
2. Run yarn install in runtime
3. Execute `node_modules/nw/nwjs/nw .`
4. Observe error

I expect the application to open but instead I receive this error message:
```
Total spawn time to start the pgAdmin4 server: 0.004 Sec
Traceback (most recent call last):
  File "/home/stars/Git/pgadmin4/web/pgAdmin4.py", line 102, in <module>
    app = create_app()
  File "/home/stars/Git/pgadmin4/web/pgadmin/__init__.py", line 302, in create_app

    app.logger.debug('Available translations: %s' % babel.list_translations())
  File "/usr/lib/python3.10/site-packages/flask_babel/__init__.py", line 188, in list_translations
    for dirname in get_babel().translation_directories:
  File "/usr/lib/python3.10/site-packages/flask_babel/__init__.py", line 44, in get_babel
    if not hasattr(app, 'extensions'):
  File "/usr/lib/python3.10/site-packages/werkzeug/local.py", line 316, in __get__
    obj = instance._get_current_object()
  File "/usr/lib/python3.10/site-packages/werkzeug/local.py", line 513, in _get_current_object
    raise RuntimeError(unbound_message) from None
RuntimeError: Working outside of application context.

This typically means that you attempted to use functionality that needed
the current application. To solve this, set up an application context
with app.app_context(). See the documentation for more information.
```
Configuration:
OS: Arch Linux
Kernel: 6.1.12-arch1-1
Browser: Firefox 110.0
Python Version: 3.9.16

**Comment by Stars-** [comment]
Re-installed python requirements seemed to fix the problem.
