### ISSUE TITLE
CSRF errors behind Nginx Proxy Manager with Oauth2

### ISSUE THREAD

**Issue by rijnhard** [pgadmin-org/pgadmin4#5950]
**Describe the bug**
When Running PgAdmin behind Nginx Proxy Manager and using Auth0 (Generic Oauth) for authentication it sends an incorrect `redirect_uri`. I am also getting incorrect CSRF Errors. 

I can confirm that the Oauth Config does work when not routing to through the reverse proxy.

The proxy is setup for pgadmin to have its own domain, and not run on a subpath.

**To Reproduce**
Run in docker with the following:

`config.py`:
```python
OAUTH2_CONFIG = [
    {
        # The name of the oauth provider, ex: github, google
        'OAUTH2_NAME': 'auth0',
        # The display name, ex: Google
        'OAUTH2_DISPLAY_NAME': 'Auth0',
        # Oauth client id
        'OAUTH2_CLIENT_ID': os.getenv('OAUTH2_CLIENT_ID').strip(),
        # Oauth secret
        'OAUTH2_CLIENT_SECRET': os.getenv('OAUTH2_CLIENT_SECRET').strip(),
        # URL to generate a token,
        # Ex: https://github.com/login/oauth/access_token
        'OAUTH2_TOKEN_URL': 'https://<domain>.eu.auth0.com/oauth/token',
        # URL is used for authentication,
        # Ex: https://github.com/login/oauth/authorize
        'OAUTH2_AUTHORIZATION_URL': 'https://<domain>.eu.auth0.com/authorize',
        # Oauth base url, ex: https://api.github.com/
        'OAUTH2_API_BASE_URL': 'https://<domain>.eu.auth0.com',
        # Name of the Endpoint, ex: user
        'OAUTH2_USERINFO_ENDPOINT': 'https://<domain>.eu.auth0.com/userinfo',
        # OpenID configuration URL
        'OAUTH2_SERVER_METADATA_URL': 'https://<domain>.eu.auth0.com/.well-known/openid-configuration',
        # Oauth scope, ex: 'openid email profile'
        # Note that an 'email' claim is required in the resulting profile
        'OAUTH2_SCOPE': 'openid email profile',
        # Font-awesome icon, ex: fa-github
        'OAUTH2_ICON': 'fa-openid',
        # UI button colour, ex: #0000ff
        'OAUTH2_BUTTON_COLOR': None,
    }
]

AUTHENTICATION_SOURCES = ['oauth2', 'internal']
OAUTH2_AUTO_CREATE_USER = True
```

Docker compose (nothing special here):
```yaml
version: '3.8'

services:
  pgadmin:
    image: dpage/pgadmin4:latest
    ports:
      - "9000:80/tcp"
    hostname: "pgadmin"
    environment:
      - OAUTH2_CLIENT_SECRET=<snip>
      - OAUTH2_CLIENT_ID=<snip>
      - PGADMIN_DEFAULT_EMAIL=<snip>
      - PGADMIN_DEFAULT_PASSWORD=<snip>
      - PGADMIN_CONFIG_ENHANCED_COOKIE_PROTECTION=False # made no difference
      - PGADMIN_CONFIG_PROXY_X_PORT_COUNT=1 # 1 or 0 made no difference
      - PGADMIN_CONFIG_PROXY_X_HOST_COUNT=1 # 1 or 0 made no difference
      - PGADMIN_CONFIG_PROXY_X_PROTO_COUNT=1 # 1 or 0 made no difference
      - PGADMIN_CONFIG_PROXY_X_FOR_COUNT=1 # 1 or 0 made no difference
    volumes:
      - pgadmin-data:/var/lib/pgadmin
      - /etc/localtime:/etc/localtime:ro
      - ./config/pgadmin_config_local.py:/pgadmin4/config_local.py:rw

volumes:
  pgadmin-data:
    name: 'pgadmin-data'
```

Nginx Proxy manager config (tried setting this in the Location and in the Host).
```
proxy_set_header X-Scheme $scheme;
proxy_set_header Host $host;
proxy_set_header X-Real-IP $remote_addr;
proxy_set_header X-Forwarded-Proto https;
proxy_pass_header Set-Cookie;
proxy_redirect off;
```

1. attempt to login

**Expected behavior**

Login should succeed

**Error message**
From Auth0:
```
{
  "date": "2023-03-14T13:31:05.806Z",
  "type": "f",
  "description": "Callback URL mismatch. https://<domain>,<domain>/oauth2/authorize is not in the list of allowed callback URLs",
  "connection_id": "",
  "ip": "196.223.232.71",
  "user_agent": "Chrome 111.0.0 / Linux 0.0.0",
  "details": {
    "body": {},
    "qs": {
      "response_type": "code",
      "client_id": "<snip>",
      "redirect_uri": "https://<domain>,<domain>/oauth2/authorize",
      "scope": "openid email profile",
      "state": "kgGL7JtmmX6e00PTTVX8iSMqYlfawT",
      "nonce": "TPFhWmgRf7AmrupwQXVl"
    },
    "error": {
      "message": "Callback URL mismatch. https://<domain>,<domain>/oauth2/authorize is not in the list of allowed callback URLs",
      "oauthError": "Callback URL mismatch. https://<domain>,<domain>/oauth2/authorize is not in the list of allowed callback URLs. Please go to 'https://manage.auth0.com/#/applications/<snip>/settings' and make sure you are sending the same callback url from your application.",
      "payload": {
        "message": "Callback URL mismatch. https://<domain>,<domain>/oauth2/authorize is not in the list of allowed callback URLs",
        "code": "unauthorized_client",
        "status": 403,
        "name": "CallbackMismatchError",
        "authorized": [
          "https://<domain>/oauth2/authorize"
        ],
        "attempt": "https://<domain>,<domain>/oauth2/authorize",
        "client": {
          "clientID": "<snip>"
        },
        "log_url": "https://manage.auth0.com/#/logs/"
      },
      "type": "callback-url-mismatch"
    },
    "session_id": "oaa0ezJauLijzD-Um0rOxErlE4qWHjGf"
  },
  "hostname": "<snip>.eu.auth0.com",
  "log_id": "90020230314133107835647000000000000001223372037860719265",
  "_id": "90020230314133107835647000000000000001223372037860719265",
  "isMobile": false,
  "id": "90020230314133107835647000000000000001223372037860719265"
}
```
I removed the domain from the above logs.
It's pretty easy to see here that Auth0 expects a single URL for the `redirect_uri` (as per Oauth specification) but pgadmin is sending multiple in a comma-separated list, and neither is quite correct.   
sent: `https://<domain>,<domain>/oauth2/authorize`
expected: `https://<domain>/oauth2/authorize`

**Desktop (please complete the following information):**
 - OS: Jelastic Docker Engine
 - Version: 6.21
 - Mode: Server
 - Browser (if running in server mode): chrome
 - Package type: Container

**Additional Context**
it may be worth noting that before i explicitly logged out, and after I placed the proxy in front of pgadmin, I was having issues after login. with CSRF tokens mismatching.
```
196.223.232.71 - - [14/Mar/2023:15:27:44 +0200] "GET /login?next=%2Fbrowser%2F HTTP/1.1" 200 1548 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36"
2023-03-14 15:27:44,840: ERROR	pgadmin:	400 Bad Request: The CSRF tokens do not match.
Traceback (most recent call last):
  File "/venv/lib/python3.10/site-packages/flask_wtf/csrf.py", line 261, in protect
    validate_csrf(self._get_csrf_token())
  File "/venv/lib/python3.10/site-packages/flask_wtf/csrf.py", line 115, in validate_csrf
    raise ValidationError("The CSRF tokens do not match.")
wtforms.validators.ValidationError: The CSRF tokens do not match.
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/venv/lib/python3.10/site-packages/flask/app.py", line 1515, in full_dispatch_request
    rv = self.preprocess_request()
  File "/venv/lib/python3.10/site-packages/flask/app.py", line 1857, in preprocess_request
    rv = self.ensure_sync(before_func)()
  File "/venv/lib/python3.10/site-packages/flask_wtf/csrf.py", line 229, in csrf_protect
    self.protect()
  File "/venv/lib/python3.10/site-packages/flask_wtf/csrf.py", line 264, in protect
    self._error_response(e.args[0])
  File "/venv/lib/python3.10/site-packages/flask_wtf/csrf.py", line 307, in _error_response
    raise CSRFError(reason)
flask_wtf.csrf.CSRFError: 400 Bad Request: The CSRF tokens do not match.
```

**Comment by rijnhard** [comment]
So changing the following settings allows login to succeed, but I still get a CSRF error. 

Env Vars:
```
PGADMIN_CONFIG_PROXY_X_PORT_COUNT=1
PGADMIN_CONFIG_PROXY_X_HOST_COUNT=0
PGADMIN_CONFIG_PROXY_X_FOR_COUNT=1
PGADMIN_CONFIG_PROXY_X_PROTO_COUNT=1
# undocumented flask config I had to dig for.
PGADMIN_PREFERRED_URL_SCHEME=https
PGADMIN_SERVER_NAME=<domain>
```

and stripping ALL of the nginx config, from NPM, which only leaves the [defaults NPM sets](https://github.com/NginxProxyManager/nginx-proxy-manager/issues/1556#issuecomment-960628795)

**Comment by rijnhard** [comment]
Something else just popped up. 
If another user signs in with Auth0, after I logged in, they end up logging in with MY user. So the cookies are not being set correctly on the server.

**Comment by rijnhard** [comment]
Ok simplified everything. Login now works, but the application still Gives CSRF Errors:

Nginx Proxy Manager Location Config:
```
Location: /
Forward Scheme: HTTP
Forward Port: 9000 (bind)

Advanced Config:
  proxy_set_header   X-Forwarded-Host   $http_host;
```

Full Docker Compose config:
```yaml
version: '3.8'

services:
  pgadmin:
    image: dpage/pgadmin4:latest
    ports:
      - "9000:80/tcp"
    environment:
      - PGADMIN_DISABLE_POSTFIX=True
      - OAUTH2_CLIENT_ID=<snip>
      - OAUTH2_CLIENT_SECRET=<snip>
      - PGADMIN_CONFIG_ENHANCED_COOKIE_PROTECTION=False
      - PGADMIN_CONFIG_PROXY_X_FOR_COUNT=1
      - PGADMIN_CONFIG_PROXY_X_PROTO_COUNT=1
      - PGADMIN_CONFIG_PROXY_X_HOST_COUNT=1
      - PGADMIN_CONFIG_PROXY_X_PORT_COUNT=1
    hostname: "pgadmin"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
      - /etc/localtime:/etc/localtime:ro
      - ./config/pgadmin_config_local.py:/pgadmin4/config_local.py:rw

volumes:
  pgadmin-data:
    name: 'pgadmin-data'
```

Flow:
```
NPM (Public IP, Port 443) on <target> domain
-> Docker Engine (Private IP, Port 9000)
-> PgAdmin Container (port 80)
```

Error:
```
 <source> - - [16/Mar/2023:09:41:12 +0200] "POST /settings/store HTTP/1.1" 400 117 "https://<target>/browser/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36"
2023-03-16 09:41:14,514: ERROR  pgadmin:  400 Bad Request: The CSRF token is invalid.
Traceback (most recent call last):
  File "/venv/lib/python3.10/site-packages/flask_wtf/csrf.py", line 108, in validate_csrf
    token = s.loads(data, max_age=time_limit)
  File "/venv/lib/python3.10/site-packages/itsdangerous/timed.py", line 226, in loads
    raise _t.cast(BadSignature, last_exception)
  File "/venv/lib/python3.10/site-packages/itsdangerous/timed.py", line 210, in loads
    base64d, timestamp = signer.unsign(
  File "/venv/lib/python3.10/site-packages/itsdangerous/timed.py", line 136, in unsign
    raise BadTimeSignature(str(sig_error), payload=value, date_signed=ts_dt)
itsdangerous.exc.BadTimeSignature: Signature b'<snip>' does not match

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/venv/lib/python3.10/site-packages/flask_wtf/csrf.py", line 261, in protect
    validate_csrf(self._get_csrf_token())
  File "/venv/lib/python3.10/site-packages/flask_wtf/csrf.py", line 112, in validate_csrf
    raise ValidationError("The CSRF token is invalid.") from e
wtforms.validators.ValidationError: The CSRF token is invalid.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/venv/lib/python3.10/site-packages/flask/app.py", line 1515, in full_dispatch_request
    rv = self.preprocess_request()
  File "/venv/lib/python3.10/site-packages/flask/app.py", line 1857, in preprocess_request
    rv = self.ensure_sync(before_func)()
  File "/venv/lib/python3.10/site-packages/flask_wtf/csrf.py", line 229, in csrf_protect
    self.protect()
  File "/venv/lib/python3.10/site-packages/flask_wtf/csrf.py", line 264, in protect
    self._error_response(e.args[0])
  File "/venv/lib/python3.10/site-packages/flask_wtf/csrf.py", line 307, in _error_response
    raise CSRFError(reason)
flask_wtf.csrf.CSRFError: 400 Bad Request: The CSRF token is invalid.
<source> - - [16/Mar/2023:09:41:14 +0200] "POST /settings/store HTTP/1.1" 400 117 "https://<target>/browser/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36"
```

**Comment by rijnhard** [comment]
Fixed. 

The problem was "Cache Assets" was enabled for the PgAdmin Host on Nginx Proxy manager. 
Disabling this stopped the CSRF errors and users being logged in same user.
