### ISSUE TITLE
No user can connect to databases after an error that is probably caused by session expiration

### ISSUE THREAD

**Issue by trettstadtnlb** [pgadmin-org/pgadmin4#6120]
**_Please note that security bugs or issues should be reported to security@pgadmin.org._**

**Describe the bug**

After an error that is probably caused by session expiration no user is able to connect to connect to a database anymore until the pod is restarted.

**To Reproduce**

I did not succeed yet in reproducing this bug and it has only happened once since we migrated the user settings database from SQLite to PostgreSQL. In this one case, the following steps were performed:
1. User sets a master password, creates a database connection to our PostgreSQL server and connects to the database.
2. User leaves the browser window with pgadmin open and the session expires
3. User tries to connect to the database and the error shown in the log below occurs
4. After that every user that wants to connect to the database (they all use the same server) gets a loading icon for a few minutes and after that a pop-up with the title "Error" but without any text appears.
5. If the pod is restarted, users are able to connect to the database again.

**Expected behavior**

Session expiration should not affect other users that want to connect to the same server.

**Error message**

```
2023-03-27 16:35:59,619: INFO	pgadmin:	Waiting for a lock.
2023-03-27 16:35:59,619: INFO	pgadmin:	Acquired a lock.
2023-03-27 16:35:59,619: ERROR	pgadmin:	'auth_source_manager'
Traceback (most recent call last):
  File "/venv/lib/python3.10/site-packages/flask/app.py", line 1517, in full_dispatch_request
    rv = self.dispatch_request()
  File "/venv/lib/python3.10/site-packages/flask/app.py", line 1503, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/pgadmin4/pgadmin/authenticate/oauth2.py", line 75, in oauth_logout
    logout_user()
  File "/venv/lib/python3.10/site-packages/flask_security/utils.py", line 206, in logout_user
    _logout_user()
  File "/venv/lib/python3.10/site-packages/flask_login/utils.py", line 230, in logout_user
    user_logged_out.send(current_app._get_current_object(), user=user)
  File "/venv/lib/python3.10/site-packages/blinker/base.py", line 263, in send
    return [(receiver, receiver(sender, **kwargs))
  File "/venv/lib/python3.10/site-packages/blinker/base.py", line 263, in <listcomp>
    return [(receiver, receiver(sender, **kwargs))
  File "/pgadmin4/pgadmin/__init__.py", line 750, in current_user_cleanup
    _driver.gc_own()
  File "/pgadmin4/pgadmin/utils/driver/psycopg2/__init__.py", line 251, in gc_own
    mgr.release()
  File "/pgadmin4/pgadmin/utils/driver/psycopg2/server_manager.py", line 483, in release
    conn.cancel_transaction(conn.conn_id[5:])
  File "/pgadmin4/pgadmin/utils/driver/psycopg2/connection.py", line 1696, in cancel_transaction
    with ConnectionLocker(self.manager.kerberos_conn):
  File "/pgadmin4/pgadmin/utils/locker.py", line 36, in __enter__
    if session['auth_source_manager']['current_source'] == \
KeyError: 'auth_source_manager'
2023-03-28 07:25:33,796: INFO	pgadmin:	Connection Request for server#2
2023-03-28 07:25:33,815: INFO	pgadmin:	Waiting for a lock.
```

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Kubernetes helm chart using the official Docker image
 - Version: 6.20
 - Mode: Server
 - Browser (if running in server mode): Edge
 - Package type: Docker

**Additional context**

We use master passwords and the following configuration for our Docker containers:

```
- env:
        - name: PGADMIN_DEFAULT_EMAIL
          value: pgadmin4(at)pgadmin(dot)org
        - name: PGADMIN_DEFAULT_PASSWORD
          valueFrom:
            secretKeyRef:
              key: adminPassword
              name: pgadmin
        - name: PGADMIN_LISTEN_PORT
          value: "8080"
        - name: OAUTH2_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              key: clientSecret
              name: pgadmin
        - name: PGADMIN_CONFIG_OAUTH2_CONFIG
          value: '[ { ''OAUTH2_NAME'': ''azure'', ''OAUTH2_DISPLAY_NAME'': ''Azure-AD'',
            ''OAUTH2_CLIENT_ID'': 'clientid'', ''OAUTH2_CLIENT_SECRET'':
            ''$(OAUTH2_CLIENT_SECRET)'', ''OAUTH2_TOKEN_URL'': ''https://login.microsoftonline.com/tenant/oauth2/v2.0/token'',
            ''OAUTH2_AUTHORIZATION_URL'': ''https://login.microsoftonline.com/tenant/oauth2/v2.0/authorize'',
            ''OAUTH2_SERVER_METADATA_URL'': ''https://login.microsoftonline.com/tenant/v2.0/.well-known/openid-configuration'',
            ''OAUTH2_API_BASE_URL'': ''https://graph.microsoft.com/v1.0/'', ''OAUTH2_USERINFO_ENDPOINT'':
            ''me'', ''OAUTH2_SCOPE'': ''User.Read openid email profile'', ''OAUTH2_USERNAME_CLAIM'':
            None, ''OAUTH2_ICON'': None, ''OAUTH2_BUTTON_COLOR'': None } ]'
        - name: DB_USER
          value: pgadmin
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              key: databasePassword
              name: pgadmin
        - name: DB_HOST
          value: "1.2.3.4"
        - name: DB_PORT
          value: "5432"
        - name: DB_NAME
          value: pgadmin
        - name: PGADMIN_CONFIG_CONFIG_DATABASE_URI
          value: '''postgresql://$(DB_USER):$(DB_PASSWORD)@$(DB_HOST):$(DB_PORT)/$(DB_NAME)'''
        - name: PGADMIN_CONFIG_ENHANCED_COOKIE_PROTECTION
          value: "False"
        - name: PGADMIN_CONFIG_AUTHENTICATION_SOURCES
          value: '[''oauth2'', ''internal'']'
        - name: PGADMIN_CONFIG_MASTER_PASSWORD
          value: "True"
        - name: PGADMIN_CONFIG_LOG_FILE
          value: '''/var/lib/pgadmin/logs/pgadmin.log'''
        - name: PGADMIN_CONFIG_FILE_LOG_LEVEL
          value: "20"
        - name: PGADMIN_CONFIG_UPGRADE_CHECK_ENABLED
          value: "False"
```

**Comment by Arunamanivannan** [comment]
@yogeshmahajan-1903 @FaharAbbasRizvi Have provided the required screenshot in issue #5567 [here](https://github.com/pgadmin-org/pgadmin4/issues/5567#issuecomment-1514771614) . Thanks.

**Comment by adityatoshniwal** [comment]
This works fine. Tested with Github Oauth2 on Ubuntu 22 with builds - https://www.postgresql.org/ftp/pgadmin/pgadmin4/snapshots/2023-04-26/apt/
