### ISSUE TITLE
Error removing test config database when running Python tests on Windows

### ISSUE THREAD

**Issue by dpage** [pgadmin-org/pgadmin4#6164]
**Describe the bug**

Example from Jenkins. I see the same in a GitHub action:

```
07:18:30 Please check output in file: C:\jenkins\workspace\pgadmin4-windows-x64-qa\web\regression/regression.log
07:18:30 
07:18:32 Exception ignored in atexit callback: functools.partial(<function _cleanup at 0x000001C8AAC73380>, <TestClient <PgAdmin 'pgadmin'>>, None)
07:18:32 Traceback (most recent call last):
07:18:32   File "C:\jenkins\workspace\pgadmin4-windows-x64-qa\web\regression\python_test_utils\test_utils.py", line 999, in _cleanup
07:18:32     remove_db_file()
07:18:32   File "C:\jenkins\workspace\pgadmin4-windows-x64-qa\web\regression\python_test_utils\test_utils.py", line 953, in remove_db_file
07:18:32     os.remove(config.TEST_SQLITE_PATH)
07:18:32 PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'C:\\jenkins\\workspace\\pgadmin4-windows-x64-qa/var/pgadmin4.db'
07:18:40 Finished: SUCCESS
```

**To Reproduce**

Run the Python tests on Windows.

**Expected behavior**

Test database removed, no error message shown.

**Comment by akshay-joshi** [comment]
There is a FORCE option available to drop a database even if other users are connected. v13+

**Comment by akshay-joshi** [comment]
We have added the exception handling to not show the error message for the time being. Will fix the issue whenever we will found the proper solution.

**Comment by khushboovashi** [comment]
We couldn't find the proper solution, but we added exception handling.
