### ISSUE TITLE
Ubuntu 23.04(Lunar Lobster) is out now. You may add it too to other pgadmin4's. Thank you 

### ISSUE THREAD

**Issue by patriicke** [pgadmin-org/pgadmin4#6171]

**Comment by trufanov-nok** [comment]
pgadmin4 has stopped to work after I upgraded my Kubuntu to 23.04.

```
sudo apt purge pgadmin4-*
sudo apt install pgadmin4-desktop
```

then launching pgadmin from GUI results in

```
pgAdmin Runtime Environment
--------------------------------------------------------
Python Path: "/usr/pgadmin4/venv/bin/python3"
Runtime Config File: "/home/username/.config/pgadmin/runtime_config.json"
pgAdmin Config File: "/usr/pgadmin4/web/config.py"
Webapp Path: "/usr/pgadmin4/web/pgAdmin4.py"
pgAdmin Command: "/usr/pgadmin4/venv/bin/python3 -s /usr/pgadmin4/web/pgAdmin4.py"
Environment: 
  - HOME: /home/username
  - LANG: ru_RU.UTF-8
  - LC_ADDRESS: ru_RU.UTF-8
  - LC_IDENTIFICATION: ru_RU.UTF-8
  - LC_MEASUREMENT: ru_RU.UTF-8
  - LC_MONETARY: ru_RU.UTF-8
  - LC_NAME: ru_RU.UTF-8
  - LC_NUMERIC: ru_RU.UTF-8
  - LC_PAPER: ru_RU.UTF-8
  - LC_TELEPHONE: ru_RU.UTF-8
  - LC_TIME: ru_RU.UTF-8
  - LOGNAME: username
  - PATH: /home/username/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
  - SHELL: /bin/bash
  - SYSTEMD_EXEC_PID: 1980
  - USER: username
  - XDG_RUNTIME_DIR: /run/user/1000
  - QT_ACCESSIBILITY: 1
  - QTWEBENGINE_DICTIONARIES_PATH: /usr/share/hunspell-bdic/
  - XDG_DATA_DIRS: /usr/share/plasma:/usr/local/share:/usr/share:/var/lib/snapd/desktop
  - DBUS_SESSION_BUS_ADDRESS: unix:path=/run/user/1000/bus
  - DEBUGINFOD_URLS: https://debuginfod.ubuntu.com
  - DESKTOP_SESSION: plasma
  - DISPLAY: :0
  - GPG_AGENT_INFO: /run/user/1000/gnupg/S.gpg-agent:0:1
  - GTK2_RC_FILES: /etc/gtk-2.0/gtkrc:/home/username/.gtkrc-2.0:/home/username/.config/gtkrc-2.0
  - GTK_RC_FILES: /etc/gtk/gtkrc:/home/username/.gtkrc:/home/username/.config/gtkrc
  - IM_CONFIG_PHASE: 1
  - KDE_APPLICATIONS_AS_SCOPE: 1
  - KDE_FULL_SESSION: true
  - KDE_SESSION_UID: 1000
  - KDE_SESSION_VERSION: 5
  - LANGUAGE: ru:en_US
  - PAM_KWALLET5_LOGIN: /run/user/1000/kwallet5.socket
  - PWD: /home/username
  - QT_AUTO_SCREEN_SCALE_FACTOR: 0
  - SESSION_MANAGER: local/lenovo-g780:@/tmp/.ICE-unix/1952,unix/lenovo-g780:/tmp/.ICE-unix/1952
  - SHLVL: 0
  - SSH_AGENT_PID: 1828
  - SSH_AUTH_SOCK: /tmp/ssh-XXXXXXov8I9w/agent.1714
  - XAUTHORITY: /home/username/.Xauthority
  - XCURSOR_SIZE: 24
  - XCURSOR_THEME: breeze_cursors
  - XDG_CONFIG_DIRS: /home/username/.config/kdedefaults:/etc/xdg/xdg-plasma:/etc/xdg:/usr/share/kubuntu-default-settings/kf5-settings
  - XDG_CURRENT_DESKTOP: KDE
  - XDG_SEAT: seat0
  - XDG_SEAT_PATH: /org/freedesktop/DisplayManager/Seat0
  - XDG_SESSION_CLASS: user
  - XDG_SESSION_DESKTOP: KDE
  - XDG_SESSION_ID: 3
  - XDG_SESSION_PATH: /org/freedesktop/DisplayManager/Session1
  - XDG_SESSION_TYPE: x11
  - XDG_VTNR: 1
  - _: /usr/bin/dbus-update-activation-environment
  - MANAGERPID: 1686
  - INVOCATION_ID: 1904f8438c1240f3812c5e155422ea56
  - JOURNAL_STREAM: 8:31501
  - GDK_BACKEND: x11
  - NO_AT_BRIDGE: 1
  - PGADMIN_INT_PORT: 37011
  - PGADMIN_INT_KEY: 60d876e1-a302-4650-a952-946380ee600f
  - PGADMIN_SERVER_MODE: OFF
--------------------------------------------------------

Total spawn time to start the pgAdmin4 server: 0.008 Sec
Failed to launch pgAdmin4. Error:
Error: spawn /usr/pgadmin4/venv/bin/python3 ENOENT

```

Then
`$ ls -ln /usr/pgadmin4/venv/bin/python3`
says it points to  /usr/bin/python3.10 which doesnt exist
my system has  /usr/bin/python3.11
Unfortunately 
```
sudo rm /usr/pgadmin4/venv/bin/python3
sudo ln -s /usr/bin/python3.11  /usr/pgadmin4/venv/bin/python3
```
leads to

```
$ /usr/pgadmin4/venv/bin/python3 -s /usr/pgadmin4/web/pgAdmin4.py
Traceback (most recent call last):
  File "/usr/pgadmin4/web/pgAdmin4.py", line 47, in <module>
    import config
  File "/usr/pgadmin4/web/config.py", line 25, in <module>
    from pgadmin.utils import env, IS_WIN, fs_short_path
  File "/usr/pgadmin4/web/pgadmin/__init__.py", line 24, in <module>
    from flask import Flask, abort, request, current_app, session, url_for
ModuleNotFoundError: No module named 'flask'

```


while flask is already installed andI can import it in /usr/bin/python3.11 env


could this be fixed?

**Comment by dpage** [comment]
Support for 23.04 has already been added - it will be included with pgAdmin 7.1 onwards.

**Comment by patriicke** [comment]
Then how can I install it on my ubuntu

**Comment by patriicke** [comment]
[image: image.png]

**Comment by patriicke** [comment]
[image: image.png]

**Comment by dpage** [comment]
You have to wait until 7.1 is released, or use one of the snapshot builds at https://www.postgresql.org/ftp/pgadmin/pgadmin4/snapshots/ which may or may not be stable (or may not be there at all if the build failed for some reason).
