### ISSUE TITLE
Forgotten Passwort Reset does not work

### ISSUE THREAD

**Issue by krzndb** [pgadmin-org/pgadmin4#6191]
In the new version 7.0 (install via python) the prozess of resetting your password does not work. The received e-mail with the included link for resetting the password does arrive, but following the link shows an error:
{"success":0,"errormsg":"'Security' object has no attribute 'reset_password_form'","info":"","result":null,"data":null}

The pgadmin log-file show following output:
ERROR  pgadmin:        'Security' object has no attribute 'reset_password_form'
Traceback (most recent call last):
  File "/opt/pgadmin4/lib/python3.8/site-packages/flask/app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "/opt/pgadmin4/lib/python3.8/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/opt/pgadmin4/lib/python3.8/site-packages/flask_security/decorators.py", line 622, in wrapper
    return f(*args, **kwargs)
  File "/opt/pgadmin4/lib/python3.8/site-packages/pgadmin4/pgadmin/browser/__init__.py", line 1083, in reset_password
    form = _security.reset_password_form()
AttributeError: 'Security' object has no attribute 'reset_password_form'

It seems to be a problem with the module flask-security-too-5.1.2. With the last version 6.21 using flask-security-too-4.1.6 this was no issue.

**Comment by pravesh-sharma** [comment]
Issue fixed. Verified on snapshot build https://www.postgresql.org/ftp/pgadmin/pgadmin4/snapshots/2023-04-28/

Env - macOS Ventura (13.3.1) python wheel package
