### ISSUE TITLE
OAuth sign in not working - Missing "jwks_uri" in metadata reloaded

### ISSUE THREAD

**Issue by alphanoob1337** [pgadmin-org/pgadmin4#6194]
I get the same behavior/error message as described for Azure AD in [#5666](https://github.com/pgadmin-org/pgadmin4/issues/5666#issue-1506833881) while using Keycloak as OAuth2 provider for pgadmin4 version 7.0:
```JSON
{"success":0,"errormsg":"Missing \"jwks_uri\" in metadata","info":"","result":null,"data":null}
```

I provide the `OAUTH2_METADATA_URL` in the pgadmin4 config:
```python
OAUTH2_CONFIG = [
  {
    'OAUTH2_NAME': 'keycloak-master',
    'OAUTH2_DISPLAY_NAME': 'Keycloak master',
    'OAUTH2_CLIENT_ID': 'pgadmin4',
    'OAUTH2_CLIENT_SECRET': '***',
    'OAUTH2_TOKEN_URL': 'https://***/realms/master/protocol/openid-connect/token',
    'OAUTH2_AUTHORIZATION_URL': 'https://***/realms/master/protocol/openid-connect/auth',
    'OAUTH2_METADATA_URL': 'https://***/realms/master/.well-known/openid-configuration',
    'OAUTH2_API_BASE_URL': 'https://***/realms/master/',
    'OAUTH2_USERINFO_ENDPOINT': 'https://***/realms/master/protocol/openid-connect/userinfo',
    'OAUTH2_SCOPE': 'openid email profile',
    'OAUTH2_USERNAME_CLAIM': 'preferred_username',
    'OAUTH2_BUTTON_COLOR': None,
  }
]
```

The exact same setup works fine for pgadmin4 verion 6.14. Here is the relevant part of the logs (using pgadmin4 version 7.0 of course):
```
2023-04-26 22:55:04,972: ERROR  pgadmin:        Missing "jwks_uri" in metadata
Traceback (most recent call last):
  File "/venv/lib/python3.10/site-packages/flask/app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "/venv/lib/python3.10/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/pgadmin4/pgadmin/authenticate/oauth2.py", line 55, in oauth_authorize
    status, msg = auth_obj.login()
  File "/pgadmin4/pgadmin/authenticate/__init__.py", line 296, in login
    status, msg = self.source.login(self.form)
  File "/pgadmin4/pgadmin/authenticate/oauth2.py", line 123, in login
    profile = self.get_user_profile()
  File "/pgadmin4/pgadmin/authenticate/oauth2.py", line 167, in get_user_profile
    self.oauth2_current_client].authorize_access_token()
  File "/venv/lib/python3.10/site-packages/authlib/integrations/flask_client/apps.py", line 105, in authorize_access_token
    userinfo = self.parse_id_token(token, nonce=state_data['nonce'], claims_options=claims_options)
  File "/venv/lib/python3.10/site-packages/authlib/integrations/base_client/sync_openid.py", line 66, in parse_id_token
    claims = _jwt.decode(
  File "/venv/lib/python3.10/site-packages/authlib/jose/rfc7519/jwt.py", line 96, in decode
    data = self._jws.deserialize_compact(s, load_key, decode_payload)
  File "/venv/lib/python3.10/site-packages/authlib/jose/rfc7515/jws.py", line 101, in deserialize_compact
    algorithm, key = self._prepare_algorithm_key(jws_header, payload, key)
  File "/venv/lib/python3.10/site-packages/authlib/jose/rfc7515/jws.py", line 254, in _prepare_algorithm_key
    key = key(header, payload)
  File "/venv/lib/python3.10/site-packages/authlib/integrations/base_client/sync_openid.py", line 38, in load_key
    jwk_set = JsonWebKey.import_key_set(self.fetch_jwk_set())
  File "/venv/lib/python3.10/site-packages/authlib/integrations/base_client/sync_openid.py", line 14, in fetch_jwk_set
    raise RuntimeError('Missing "jwks_uri" in metadata')
RuntimeError: Missing "jwks_uri" in metadata
```

**Additional info to reproduce the issue**

The metadata provided under `https://***/realms/master/.well-known/openid-configuration` provides a value for `jwks_uri`:
```JSON
{
  "issuer": "https://***/realms/master",
  "authorization_endpoint": "https://***/realms/master/protocol/openid-connect/auth",
  "token_endpoint": "https://***/realms/master/protocol/openid-connect/token",
  "introspection_endpoint": "https://***/realms/master/protocol/openid-connect/token/introspect",
  "userinfo_endpoint": "https://***/realms/master/protocol/openid-connect/userinfo",
  "end_session_endpoint": "https://***/realms/master/protocol/openid-connect/logout",
  "frontchannel_logout_session_supported": true,
  "frontchannel_logout_supported": true,
  "jwks_uri": "https://***/realms/master/protocol/openid-connect/certs",
  "check_session_iframe": "https://***/realms/master/protocol/openid-connect/login-status-iframe.html",
  "grant_types_supported": [
    "authorization_code",
    "implicit",
    "refresh_token",
    "password",
    "client_credentials",
    "urn:ietf:params:oauth:grant-type:device_code",
    "urn:openid:params:grant-type:ciba"
  ],
  "acr_values_supported": [
    "0",
    "1"
  ],
  "response_types_supported": [
    "code",
    "none",
    "id_token",
    "token",
    "id_token token",
    "code id_token",
    "code token",
    "code id_token token"
  ],
  "subject_types_supported": [
    "public",
    "pairwise"
  ],
  "id_token_signing_alg_values_supported": [
    "PS384",
    "ES384",
    "RS384",
    "HS256",
    "HS512",
    "ES256",
    "RS256",
    "HS384",
    "ES512",
    "PS256",
    "PS512",
    "RS512"
  ],
  "id_token_encryption_alg_values_supported": [
    "RSA-OAEP",
    "RSA-OAEP-256",
    "RSA1_5"
  ],
  "id_token_encryption_enc_values_supported": [
    "A256GCM",
    "A192GCM",
    "A128GCM",
    "A128CBC-HS256",
    "A192CBC-HS384",
    "A256CBC-HS512"
  ],
  "userinfo_signing_alg_values_supported": [
    "PS384",
    "ES384",
    "RS384",
    "HS256",
    "HS512",
    "ES256",
    "RS256",
    "HS384",
    "ES512",
    "PS256",
    "PS512",
    "RS512",
    "none"
  ],
  "userinfo_encryption_alg_values_supported": [
    "RSA-OAEP",
    "RSA-OAEP-256",
    "RSA1_5"
  ],
  "userinfo_encryption_enc_values_supported": [
    "A256GCM",
    "A192GCM",
    "A128GCM",
    "A128CBC-HS256",
    "A192CBC-HS384",
    "A256CBC-HS512"
  ],
  "request_object_signing_alg_values_supported": [
    "PS384",
    "ES384",
    "RS384",
    "HS256",
    "HS512",
    "ES256",
    "RS256",
    "HS384",
    "ES512",
    "PS256",
    "PS512",
    "RS512",
    "none"
  ],
  "request_object_encryption_alg_values_supported": [
    "RSA-OAEP",
    "RSA-OAEP-256",
    "RSA1_5"
  ],
  "request_object_encryption_enc_values_supported": [
    "A256GCM",
    "A192GCM",
    "A128GCM",
    "A128CBC-HS256",
    "A192CBC-HS384",
    "A256CBC-HS512"
  ],
  "response_modes_supported": [
    "query",
    "fragment",
    "form_post",
    "query.jwt",
    "fragment.jwt",
    "form_post.jwt",
    "jwt"
  ],
  "registration_endpoint": "https://***/realms/master/clients-registrations/openid-connect",
  "token_endpoint_auth_methods_supported": [
    "private_key_jwt",
    "client_secret_basic",
    "client_secret_post",
    "tls_client_auth",
    "client_secret_jwt"
  ],
  "token_endpoint_auth_signing_alg_values_supported": [
    "PS384",
    "ES384",
    "RS384",
    "HS256",
    "HS512",
    "ES256",
    "RS256",
    "HS384",
    "ES512",
    "PS256",
    "PS512",
    "RS512"
  ],
  "introspection_endpoint_auth_methods_supported": [
    "private_key_jwt",
    "client_secret_basic",
    "client_secret_post",
    "tls_client_auth",
    "client_secret_jwt"
  ],
  "introspection_endpoint_auth_signing_alg_values_supported": [
    "PS384",
    "ES384",
    "RS384",
    "HS256",
    "HS512",
    "ES256",
    "RS256",
    "HS384",
    "ES512",
    "PS256",
    "PS512",
    "RS512"
  ],
  "authorization_signing_alg_values_supported": [
    "PS384",
    "ES384",
    "RS384",
    "HS256",
    "HS512",
    "ES256",
    "RS256",
    "HS384",
    "ES512",
    "PS256",
    "PS512",
    "RS512"
  ],
  "authorization_encryption_alg_values_supported": [
    "RSA-OAEP",
    "RSA-OAEP-256",
    "RSA1_5"
  ],
  "authorization_encryption_enc_values_supported": [
    "A256GCM",
    "A192GCM",
    "A128GCM",
    "A128CBC-HS256",
    "A192CBC-HS384",
    "A256CBC-HS512"
  ],
  "claims_supported": [
    "aud",
    "sub",
    "iss",
    "auth_time",
    "name",
    "given_name",
    "family_name",
    "preferred_username",
    "email",
    "acr"
  ],
  "claim_types_supported": [
    "normal"
  ],
  "claims_parameter_supported": true,
  "scopes_supported": [
    "openid",
    "web-origins",
    "email",
    "address",
    "offline_access",
    "phone",
    "microprofile-jwt",
    "acr",
    "profile",
    "roles"
  ],
  "request_parameter_supported": true,
  "request_uri_parameter_supported": true,
  "require_request_uri_registration": true,
  "code_challenge_methods_supported": [
    "plain",
    "S256"
  ],
  "tls_client_certificate_bound_access_tokens": true,
  "revocation_endpoint": "https://***/realms/master/protocol/openid-connect/revoke",
  "revocation_endpoint_auth_methods_supported": [
    "private_key_jwt",
    "client_secret_basic",
    "client_secret_post",
    "tls_client_auth",
    "client_secret_jwt"
  ],
  "revocation_endpoint_auth_signing_alg_values_supported": [
    "PS384",
    "ES384",
    "RS384",
    "HS256",
    "HS512",
    "ES256",
    "RS256",
    "HS384",
    "ES512",
    "PS256",
    "PS512",
    "RS512"
  ],
  "backchannel_logout_supported": true,
  "backchannel_logout_session_supported": true,
  "device_authorization_endpoint": "https://***/realms/master/protocol/openid-connect/auth/device",
  "backchannel_token_delivery_modes_supported": [
    "poll",
    "ping"
  ],
  "backchannel_authentication_endpoint": "https://***/realms/master/protocol/openid-connect/ext/ciba/auth",
  "backchannel_authentication_request_signing_alg_values_supported": [
    "PS384",
    "ES384",
    "RS384",
    "ES256",
    "RS256",
    "ES512",
    "PS256",
    "PS512",
    "RS512"
  ],
  "require_pushed_authorization_requests": false,
  "pushed_authorization_request_endpoint": "https://***/realms/master/protocol/openid-connect/ext/par/request",
  "mtls_endpoint_aliases": {
    "token_endpoint": "https://***/realms/master/protocol/openid-connect/token",
    "revocation_endpoint": "https://***/realms/master/protocol/openid-connect/revoke",
    "introspection_endpoint": "https://***/realms/master/protocol/openid-connect/token/introspect",
    "device_authorization_endpoint": "https://***/realms/master/protocol/openid-connect/auth/device",
    "registration_endpoint": "https://***/realms/master/clients-registrations/openid-connect",
    "userinfo_endpoint": "https://***/realms/master/protocol/openid-connect/userinfo",
    "pushed_authorization_request_endpoint": "https://***/realms/master/protocol/openid-connect/ext/par/request",
    "backchannel_authentication_endpoint": "https://***/realms/master/protocol/openid-connect/ext/ciba/auth"
  }
}

**Comment by yogeshmahajan-1903** [comment]
@alphanoob1337 ,

Please rename parameter 'OAUTH2_METADATA_URL' to 'OAUTH2_**SERVER**_METADATA_URL' in Oatuh2 config & restart the pgAdmin 4.

**Comment by alphanoob1337** [comment]
> @alphanoob1337 ,
> 
> Please rename parameter 'OAUTH2_METADATA_URL' to 'OAUTH2_**SERVER**_METADATA_URL' in Oatuh2 config & restart the pgAdmin 4.

This is very embarrassing. Sorry for asking. Now it works perfectly with Version 7.0!

**Comment by yogeshmahajan-1903** [comment]
Great!. As issue is resolved closing the issue.
