### ISSUE TITLE
[sqlite3.OperationalError] database is locked

### ISSUE THREAD

**Issue by ramank775** [pgadmin-org/pgadmin4#6197]
**_Please note that security bugs or issues should be reported to security@pgadmin.org._**

**Describe the bug**
We are running pgadmin4 in server mode on container. After sometimes it start becoming unresponsive.

**Expected behavior**
- It should work

**Error message**
```
2023-04-27 06:27:43,833: ERROR	pgadmin:	(raised as a result of Query-invoked autoflush; consider using a session.no_autoflush block if this flush is occurring prematurely)
(sqlite3.OperationalError) database is locked
[SQL: UPDATE server SET username=?, password=?, save_password=? WHERE server.id = ?]
[parameters: ('xxxxxxx', None, 0, 1)]
(Background on this error at: https://sqlalche.me/e/20/e3q8)
Traceback (most recent call last):
  File "/venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1964, in _exec_single_context
    self.dialect.do_execute(
  File "/venv/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 748, in do_execute
    cursor.execute(statement, parameters)
sqlite3.OperationalError: database is locked

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/venv/lib/python3.10/site-packages/flask/app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "/venv/lib/python3.10/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/venv/lib/python3.10/site-packages/flask/views.py", line 107, in view
    return current_app.ensure_sync(self.dispatch_request)(**kwargs)
  File "/pgadmin4/pgadmin/browser/utils.py", line 311, in dispatch_request
    return method(*args, **kwargs)
  File "/pgadmin4/pgadmin/browser/server_groups/servers/__init__.py", line 1350, in connect
    user = User.query.filter_by(id=current_user.id).first()
  File "/venv/lib/python3.10/site-packages/sqlalchemy/orm/query.py", line 2752, in first
    return self.limit(1)._iter().first()  # type: ignore
  File "/venv/lib/python3.10/site-packages/sqlalchemy/orm/query.py", line 2855, in _iter
    result: Union[ScalarResult[_T], Result[_T]] = self.session.execute(
  File "/venv/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 2229, in execute
    return self._execute_internal(
  File "/venv/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 2103, in _execute_internal
    ) = compile_state_cls.orm_pre_session_exec(
  File "/venv/lib/python3.10/site-packages/sqlalchemy/orm/context.py", line 460, in orm_pre_session_exec
    session._autoflush()
  File "/venv/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 2906, in _autoflush
    raise e.with_traceback(sys.exc_info()[2])
  File "/venv/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 2895, in _autoflush
    self.flush()
  File "/venv/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 4155, in flush
    self._flush(objects)
  File "/venv/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 4291, in _flush
    with util.safe_reraise():
  File "/venv/lib/python3.10/site-packages/sqlalchemy/util/langhelpers.py", line 147, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "/venv/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 4252, in _flush
    flush_context.execute()
  File "/venv/lib/python3.10/site-packages/sqlalchemy/orm/unitofwork.py", line 467, in execute
    rec.execute(self)
  File "/venv/lib/python3.10/site-packages/sqlalchemy/orm/unitofwork.py", line 644, in execute
    util.preloaded.orm_persistence.save_obj(
  File "/venv/lib/python3.10/site-packages/sqlalchemy/orm/persistence.py", line 85, in save_obj
    _emit_update_statements(
  File "/venv/lib/python3.10/site-packages/sqlalchemy/orm/persistence.py", line 890, in _emit_update_statements
    c = connection.execute(
  File "/venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1414, in execute
    return meth(
  File "/venv/lib/python3.10/site-packages/sqlalchemy/sql/elements.py", line 486, in _execute_on_connection
    return connection._execute_clauseelement(
  File "/venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1638, in _execute_clauseelement
    ret = self._execute_context(
  File "/venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1842, in _execute_context
    return self._exec_single_context(
  File "/venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1983, in _exec_single_context
    self._handle_dbapi_exception(
  File "/venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 2326, in _handle_dbapi_exception
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
  File "/venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1964, in _exec_single_context
    self.dialect.do_execute(
  File "/venv/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 748, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (raised as a result of Query-invoked autoflush; consider using a session.no_autoflush block if this flush is occurring prematurely)
(sqlite3.OperationalError) database is locked
[SQL: UPDATE server SET username=?, password=?, save_password=? WHERE server.id = ?]
[parameters: ('xxxxx', None, 0, 1)]
(Background on this error at: https://sqlalche.me/e/20/e3q8)
::ffff:172.21.0.1 - - [27/Apr/2023:06:27:43 +0000] "POST /browser/server/connect/2/1 HTTP/1.0" 500 433 "https://example.com/pgadmin4/browser/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/112.0.0.0 Safari/537.36"
```

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [Ubuntu]
 - Version: [20]
 - Mode: [Server]
 - Browser (if running in server mode): [chrome]
 - Package type: [Container]

**Additional context**
We start using the container since 6.20 and keep updating the docker container version.
This problem starts from last 3 version.

**Comment by akshay-joshi** [comment]
Hi @ramank775 

Can you please test the issue on the latest pgadmin v7.0?

**Comment by ramank775** [comment]
Hi @akshay-joshi 
The issue persist in latest version as well (7.0). We are currently running the latest version only.

**Comment by ramank775** [comment]
On debugging further. They seems to be like a pattern. 
We are using google oauth2 to login into the pgadmin4 portal. 
If we have open query editor and user try to logout. 
User redirected to an error page instead of login page with this json response
```
{"success": 0, "errormsg": "'auth_source_manager'", "info": "", "result": null, "data": null}
```

On logs we have this
```
2023-04-28 15:42:34,135: ERROR	pgadmin:	'auth_source_manager'
Traceback (most recent call last):
  File "/venv/lib/python3.10/site-packages/flask/app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "/venv/lib/python3.10/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/pgadmin4/pgadmin/authenticate/oauth2.py", line 75, in oauth_logout
    logout_user()
  File "/venv/lib/python3.10/site-packages/flask_security/utils.py", line 208, in logout_user
    _logout_user()
  File "/venv/lib/python3.10/site-packages/flask_login/utils.py", line 230, in logout_user
    user_logged_out.send(current_app._get_current_object(), user=user)
  File "/venv/lib/python3.10/site-packages/blinker/base.py", line 263, in send
    return [(receiver, receiver(sender, **kwargs))
  File "/venv/lib/python3.10/site-packages/blinker/base.py", line 263, in <listcomp>
    return [(receiver, receiver(sender, **kwargs))
  File "/pgadmin4/pgadmin/__init__.py", line 747, in current_user_cleanup
    _driver.gc_own()
  File "/pgadmin4/pgadmin/utils/driver/psycopg3/__init__.py", line 274, in gc_own
    mgr.release()
  File "/pgadmin4/pgadmin/utils/driver/psycopg3/server_manager.py", line 485, in release
    conn.cancel_transaction(conn.conn_id[5:])
  File "/pgadmin4/pgadmin/utils/driver/psycopg3/connection.py", line 1549, in cancel_transaction
    with ConnectionLocker(self.manager.kerberos_conn):
  File "/pgadmin4/pgadmin/utils/locker.py", line 36, in __enter__
    if session['auth_source_manager']['current_source'] == \
KeyError: 'auth_source_manager'
2023-04-28 15:42:34,138: ERROR	pgadmin:	400 Bad Request: The CSRF session token is missing.
Traceback (most recent call last):
  File "/venv/lib/python3.10/site-packages/flask_wtf/csrf.py", line 261, in protect
    validate_csrf(self._get_csrf_token())
  File "/venv/lib/python3.10/site-packages/flask_wtf/csrf.py", line 103, in validate_csrf
    raise ValidationError("The CSRF session token is missing.")
wtforms.validators.ValidationError: The CSRF session token is missing.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/venv/lib/python3.10/site-packages/flask/app.py", line 1821, in full_dispatch_request
    rv = self.preprocess_request()
  File "/venv/lib/python3.10/site-packages/flask/app.py", line 2312, in preprocess_request
    rv = self.ensure_sync(before_func)()
  File "/venv/lib/python3.10/site-packages/flask_wtf/csrf.py", line 229, in csrf_protect
    self.protect()
  File "/venv/lib/python3.10/site-packages/flask_wtf/csrf.py", line 264, in protect
    self._error_response(e.args[0])
  File "/venv/lib/python3.10/site-packages/flask_wtf/csrf.py", line 307, in _error_response
    raise CSRFError(reason)
flask_wtf.csrf.CSRFError: 400 Bad Request: The CSRF session token is missing.
::ffff:172.18.0.1 - - [28/Apr/2023:15:42:34 +0000] "GET /oauth2/logout?next=/pgadmin4/browser/ HTTP/1.0" 500 84 "https://example.com/pgadmin4/browser/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/112.0.0.0 Safari/537.36"
::ffff:172.18.0.1 - - [28/Apr/2023:15:42:34 +0000] "GET /sqleditor/status/2377137 HTTP/1.0" 400 125 "https://example.com/pgadmin4/sqleditor/panel/2377137?is_query_tool=true&sgid=2&sid=1&did=16402&database_name=pidge-1" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/112.0.0.0 Safari/537.36"
2023-04-28 15:42:34,177: ERROR	pgadmin:	400 Bad Request: The CSRF session token is missing.
Traceback (most recent call last):
  File "/venv/lib/python3.10/site-packages/flask_wtf/csrf.py", line 261, in protect
    validate_csrf(self._get_csrf_token())
  File "/venv/lib/python3.10/site-packages/flask_wtf/csrf.py", line 103, in validate_csrf
    raise ValidationError("The CSRF session token is missing.")
wtforms.validators.ValidationError: The CSRF session token is missing.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/venv/lib/python3.10/site-packages/flask/app.py", line 1821, in full_dispatch_request
    rv = self.preprocess_request()
  File "/venv/lib/python3.10/site-packages/flask/app.py", line 2312, in preprocess_request
    rv = self.ensure_sync(before_func)()
  File "/venv/lib/python3.10/site-packages/flask_wtf/csrf.py", line 229, in csrf_protect
    self.protect()
  File "/venv/lib/python3.10/site-packages/flask_wtf/csrf.py", line 264, in protect
    self._error_response(e.args[0])
  File "/venv/lib/python3.10/site-packages/flask_wtf/csrf.py", line 307, in _error_response
    raise CSRFError(reason)
flask_wtf.csrf.CSRFError: 400 Bad Request: The CSRF session token is missing.
::ffff:172.18.0.1 - - [28/Apr/2023:15:42:34 +0000] "DELETE /sqleditor/close/2377137 HTTP/1.0" 400 125 "https://example.com/pgadmin4/sqleditor/panel/2377137?is_query_tool=true&sgid=2&sid=1&did=16402&database_name=pidge-1" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/112.0.0.0 Safari/537.36"
::ffff:172.18.0.1 - - [28/Apr/2023:15:42:54 +0000] "GET /sqleditor/status/1030266 HTTP/1.0" 503 100 "https://example.com/pgadmin4/sqleditor/panel/1030266?is_query_tool=true&sgid=2&sid=1&did=16402&database_name=pidge-1" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/112.0.0.0 Safari/537.36"
::ffff:172.18.0.1 - - [28/Apr/2023:15:42:54 +0000] "POST /misc/heartbeat/log HTTP/1.0" 200 91 "https://example.com/pgadmin4/browser/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/112.0.0.0 Safari/537.36"
::ffff:172.18.0.1 - - [28/Apr/2023:15:42:55 +0000] "POST /misc/cleanup HTTP/1.0" 200 0 "https://example.com/pgadmin4/browser/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/112.0.0.0 Safari/537.36"
```
On relogin to portal this api ```pgadmin4/browser/sever_group/children/<int>``` stuck on loading and finally result in Timeout

**Comment by ramank775** [comment]
Ahh my bad it seems in in release v7.0 we don't have this check of `if 'auth_source_manager' in session` but it just got added recently in https://github.com/pgadmin-org/pgadmin4/issues/6120
https://github.com/pgadmin-org/pgadmin4/blob/6ab102fcbcdd8e1e12ce0aafa86d24a39f3b824b/web/pgadmin/utils/locker.py#L30-L41

It seems like this is fixed @akshay-joshi  on this issue https://github.com/pgadmin-org/pgadmin4/issues/6120.

**Comment by adityatoshniwal** [comment]
Hi @ramank775,
Thank you for debugging. Please try with v7.1 planned to be released this week and let us know.

**Comment by adityatoshniwal** [comment]
HI @ramank775 ,

pgAdmin v7.1 is released. Can you please confirm if the issue is fixed?

Thanks.

**Comment by ramank775** [comment]
Hi @adityatoshniwal 
I have tried v7.1 release. Can confirm this issue is fixed.

Marking this issue as closed.
