### ISSUE TITLE
pgadmin4 version 7.3 shows error after login

### ISSUE THREAD

**Issue by thesumeetkale** [pgadmin-org/pgadmin4#6477]
**Please note that security bugs or issues should be reported to [security@pgadmin.org](mailto:security@pgadmin.org).**

**Describe the bug**

pgadmin4 version 7.3 shows error after login

**To Reproduce**

1. python -m pip install pgadmin4==7.3

**Expected behavior**

It should allow login without any errors.

**Error message**

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 1517, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 1503, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/var/www/engg_tools/environments/.env/lib/python3.10/site-packages/pgadmin4/pgadmin/authenticate/__init__.py", line 101, in login
    return _login()
  File "/var/www/engg_tools/environments/.env/lib/python3.10/site-packages/pgadmin4/pgadmin/authenticate/__init__.py", line 108, in _login
    form = _security.forms.get('login_form').cls(request.form)
AttributeError: 'Security' object has no attribute 'forms'

**Screenshots**

![image](https://github.com/pgadmin-org/pgadmin4/assets/51416370/1f389751-85b5-4445-88e0-dc4c348969d7)

**Server**
 - OS: Ubuntu Jammy Jellyfish
 - Version: 22.04
 - Mode: Server
 - Browser: firefox
 - Package type: Python

**Additional context**

Used this link to install pgadmin4: [https://www.digitalocean.com/community/tutorials/how-to-install-and-configure-pgadmin-4-in-server-mode-on-ubuntu-22-04](url)

**Comment by adityatoshniwal** [comment]
Hi @thesumeetkale,
Can you please share the output for `pip freeze`? We suspect that your python env has some older packages which are conflicting. You may also try with new virtual env.

**Comment by yogeshmahajan-1903** [comment]
No response from author, hence closing ticket.
