### ISSUE TITLE
lost connection v 7.4

### ISSUE THREAD

**Issue by Bear4** [pgadmin-org/pgadmin4#6524]
**Describe the bug**
Can't connect with tables, only in one, two tables can connect and the other tables - get messages: 
`Connection to pgAdmin server has been lost.`

After restart - the same, one, two tables can reached or anyone because: 
`Connection to pgAdmin server has been lost.`

And can't connect with other server because: 
`Connection to pgAdmin server has been lost.`

In PgAmin 4 v 7.3 - there wasn't such problems.

Any idea how to fix this problem with connection?

**Screenshots**
![pgadmin_err-1](https://github.com/pgadmin-org/pgadmin4/assets/8928341/08fb39e1-16f8-4c22-9053-6516870038dd)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version: 7.4
 - Desktop
 - Package type: -
 - Path: C:\Program Files\pgAdmin 4\v7\runtime;

**Additional context**

Total spawn time to start the pgAdmin4 server: 0.02 Sec
2023-07-03 08:35:17,639: WARNING	werkzeug:	WebSocket transport not available. Install simple-websocket for improved performance.

2023-07-03 08:35:17,639: WARNING	werkzeug:	Werkzeug appears to be used in a production deployment. Consider switching to a production web server instead.

 * Serving Flask app 'pgadmin'
 * Debug mode: off
Application Server URL: http://127.0.0.1:5050/?key=123a9de8-c0c9-4e08-8cb1-6198ac7c16f5
2023-07-03 08:35:43,276: ERROR	pgadmin:	exception: access violation reading 0x00000000298C00D0
Traceback (most recent call last):
  File "C:\Program Files\pgAdmin 4\v7\python\lib\site-packages\flask\app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Program Files\pgAdmin 4\v7\python\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "C:\Program Files\pgAdmin 4\v7\python\lib\site-packages\flask_login\utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "C:\Program Files\pgAdmin 4\v7\web\pgadmin\tools\sqleditor\__init__.py", line 893, in poll
    status, result = conn.poll(
  File "C:\Program Files\pgAdmin 4\v7\web\pgadmin\utils\driver\psycopg3\connection.py", line 1458, in poll
    if self.conn and self.conn.pgconn.is_busy():
  File "C:\Program Files\pgAdmin 4\v7\python\lib\site-packages\psycopg\pq\pq_ctypes.py", line 530, in is_busy
    return impl.PQisBusy(self._pgconn_ptr)
OSError: exception: access violation reading 0x00000000298C00D0

2023-07-03 08:35:43,277: ERROR	pgadmin:	exception: access violation reading 0x00000000298C00D0
**Traceback (most recent call last):**
  File "C:\Program Files\pgAdmin 4\v7\python\lib\site-packages\flask\app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Program Files\pgAdmin 4\v7\python\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "C:\Program Files\pgAdmin 4\v7\python\lib\site-packages\flask_login\utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "C:\Program Files\pgAdmin 4\v7\web\pgadmin\tools\sqleditor\__init__.py", line 835, in start_query_tool
    return StartRunningQuery(blueprint, current_app.logger).execute(
  File "C:\Program Files\pgAdmin 4\v7\web\pgadmin\tools\sqleditor\utils\start_running_query.py", line 88, in execute
    result, status = self.__execute_query(
  File "C:\Program Files\pgAdmin 4\v7\web\pgadmin\tools\sqleditor\utils\start_running_query.py", line 139, in __execute_query
    status, result = conn.execute_async(sql)
  File "C:\Program Files\pgAdmin 4\v7\web\pgadmin\utils\driver\psycopg3\connection.py", line 1067, in execute_async
    cur.execute(query, params)
  File "C:\Program Files\pgAdmin 4\v7\web\pgadmin\utils\driver\psycopg3\cursor.py", line 281, in execute
    return asyncio.run(self._execute(query, params))
  File "asyncio\runners.py", line 44, in run
  File "asyncio\base_events.py", line 649, in run_until_complete
  File "C:\Program Files\pgAdmin 4\v7\web\pgadmin\utils\driver\psycopg3\cursor.py", line 292, in _execute
    return await _async_cursor.execute(self, query, params)
  File "C:\Program Files\pgAdmin 4\v7\python\lib\site-packages\psycopg\cursor_async.py", line 90, in execute
    await self._conn.wait(
  File "C:\Program Files\pgAdmin 4\v7\python\lib\site-packages\psycopg\connection_async.py", line 349, in wait
    return await waiting.wait_async(gen, self.pgconn.socket)
  File "C:\Program Files\pgAdmin 4\v7\python\lib\site-packages\psycopg\waiting.py", line 142, in wait_async
    s = gen.send(ready)
  File "C:\Program Files\pgAdmin 4\v7\python\lib\site-packages\psycopg\cursor.py", line 196, in _execute_gen
    results = yield from self._maybe_prepare_gen(
  File "C:\Program Files\pgAdmin 4\v7\python\lib\site-packages\psycopg\cursor.py", line 321, in _maybe_prepare_gen
    results = yield from execute(self._pgconn)
  File "C:\Program Files\pgAdmin 4\v7\python\lib\site-packages\psycopg\generators.py", line 100, in _execute
    rv = yield from _fetch_many(pgconn)
  File "C:\Program Files\pgAdmin 4\v7\python\lib\site-packages\psycopg\generators.py", line 139, in _fetch_many
    res = yield from _fetch(pgconn)
  File "C:\Program Files\pgAdmin 4\v7\python\lib\site-packages\psycopg\generators.py", line 172, in _fetch
    if not pgconn.is_busy():
  File "C:\Program Files\pgAdmin 4\v7\python\lib\site-packages\psycopg\pq\pq_ctypes.py", line 530, in is_busy
    return impl.PQisBusy(self._pgconn_ptr)
OSError: exception: access violation reading 0x00000000298C00D0

2023-07-03 08:35:57,058: ERROR	pgadmin:	Failed to execute query (execute_async) for the server #2 - CONN:3379968(Query-id: 6761466):
Error Message:ERROR:  sending query failed: got message type "

**Comment by danielabbatt** [comment]
I also get this a lot today, had to downgrade to 7.3, problem went away

**Comment by Bear4** [comment]
Yes, comeback to version  7.3 solved the problem.

**Comment by edwinteisman** [comment]
Version 7.4 is no longer workable, all my queries return "Connection has been lost"
I am reverting to version 7.3

**Comment by khushboovashi** [comment]
@edwinteisman, @Bear4, @danielabbatt,

Try the latest snapshot build at https://www.postgresql.org/ftp/pgadmin/pgadmin4/snapshots/2023-07-13/
This issue has been fixed.

**Comment by danielabbatt** [comment]
Any idea when the next 7.5 build will be out or a patch to 7.4 as many of my colleagues are also suffering the same problem and don't want to download the snapshots

**Comment by akshay-joshi** [comment]
> Any idea when the next 7.5 build will be out or a patch to 7.4 as many of my colleagues are also suffering the same problem and don't want to download the snapshots

v7.5 will be releasing on 27th July

**Comment by ugurlu2001** [comment]
Same issue on my PgAdmin 7.4 too, error message is : 

Connection to pgAdmin server has been lostConnection to pgAdmin server has been lost

I downgrade to 7.3 and problem solved.

**Comment by vnicolici** [comment]
> v7.5 will be releasing on 27th July

After downgrading to 7.3 pgAdmin keeps badgering me to install 7.4. If the 7.5 release can't be expedited, perhaps versions that have serious issues, like 7.4, shouldn't generate update notifications once it becomes clear they should be skipped? This will also save users that didn't yet update to 7.4 from experiencing the issue, having to look for a solution, and having to downgrade to 7.3 to fix it.

**Comment by FaharAbbasRizvi** [comment]
This is fixed in the latest snapshot build:
https://www.postgresql.org/ftp/pgadmin/pgadmin4/snapshots/2023-07-19/

**Comment by huangzhuohua** [comment]
> Same issue on my PgAdmin 7.4 too, error message is :
> 
> Connection to pgAdmin server has been lostConnection to pgAdmin server has been lost
> 
> I downgrade to 7.3 and problem solved.

yes , i also get the same problem in pgadmin4-7.4-x64.exe

**Comment by packole** [comment]
same issues on my PgAdmin 7.5 today -> it try with 7.3 again...

**Comment by edwinteisman** [comment]
Just for information: for me PgAdmin version 7.5 is working well.

**Comment by ad-trauke** [comment]
Same on 7.5
First attempt after upgrade to 7.6 and error again...

**Comment by RiftWa1ker** [comment]
Same issue on 7.6 too

**Comment by Jezternz** [comment]
Jump to 2024 - upgrading from 7.4 to 8.2 ffixed this for me :)
