### ISSUE TITLE
Query tool, After conneting to the server

### ISSUE THREAD

**Issue by gumuliokas** [pgadmin-org/pgadmin4#6539]
I am connecting to the server successfullty, then open query tool to enter simple query:
and got error message below:
![image](https://github.com/pgadmin-org/pgadmin4/assets/15009387/9627f593-03d2-488a-b8ad-16b08591cc7d)

windows 10, pgadmin 4, v7.

2023-07-07 11:58:23,312: ERROR	pgadmin:	'NoneType' object has no attribute 'pgconn'
Traceback (most recent call last):
  File "C:\Program Files\pgAdmin 4\v7\python\lib\site-packages\flask\app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Program Files\pgAdmin 4\v7\python\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "C:\Program Files\pgAdmin 4\v7\python\lib\site-packages\flask_login\utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "C:\Program Files\pgAdmin 4\v7\web\pgadmin\tools\sqleditor\__init__.py", line 893, in poll
    status, result = conn.poll(
  File "C:\Program Files\pgAdmin 4\v7\web\pgadmin\utils\driver\psycopg3\connection.py", line 1478, in poll
    if not self.conn.pgconn.is_busy():
AttributeError: 'NoneType' object has no attribute 'pgconn'
2023-07-07 12:00:15,628: WARNING	werkzeug:	WebSocket transport not available. Install simple-websocket for improved performance.
2023-07-07 12:00:15,628: WARNING	werkzeug:	Werkzeug appears to be used in a production deployment. Consider switching to a production web server instead.

**Comment by FaharAbbasRizvi** [comment]
@gumuliokas 

I am not able to reproduce the issue on the latest snapshot build, can you please try on the latest snapshot build :https://www.postgresql.org/ftp/pgadmin/pgadmin4/snapshots/2023-07-07/

**Comment by metropolisStar** [comment]
The same issue seen yesterday on my v7.4 desktop mode on Windows 11 Pro.

**Comment by FaharAbbasRizvi** [comment]
@metropolisStar  we have fixed this issue,  Kindly try the steps on testing builds:
https://www.postgresql.org/ftp/pgadmin/pgadmin4/snapshots/2023-07-07/

**Comment by gumuliokas** [comment]
Seems working fine. No issues found.  Thank you.

**Comment by yogeshmahajan-1903** [comment]
As per user comments, it working on nightly builds. It will be available in next release.
