### ISSUE TITLE
Query tool: The message  "list index out of range" is displayed if the user drops the table if the query running on the view data

### ISSUE THREAD

**Issue by FaharAbbasRizvi** [pgadmin-org/pgadmin4#6564]
The message  "list index out of range" is displayed if the user drops the table if the query running on the view data

**To Reproduce**

1. create database huge 
2. Create the following query:

create table temp1 (a numeric);
insert into temp1 (a) select random()*100 from generate_series(0,100000000)

3. Table created in 3 minutes' time
4.  Select the table and go into view data
5. Open another query tool Window
6.  execute this query DROP TABLE IF EXISTS public.temp1
7. Now list index out of range is displayed

**Expected behavior**

A pop-up message should be displayed if any query is running in view data and the user wants to drop the query from another query tool.

**Error message**

*list index out of range*

**Screenshots**

<img width="1302" alt="Screen Shot 2023-07-13 at 4 09 23 PM" src="https://github.com/pgadmin-org/pgadmin4/assets/43006122/b1b143bd-df1a-4466-9e5a-505210dacd7e">
<img width="1321" alt="Screen Shot 2023-07-13 at 4 09 41 PM" src="https://github.com/pgadmin-org/pgadmin4/assets/43006122/c3606250-80d1-4dd3-aba2-74ee38003f3d">

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10, OSX monterey]
 - Version: [e.g. 7.4]

**Comment by adityatoshniwal** [comment]
Error:
```

Traceback (most recent call last):
  File "/Users/adityatoshniwal/venv/pypg312/lib/python3.12/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/adityatoshniwal/venv/pypg312/lib/python3.12/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/adityatoshniwal/venv/pypg312/lib/python3.12/site-packages/flask_login/utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/adityatoshniwal/projects/pgadmin4/web/pgadmin/tools/sqleditor/__init__.py", line 1039, in poll
    if hasattr(trans_obj, 'obj_id') and trans_obj.can_edit():
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/adityatoshniwal/projects/pgadmin4/web/pgadmin/tools/sqleditor/command.py", line 703, in get_columns_types
    return get_columns_types(conn=conn,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/adityatoshniwal/projects/pgadmin4/web/pgadmin/tools/sqleditor/utils/get_column_types.py", line 57, in get_columns_types
    rset['rows'][key]['not_null']
    ~~~~~~~~~~~~^^^^^
IndexError: list index out of range
```

**Comment by anilsahoo20** [comment]
Tested and verified on snapshot build: https://www.postgresql.org/ftp/pgadmin/pgadmin4/snapshots/2025-05-14/
Package: arm64
Environment: macOs Sonoma 14.7.1
