### ISSUE TITLE
Cant to backup database: str expected, not bytes

### ISSUE THREAD

**Issue by kofesutra** [pgadmin-org/pgadmin4#6575]
When I try to backup my database i`ve got an error "str expected, not bytes"
But two weeks ago backing up was sucsessful
I hope for your help, thank you

[<a href="https://ibb.co/YPQnfsR"><img src="https://i.ibb.co/S5yYVCs/2023-07-16-12-42-32.png" alt="2023-07-16-12-42-32" border="0"></a>](url)

Log:
`2023-07-16 12:38:46,228: ERROR	pgadmin:	str expected, not bytes
Traceback (most recent call last):
  File "/usr/pgadmin4/web/pgadmin/tools/backup/__init__.py", line 405, in create_backup_objects_job
    manager.export_password_env(p.id)
  File "/usr/pgadmin4/web/pgadmin/utils/driver/psycopg3/server_manager.py", line 545, in export_password_env
    os.environ[str(env)] = password
  File "/usr/lib/python3.10/os.py", line 684, in __setitem__
    value = self.encodevalue(value)
  File "/usr/lib/python3.10/os.py", line 756, in encode
    raise TypeError("str expected, not %s" % type(value).__name__)
TypeError: str expected, not bytes`

**Comment by akshay-joshi** [comment]
@kofesutra 

Can you test on the snapshot build (https://www.postgresql.org/ftp/pgadmin/pgadmin4/snapshots/2023-07-19/) as we are not able to reproduce the issue?

**Comment by anilsahoo20** [comment]
Hi @kofesutra,
Please try on pgAdmin 4 v7.5.

**Comment by akshay-joshi** [comment]
No response from the author, hence closing it.
