### ISSUE TITLE
Cant see data output when executing a query

### ISSUE THREAD

**Issue by Emil760** [pgadmin-org/pgadmin4#6587]
pgadmin version: 7.4

OS: Windos 10 Home

Steps to introduce: just take some simple query and try to execute it, so you would not see any data in Data Output tab

LOGS from AppData=>Roaming=>pgadmin=>pgadmin4.log file

2023-07-19 13:07:38,621: ERROR	pgadmin:	<asyncio.locks.Lock object at 0x0000029804728550 [unlocked, waiters:1]> is bound to a different event loop
Traceback (most recent call last):
  File "C:\Program Files\pgAdmin 4\v7\web\pgadmin\utils\driver\psycopg3\cursor.py", line 281, in execute
    return asyncio.run(self._execute(query, params))
  File "asyncio\runners.py", line 44, in run
  File "asyncio\base_events.py", line 649, in run_until_complete
  File "C:\Program Files\pgAdmin 4\v7\web\pgadmin\utils\driver\psycopg3\cursor.py", line 292, in _execute
    return await _async_cursor.execute(self, query, params)
  File "C:\Program Files\pgAdmin 4\v7\python\lib\site-packages\psycopg\cursor_async.py", line 89, in execute
    async with self._conn.lock:
  File "asyncio\locks.py", line 14, in __aenter__
  File "asyncio\locks.py", line 106, in acquire
  File "asyncio\mixins.py", line 30, in _get_loop
RuntimeError: <asyncio.locks.Lock object at 0x0000029804728550 [unlocked, waiters:1]> is bound to a different event loop

**Comment by knutole** [comment]
I came here to report the same. 

- The row count is displaying data, but there is nothing in the Output box. 
- This is new after I updated to 7.4 (from 6-something). 
![Screenshot 2023-07-19 at 11 58 01](https://github.com/pgadmin-org/pgadmin4/assets/2197944/26b9a17e-503a-4b6b-95a0-fc3081178c4b)

**Comment by khushboovashi** [comment]
Hi @Emil760,

This issue has been fixed; please check it on the snapshot build. Ref: https://www.postgresql.org/ftp/pgadmin/pgadmin4/snapshots/2023-07-19/

I am closing this issue.

**Comment by knutole** [comment]
Thanks. That snapshot does not work for me, though. M2 mac, downloaded ARM version, nothing happens when I open the app. But that will surely be fixed soon. I've reverted to previous version for now, all good. 

Thanks for all your great work! 👍 💯

**Comment by Emil760** [comment]
Thanks a lot. in 7.5 release everything works fine )
