### ISSUE TITLE
pgAdmin 4 stuck on "Loading pgAdmin 4 v7.4..." page and nothing happens

### ISSUE THREAD

**Issue by masamy00** [pgadmin-org/pgadmin4#6607]
**_Please note that security bugs or issues should be reported to security@pgadmin.org._**

**Describe the bug**
pgAdmin 4 stuck on "Loading pgAdmin 4 v7.4..." page and nothing happens

**To Reproduce**

2. Click on 'pgAdmin 4'
3. See the error

**Expected behavior**

the server should run

**Error message**

If possible, include the full, unedited text of any error messages displayed.

**Screenshots**
![image](https://github.com/pgadmin-org/pgadmin4/assets/134070206/5246579e-4d7f-4d01-ae03-59ce0dac76be)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Version: v7.4
 - Mode: Desktop

**Comment by marcopio72** [comment]
I have the same problem on Windows 10.

this is the end  of my log file:

`------------------------------------------
Total time taken to ping pgAdmin4 server: 9.078 Sec
------------------------------------------
Total launch time of pgAdmin4: 10.108 Sec
------------------------------------------
Application Server URL: http://127.0.0.1:53985/?key=50b7db01-112a-4bfd-b618-da466900000c
2023-07-24 05:28:15,470: ERROR	pgadmin:	404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
Traceback (most recent call last):
  File "C:\Program Files\PostgreSQL\15\pgAdmin 4\python\lib\site-packages\flask\app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Program Files\PostgreSQL\15\pgAdmin 4\python\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "C:\Program Files\PostgreSQL\15\pgAdmin 4\python\lib\site-packages\flask\app.py", line 713, in <lambda>
    view_func=lambda **kw: self_ref().send_static_file(**kw),  # type: ignore # noqa: B950
  File "C:\Program Files\PostgreSQL\15\pgAdmin 4\python\lib\site-packages\flask\scaffold.py", line 331, in send_static_file
    return send_from_directory(
  File "C:\Program Files\PostgreSQL\15\pgAdmin 4\python\lib\site-packages\flask\helpers.py", line 590, in send_from_directory
    return werkzeug.utils.send_from_directory(  # type: ignore[return-value]
  File "C:\Program Files\PostgreSQL\15\pgAdmin 4\python\lib\site-packages\werkzeug\utils.py", line 587, in send_from_directory
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.

2023-07-24 05:28:15,474: ERROR	pgadmin:	404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
Traceback (most recent call last):
  File "C:\Program Files\PostgreSQL\15\pgAdmin 4\python\lib\site-packages\flask\app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Program Files\PostgreSQL\15\pgAdmin 4\python\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "C:\Program Files\PostgreSQL\15\pgAdmin 4\python\lib\site-packages\flask\app.py", line 713, in <lambda>
    view_func=lambda **kw: self_ref().send_static_file(**kw),  # type: ignore # noqa: B950
  File "C:\Program Files\PostgreSQL\15\pgAdmin 4\python\lib\site-packages\flask\scaffold.py", line 331, in send_static_file
    return send_from_directory(
  File "C:\Program Files\PostgreSQL\15\pgAdmin 4\python\lib\site-packages\flask\helpers.py", line 590, in send_from_directory
    return werkzeug.utils.send_from_directory(  # type: ignore[return-value]
  File "C:\Program Files\PostgreSQL\15\pgAdmin 4\python\lib\site-packages\werkzeug\utils.py", line 587, in send_from_directory
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.

2023-07-24 05:28:15,475: ERROR	pgadmin:	404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
Traceback (most recent call last):
  File "C:\Program Files\PostgreSQL\15\pgAdmin 4\python\lib\site-packages\flask\app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Program Files\PostgreSQL\15\pgAdmin 4\python\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "C:\Program Files\PostgreSQL\15\pgAdmin 4\python\lib\site-packages\flask\app.py", line 713, in <lambda>
    view_func=lambda **kw: self_ref().send_static_file(**kw),  # type: ignore # noqa: B950
  File "C:\Program Files\PostgreSQL\15\pgAdmin 4\python\lib\site-packages\flask\scaffold.py", line 331, in send_static_file
    return send_from_directory(
  File "C:\Program Files\PostgreSQL\15\pgAdmin 4\python\lib\site-packages\flask\helpers.py", line 590, in send_from_directory
    return werkzeug.utils.send_from_directory(  # type: ignore[return-value]
  File "C:\Program Files\PostgreSQL\15\pgAdmin 4\python\lib\site-packages\werkzeug\utils.py", line 587, in send_from_directory
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
2023-07-24 05:28:15,476: ERROR	pgadmin:	404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
Traceback (most recent call last):
  File "C:\Program Files\PostgreSQL\15\pgAdmin 4\python\lib\site-packages\flask\app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Program Files\PostgreSQL\15\pgAdmin 4\python\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "C:\Program Files\PostgreSQL\15\pgAdmin 4\python\lib\site-packages\flask\app.py", line 713, in <lambda>
    view_func=lambda **kw: self_ref().send_static_file(**kw),  # type: ignore # noqa: B950
  File "C:\Program Files\PostgreSQL\15\pgAdmin 4\python\lib\site-packages\flask\scaffold.py", line 331, in send_static_file
    return send_from_directory(
  File "C:\Program Files\PostgreSQL\15\pgAdmin 4\python\lib\site-packages\flask\helpers.py", line 590, in send_from_directory
    return werkzeug.utils.send_from_directory(  # type: ignore[return-value]
  File "C:\Program Files\PostgreSQL\15\pgAdmin 4\python\lib\site-packages\werkzeug\utils.py", line 587, in send_from_directory
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
2023-07-24 05:28:15,484: ERROR	pgadmin:	404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
Traceback (most recent call last):
  File "C:\Program Files\PostgreSQL\15\pgAdmin 4\python\lib\site-packages\flask\app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Program Files\PostgreSQL\15\pgAdmin 4\python\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "C:\Program Files\PostgreSQL\15\pgAdmin 4\python\lib\site-packages\flask\app.py", line 713, in <lambda>
    view_func=lambda **kw: self_ref().send_static_file(**kw),  # type: ignore # noqa: B950
  File "C:\Program Files\PostgreSQL\15\pgAdmin 4\python\lib\site-packages\flask\scaffold.py", line 331, in send_static_file
    return send_from_directory(
  File "C:\Program Files\PostgreSQL\15\pgAdmin 4\python\lib\site-packages\flask\helpers.py", line 590, in send_from_directory
    return werkzeug.utils.send_from_directory(  # type: ignore[return-value]
  File "C:\Program Files\PostgreSQL\15\pgAdmin 4\python\lib\site-packages\werkzeug\utils.py", line 587, in send_from_directory
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
2023-07-24 05:28:15,498: ERROR	pgadmin:	404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
Traceback (most recent call last):
  File "C:\Program Files\PostgreSQL\15\pgAdmin 4\python\lib\site-packages\flask\app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Program Files\PostgreSQL\15\pgAdmin 4\python\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "C:\Program Files\PostgreSQL\15\pgAdmin 4\python\lib\site-packages\flask\app.py", line 713, in <lambda>
    view_func=lambda **kw: self_ref().send_static_file(**kw),  # type: ignore # noqa: B950
  File "C:\Program Files\PostgreSQL\15\pgAdmin 4\python\lib\site-packages\flask\scaffold.py", line 331, in send_static_file
    return send_from_directory(
  File "C:\Program Files\PostgreSQL\15\pgAdmin 4\python\lib\site-packages\flask\helpers.py", line 590, in send_from_directory
    return werkzeug.utils.send_from_directory(  # type: ignore[return-value]
  File "C:\Program Files\PostgreSQL\15\pgAdmin 4\python\lib\site-packages\werkzeug\utils.py", line 587, in send_from_directory
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.

2023-07-24 05:28:15,632: ERROR	pgadmin:	404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
Traceback (most recent call last):
  File "C:\Program Files\PostgreSQL\15\pgAdmin 4\python\lib\site-packages\flask\app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Program Files\PostgreSQL\15\pgAdmin 4\python\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "C:\Program Files\PostgreSQL\15\pgAdmin 4\python\lib\site-packages\flask\app.py", line 713, in <lambda>
    view_func=lambda **kw: self_ref().send_static_file(**kw),  # type: ignore # noqa: B950
  File "C:\Program Files\PostgreSQL\15\pgAdmin 4\python\lib\site-packages\flask\scaffold.py", line 331, in send_static_file
    return send_from_directory(
  File "C:\Program Files\PostgreSQL\15\pgAdmin 4\python\lib\site-packages\flask\helpers.py", line 590, in send_from_directory
    return werkzeug.utils.send_from_directory(  # type: ignore[return-value]
  File "C:\Program Files\PostgreSQL\15\pgAdmin 4\python\lib\site-packages\werkzeug\utils.py", line 587, in send_from_directory
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.

2023-07-24 05:28:15,642: ERROR	pgadmin:	404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
Traceback (most recent call last):
  File "C:\Program Files\PostgreSQL\15\pgAdmin 4\python\lib\site-packages\flask\app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Program Files\PostgreSQL\15\pgAdmin 4\python\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "C:\Program Files\PostgreSQL\15\pgAdmin 4\python\lib\site-packages\flask\app.py", line 713, in <lambda>
    view_func=lambda **kw: self_ref().send_static_file(**kw),  # type: ignore # noqa: B950
  File "C:\Program Files\PostgreSQL\15\pgAdmin 4\python\lib\site-packages\flask\scaffold.py", line 331, in send_static_file
    return send_from_directory(
  File "C:\Program Files\PostgreSQL\15\pgAdmin 4\python\lib\site-packages\flask\helpers.py", line 590, in send_from_directory
    return werkzeug.utils.send_from_directory(  # type: ignore[return-value]
  File "C:\Program Files\PostgreSQL\15\pgAdmin 4\python\lib\site-packages\werkzeug\utils.py", line 587, in send_from_directory
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.

2023-07-24 05:28:15,668: ERROR	pgadmin:	404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
Traceback (most recent call last):
  File "C:\Program Files\PostgreSQL\15\pgAdmin 4\python\lib\site-packages\flask\app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Program Files\PostgreSQL\15\pgAdmin 4\python\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "C:\Program Files\PostgreSQL\15\pgAdmin 4\python\lib\site-packages\flask\app.py", line 713, in <lambda>
    view_func=lambda **kw: self_ref().send_static_file(**kw),  # type: ignore # noqa: B950
  File "C:\Program Files\PostgreSQL\15\pgAdmin 4\python\lib\site-packages\flask\scaffold.py", line 331, in send_static_file
    return send_from_directory(
  File "C:\Program Files\PostgreSQL\15\pgAdmin 4\python\lib\site-packages\flask\helpers.py", line 590, in send_from_directory
    return werkzeug.utils.send_from_directory(  # type: ignore[return-value]
  File "C:\Program Files\PostgreSQL\15\pgAdmin 4\python\lib\site-packages\werkzeug\utils.py", line 587, in send_from_directory
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.

2023-07-24 05:28:15,726: ERROR	pgadmin:	404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
Traceback (most recent call last):
  File "C:\Program Files\PostgreSQL\15\pgAdmin 4\python\lib\site-packages\flask\app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Program Files\PostgreSQL\15\pgAdmin 4\python\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "C:\Program Files\PostgreSQL\15\pgAdmin 4\python\lib\site-packages\flask\app.py", line 713, in <lambda>
    view_func=lambda **kw: self_ref().send_static_file(**kw),  # type: ignore # noqa: B950
  File "C:\Program Files\PostgreSQL\15\pgAdmin 4\python\lib\site-packages\flask\scaffold.py", line 331, in send_static_file
    return send_from_directory(
  File "C:\Program Files\PostgreSQL\15\pgAdmin 4\python\lib\site-packages\flask\helpers.py", line 590, in send_from_directory
    return werkzeug.utils.send_from_directory(  # type: ignore[return-value]
  File "C:\Program Files\PostgreSQL\15\pgAdmin 4\python\lib\site-packages\werkzeug\utils.py", line 587, in send_from_directory
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
2023-07-24 05:28:15,729: ERROR	pgadmin:	404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
Traceback (most recent call last):
  File "C:\Program Files\PostgreSQL\15\pgAdmin 4\python\lib\site-packages\flask\app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Program Files\PostgreSQL\15\pgAdmin 4\python\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "C:\Program Files\PostgreSQL\15\pgAdmin 4\python\lib\site-packages\flask\app.py", line 713, in <lambda>
    view_func=lambda **kw: self_ref().send_static_file(**kw),  # type: ignore # noqa: B950
  File "C:\Program Files\PostgreSQL\15\pgAdmin 4\python\lib\site-packages\flask\scaffold.py", line 331, in send_static_file
    return send_from_directory(
  File "C:\Program Files\PostgreSQL\15\pgAdmin 4\python\lib\site-packages\flask\helpers.py", line 590, in send_from_directory
    return werkzeug.utils.send_from_directory(  # type: ignore[return-value]
  File "C:\Program Files\PostgreSQL\15\pgAdmin 4\python\lib\site-packages\werkzeug\utils.py", line 587, in send_from_directory
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.

2023-07-24 05:28:15,732: ERROR	pgadmin:	404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
Traceback (most recent call last):
  File "C:\Program Files\PostgreSQL\15\pgAdmin 4\python\lib\site-packages\flask\app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Program Files\PostgreSQL\15\pgAdmin 4\python\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "C:\Program Files\PostgreSQL\15\pgAdmin 4\python\lib\site-packages\flask\app.py", line 713, in <lambda>
    view_func=lambda **kw: self_ref().send_static_file(**kw),  # type: ignore # noqa: B950
  File "C:\Program Files\PostgreSQL\15\pgAdmin 4\python\lib\site-packages\flask\scaffold.py", line 331, in send_static_file
    return send_from_directory(
  File "C:\Program Files\PostgreSQL\15\pgAdmin 4\python\lib\site-packages\flask\helpers.py", line 590, in send_from_directory
    return werkzeug.utils.send_from_directory(  # type: ignore[return-value]
  File "C:\Program Files\PostgreSQL\15\pgAdmin 4\python\lib\site-packages\werkzeug\utils.py", line 587, in send_from_directory
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.

--------------[UI log]---------------
{"0":{"requireType":"scripterror","requireModules":["sources/generated/app.bundle"],"originalError":{"isTrusted":true}}}
------------[UI End]----------------
--------------[UI log]---------------
{"0":{"requireType":"scripterror","requireModules":["sources/generated/codemirror"],"originalError":{"isTrusted":true}}}
------------[UI End]----------------
--------------[UI log]---------------
{"0":{"requireType":"scripterror","requireModules":["sources/generated/browser_nodes"],"originalError":{"isTrusted":true}}}
------------[UI End]----------------
`

**Comment by marcopio72** [comment]
The same problem with  v14.8

**Comment by adityatoshniwal** [comment]
Duplicates https://github.com/pgadmin-org/pgadmin4/issues/6580

**Comment by akshay-joshi** [comment]
All, Please uninstall the pgAdmin ship with PostgreSQL installers and try to download it from https://www.pgadmin.org/download/

Duplicate #6580

**Comment by at-akshat-2107** [comment]
I also Faced this Issue Yesterday and Now it is Resolved.

Follow below steps:

1. Install the Postgresql database from this link : https://www.postgresql.org/download/windows/
2. When Exe File Downloaded then you will show like below screen
![explorer_Opy4hM9hxe](https://github.com/pgadmin-org/pgadmin4/assets/116496758/71a35352-ebf4-4735-8c86-75c08c94f97e)
3. Now click on Next Button then,see below Screen
![explorer_qMp8166yB4](https://github.com/pgadmin-org/pgadmin4/assets/116496758/dc4b87ea-1391-4bfb-8e9b-54ee54a7bf12)
4. By default all options are checked, **Now uncheck pgadmin4 options(This is the rootcause of Error.)**
![explorer_BtYNgYWhzC](https://github.com/pgadmin-org/pgadmin4/assets/116496758/53528e13-7ab2-4aff-915e-edb439a4c737)
5. And Now Click on Next -Next -Next Button and then Complete the Installation Process for Windows OS.
Link:https://www.pgadmin.org/download/pgadmin-4-windows/
6. Now install Pgadmin4 IDE from Below Link and you will now not faced Error and IDE will be open and add Password which was created at the time of Installation of Postgresql of above.

![chrome_apNbt94COM](https://github.com/pgadmin-org/pgadmin4/assets/116496758/2915ba48-0dc9-49af-8940-30db4d1af290)

**Comment by rkoktan** [comment]
Same thing on OpenSUSE Tumbleweed VERSION="20230822"

Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/flask/app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/flask/app.py", line 502, in <lambda>
    view_func=lambda **kw: self_ref().send_static_file(**kw),  # type: ignore # noqa: B950
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/flask/scaffold.py", line 318, in send_static_file
    return send_from_directory(
           ^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/flask/helpers.py", line 557, in send_from_directory
    return werkzeug.utils.send_from_directory(  # type: ignore[return-value]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/werkzeug/utils.py", line 574, in send_from_directory
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
2023-08-24 10:19:24,292: ERROR	pgadmin:	404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/flask/app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/flask/app.py", line 502, in <lambda>
    view_func=lambda **kw: self_ref().send_static_file(**kw),  # type: ignore # noqa: B950
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/flask/scaffold.py", line 318, in send_static_file
    return send_from_directory(
           ^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/flask/helpers.py", line 557, in send_from_directory
    return werkzeug.utils.send_from_directory(  # type: ignore[return-value]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/werkzeug/utils.py", line 574, in send_from_directory
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
)   = 0 (Timeout)
