### ISSUE TITLE
Not found after upgrade

### ISSUE THREAD

**Issue by ClodoaldoPinto** [pgadmin-org/pgadmin4#6627]
After upgrading pgadmin from 7.4 to 7.5 in RockLinux I get a "`Not found`" page after login at the url `https://pgadmin.codepoint.net/pgadmin4`
```
2023-07-27 18:19:48,211: ERROR  pgadmin:        404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
Traceback (most recent call last):
  File "/usr/pgadmin4/venv/lib64/python3.9/site-packages/flask/app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/pgadmin4/venv/lib64/python3.9/site-packages/flask/app.py", line 1788, in dispatch_request
    self.raise_routing_exception(req)
  File "/usr/pgadmin4/venv/lib64/python3.9/site-packages/flask/app.py", line 1770, in raise_routing_exception
    raise request.routing_exception  # type: ignore
  File "/usr/pgadmin4/venv/lib64/python3.9/site-packages/flask/ctx.py", line 351, in match_request
    result = self.url_adapter.match(return_rule=True)  # type: ignore
  File "/usr/pgadmin4/venv/lib64/python3.9/site-packages/werkzeug/routing/map.py", line 624, in match
    raise NotFound() from None
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
```

**Comment by yogeshmahajan-1903** [comment]
@ClodoaldoPinto 
Can you please try clearing cache or in private window? 
Note - pgAdmin is not tested/supported on Rock Linux platform.

**Comment by stefanomarty** [comment]
Same error on Debian12. After upgrading to 7.5 the browser after login is redirected to:
<base_url>/pgadmin4

instead of
<base_url>/browser

**Comment by yogeshmahajan-1903** [comment]
@stefanomarty 

Can you please try solution provided in #5454. Meanwhile we are trying fix the solution.

**Comment by stefanomarty** [comment]
> Can you please try solution provided in #5454. Meanwhile we are trying fix the solution.

OK, I changed the `SCRIPT_NAME` value in `/usr/pgadmin4/web/pgAdmin4.wsgi`
```
#os.environ['SCRIPT_NAME'] = '/pgadmin4'
os.environ['SCRIPT_NAME'] = ''

```
and the redirect after authentication is working again (pointing to /browser).

**Comment by yogeshmahajan-1903** [comment]
We have reopened #5454, hence closing this issue.
