### ISSUE TITLE
Keyboard shortcut for query execution should be disabled when query execution is in progress

### ISSUE THREAD

**Issue by yogeshmahajan-1903** [pgadmin-org/pgadmin4#6664]
**_Please note that security bugs or issues should be reported to security@pgadmin.org._**

**Describe the bug**

Keyboard shortcut should be disabled when button is disabled on query tool

**To Reproduce**

1. Go to query tool. Execute long running query and before it completes hit keyboard shortcut to execute query which triggers re-execution of query 

```
2023-08-08 16:37:01,664: ERROR	pgadmin:	<asyncio.locks.Lock object at 0x10e010a60 [unlocked, waiters:1]> is bound to a different event loop
Traceback (most recent call last):
  File "/Users/yogeshmahajan/CodingGround/pgAdmin/DevEnv/Code/pgadmin4/web/pgadmin/utils/driver/psycopg3/cursor.py", line 281, in execute
    return asyncio.run(self._execute(query, params))
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/Users/yogeshmahajan/CodingGround/pgAdmin/DevEnv/Code/pgadmin4/web/pgadmin/utils/driver/psycopg3/cursor.py", line 292, in _execute
    return await _async_cursor.execute(self, query, params)
  File "/Users/yogeshmahajan/CodingGround/pgAdmin/DevEnv/Venv31010/lib/python3.10/site-packages/psycopg/cursor_async.py", line 89, in execute
    async with self._conn.lock:
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/locks.py", line 14, in __aenter__
    await self.acquire()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/locks.py", line 106, in acquire
    fut = self._get_loop().create_future()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/mixins.py", line 30, in _get_loop
    raise RuntimeError(f'{self!r} is bound to a different event loop')


```
And if you run some query again, it will give you incorrect output.

**Expected behavior**

Query tool execute query keyboard shortcut should be disabled while query execution is in progress.

**Error message**

If possible, include the full, unedited text of any error messages displayed.

**Screenshots**

<img width="1788" alt="Screenshot 2023-08-08 at 4 44 26 PM" src="https://github.com/pgadmin-org/pgadmin4/assets/16016019/8471b3bb-98cb-45ca-974f-d9464add8a10">

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10, OSX monterey]
 - Version: [e.g. 6.15]
 - Mode: [e.g Desktop or Server]
 - Browser (if running in server mode): [e.g. chrome, safari]
 - Package type: [e.g. RPM, DEB, Python, Container, etc.]

**Additional context**

**Comment by FaharAbbasRizvi** [comment]
This is fixed in the latest snapshot builds:
https://www.postgresql.org/ftp/pgadmin/pgadmin4/snapshots/2023-08-10/
