### ISSUE TITLE
Add a way to re-login if you type the wrong password

### ISSUE THREAD

**Issue by ccurvey** [pgadmin-org/pgadmin4#6863]
**Describe the solution you'd like**

I think I typed the wrong master password.  There's no way to re-enter it.  Now I'm stuck -- whenever I try to connect to one of my saved servers, the server icon just flashes.  

**Describe alternatives you've considered**

Using pgManage.  (Actually, I have to unless I want to re-add my credentials every time I start pgAdmin4

**Additional context**

**Comment by yogeshmahajan-1903** [comment]
@ccurvey 
Can you please tell pgAdmin 4 version, mode(desktop/server), OS?
Master password pop up should be shown again if incorrect master password is entered.

**Comment by ccurvey** [comment]
> Can you please tell pgAdmin 4 version, mode(desktop/server), OS?

Version  7.7
Application Mode  Desktop
Current User pgadmin4@pgadmin.org
NW.js Version 0.77.0
Browser Chromium 114.0.5735.91
Operating System Linux-6.2.0-34-generic-x86_64-with-glibc2.37
pgAdmin Database File /home/chris/.pgadmin/pgadmin4.db
Log File /home/chris/.pgadmin/pgadmin4.log

>  Master password pop up should be shown again if incorrect master password is entered.

Maybe I did type it in properly.  In any case, the server icon is just flashing and is unresponsive to clicks

**Comment by yogeshmahajan-1903** [comment]
@ccurvey 

Can you please share log file located at /home/chris/.pgadmin/pgadmin4.log?

**Comment by ccurvey** [comment]
Sure.  I just re-started PGAdmin, am getting the same behavior (can't open a registered server), and all that's in today's log is

```
2023-10-18 09:46:09,533: WARNING	werkzeug:	Werkzeug appears to be used in a production deployment. Consider switching to a production web server instead.
```

**Comment by yogeshmahajan-1903** [comment]
@ccurvey 
Can you please record a small video for the error? Also try adding new sever and try connecting to it.

Can you please share server config from About pop up? 

By default, pgAdmin uses OS level secrets to store saved password in desktop mode. We are not expecting master password dialogue, unless user has set DISABLED_LOCAL_PASSWORD_STORAGE=True.

**Comment by ccurvey** [comment]
>  Can you please record a small video for the error? 

I have one in MKV format.   Do you need it in a different format?  (Video is not my strength.)

> Also try adding new sever and try connecting to it.

Tried adding localhost...same reaction

> Can you please share server config from About pop up?  

by "server" I'm guessing you mean "postgres server" (let me know if that's wrong)

Host name:  localhost
Port: 5432
Maintenance Database:  postgres
Username:  chris

I did enter my password and chose "save password"

**Comment by ccurvey** [comment]
this might be interesting...I restarted my machine and re-started pgadmin4, and now I have a few instances of this in the logs:

```
2023-10-20 06:55:46,456: ERROR	pgadmin:	401 Unauthorized: The server could not verify that you are authorized to access the URL requested. You either supplied the wrong credentials (e.g. a bad password), or your browser doesn't understand how to supply the credentials required.
Traceback (most recent call last):
  File "/usr/pgadmin4/venv/lib/python3.11/site-packages/flask/app.py", line 1821, in full_dispatch_request
    rv = self.preprocess_request()
         ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/pgadmin4/venv/lib/python3.11/site-packages/flask/app.py", line 2313, in preprocess_request
    rv = self.ensure_sync(before_func)()
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/pgadmin4/web/pgadmin/__init__.py", line 815, in before_request
    abort(401)
  File "/usr/pgadmin4/venv/lib/python3.11/site-packages/flask/helpers.py", line 310, in abort
    current_app.aborter(code, *args, **kwargs)
  File "/usr/pgadmin4/venv/lib/python3.11/site-packages/werkzeug/exceptions.py", line 864, in __call__
    raise self.mapping[code](*args, **kwargs)
werkzeug.exceptions.Unauthorized: 401 Unauthorized: The server could not verify that you are authorized to access the URL requested. You either supplied the wrong credentials (e.g.  a bad password), or your browser doesn't understand how to supply the credentials required.
```

The strange thing here is that I'm restarting pgadmin4, but I'm **not** being asked for my master password on startup.

**Comment by khushboovashi** [comment]
> > Can you please share server config from About pop up?

Please share the pgAdmin configurations from `Help > About pgAdmin 4`

**Comment by ccurvey** [comment]
sigh.  I had to get this working, so I ended up deleting everything in ~/.pgadmin and starting over.

**Comment by ccurvey** [comment]
And...as soon as I disconnect/reconnect, it's back!

I've attached a screenshot -- it's static, but the circled icon is flashing between the "stack" icon and the "refresh" icon 

![pgadmin-flash](https://github.com/pgadmin-org/pgadmin4/assets/385577/de2bc829-c006-4f0b-95b4-50bc163c19f9)

**Comment by ccurvey** [comment]
If I click on the icon and try to re-open my connection, I get this dialog.  clicking on Continue doesn't seem to do anything.

![pgadmin4-error-dialog](https://github.com/pgadmin-org/pgadmin4/assets/385577/050a0fa2-9894-4378-b343-faf503c78333)

**Comment by pravesh-sharma** [comment]
Hi @ccurvey,

Is it working fine with PSQL CLI?

**Comment by anilsahoo20** [comment]
No response from author, hence closing the issue.
