### ISSUE TITLE
LDAP Login The CSRF session token is missing.

### ISSUE THREAD

**Issue by ChrisJBurns** [pgadmin-org/pgadmin4#6886]
**Describe the bug**

When we login via LDAP credentials, the it gets stuck on loading screen.

**To Reproduce**

1) Configure LDAP
2) Login with LDAP credentials
3) See Loading screen stuck

**Expected behavior**
Expected to login and be able to query postgres db's

**Error message**

```
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/venv/lib/python3.11/site-packages/flask/app.py", line 1821, in full_dispatch_request
    rv = self.preprocess_request()
         ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/venv/lib/python3.11/site-packages/flask/app.py", line 2313, in preprocess_request
    rv = self.ensure_sync(before_func)()
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/venv/lib/python3.11/site-packages/flask_wtf/csrf.py", line 229, in csrf_protect
    self.protect()
  File "/venv/lib/python3.11/site-packages/flask_wtf/csrf.py", line 264, in protect
    self._error_response(e.args[0])
  File "/venv/lib/python3.11/site-packages/flask_wtf/csrf.py", line 307, in _error_response
    raise CSRFError(reason)
flask_wtf.csrf.CSRFError: 400 Bad Request: The CSRF session token is missing.
172.16.92.128 - - [24/Oct/2023:11:53:56 +0000] "GET /sqleditor/status/2100387 HTTP/1.1" 400 125 "https://pgadmin.our.domain/sqleditor/panel/2100387?is_query_tool=false&cmd_type=3&obj_type=table&obj_id=16424&sgid=11&sid=15&did=16384&server_type=pg" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/118.0"
2023-10-24 11:53:56,730: ERROR    pgadmin:    400 Bad Request: The CSRF session token is missing.
Traceback (most recent call last):
  File "/venv/lib/python3.11/site-packages/flask_wtf/csrf.py", line 261, in protect
    validate_csrf(self._get_csrf_token())
  File "/venv/lib/python3.11/site-packages/flask_wtf/csrf.py", line 103, in validate_csrf
    raise ValidationError("The CSRF session token is missing.")
wtforms.validators.ValidationError: The CSRF session token is missing.
```

**Screenshots**

![image](https://github.com/pgadmin-org/pgadmin4/assets/29541485/1bdb0b53-b635-49be-92c7-da53cad2afc0)

**Desktop (please complete the following information):**
 - OS: OSX Sonoma
 - Version: 14.0
 - Mode: Sever
 - Browser Chrome
 - Package type: Docker container

**Additional context**

We deploy via Helm Chart. We had no issues with 7.7. but 7.8 seemed to have broken our LDAP functionality. We can sign in as the admin completely fine and see our users within PGAdmin, but when we login via LDAP we get the continuous loading screen with the CSRF errors in the PGAdmin Container logs.

**Comment by khushboovashi** [comment]
Hi,

Can you try with `docker pull dpage/pgadmin4:snapshot` and check?

**Comment by ChrisJBurns** [comment]
@khushboovashi Yes that seems to work!

**Comment by khushboovashi** [comment]
> @khushboovashi Yes that seems to work!
> 
> I'm assuming this is a fixed issue and will be in the next release?
Yes.

**Comment by yogeshmahajan-1903** [comment]
Duplicate of #6874
