### ISSUE TITLE
pgadmin4 7.8 not starting correctly with install from snapshot wheel file since 2023-10-24 

### ISSUE THREAD

**Issue by malapeyre** [pgadmin-org/pgadmin4#6899]
**_Please note that security bugs or issues should be reported to security@pgadmin.org._**

**Describe the bug**

Hanging on "Loading pgadmin 4 v7.8" page after login

**To Reproduce**

install from snapshot wheel file since 2023-10-24 

3. See the error

**Expected behavior**

Successful start 

**Error message**

If possible, include the full, unedited text of any error messages displayed.

Starting pgAdmin 4. Please navigate to http://127.0.0.1:5050 in your browser.
 * Serving Flask app 'pgadmin'
 * Debug mode: off
local variable 'registry' referenced before assignment
2023-10-28 11:48:37,789: ERROR  pgadmin:        404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
Traceback (most recent call last):
  File "D:\MyProgramFilesD\pgadmin\venv74\lib\site-packages\flask\app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "D:\MyProgramFilesD\pgadmin\venv74\lib\site-packages\flask\app.py", line 1788, in dispatch_request
    self.raise_routing_exception(req)
  File "D:\MyProgramFilesD\pgadmin\venv74\lib\site-packages\flask\app.py", line 1770, in raise_routing_exception
    raise request.routing_exception  # type: ignore
  File "D:\MyProgramFilesD\pgadmin\venv74\lib\site-packages\flask\ctx.py", line 351, in match_request
    result = self.url_adapter.match(return_rule=True)  # type: ignore
  File "D:\MyProgramFilesD\pgadmin\venv74\lib\site-packages\werkzeug\routing\map.py", line 624, in match
    raise NotFound() from None
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version: pgadmin 4 v7.8 whl snapshot since 2023-10-24
 - Mode: Server
 - Browser Microsofyt Edge
 - Package type: whl

**Additional context**

Install v7.8 from wheel file prior to 2023-10-24 works fine

**Comment by malapeyre** [comment]
Solved with cleaning Edge cookies.
Sorry for this false alert :(
