### ISSUE TITLE
servers.json not showing up for OIDC users after enabling OIDC

### ISSUE THREAD

**Issue by lenaxia** [pgadmin-org/pgadmin4#7047]
**_Please note that security bugs or issues should be reported to security@pgadmin.org._**

**Describe the bug**

Prior to enabling OIDC, servers.json was loading properly and would be visible when logged in via local users. After enabling OIDC, logging in with OIDC users the servers.json no longer shows. There is no longer an option to log in with local users after oidc is enabled. It previously was working before enabling OIDC.

**To Reproduce**

1. Enable OIDC
2. Login with OIDC user
3. See no servers

**Expected behavior**

Servers in servers.json should show up in the UI

**Error message**

None, see logs below

**Screenshots**

No option to login with local user after OIDC enabled:
![image](https://github.com/pgadmin-org/pgadmin4/assets/6321838/d476105f-5f9f-469c-961b-d67f330f06a3)

**Desktop (please complete the following information):**
 - OS: k3s 1.2.9, docker.io/dpage/pgadmin4
 - Version: 8.0
 - Mode: Docker
 - Browser (if running in server mode): Any browser
 - Package type: Container

**Additional context**

Environment variables:
```
    Environment:
      PGADMIN_SERVER_JSON_FILE:  /pgadmin4/servers.json
      TZ:                        America/Los_Angeles
```

Logs with debug enabled:

```
2023-12-08 22:20:57,784: INFO   pgadmin:        ########################################################
2023-12-08 22:20:57,785: INFO   pgadmin:        Starting pgAdmin 4 v8.0...
2023-12-08 22:20:57,785: INFO   pgadmin:        ########################################################
2023-12-08 22:20:57,785: DEBUG  pgadmin:        Python syspath: ['/pgadmin4', '/pgadmin4', '/usr/lib/python311.zip', '/usr/lib/python3.11', '/usr/lib/python3.11/lib-dynload', '/venv/lib/python3.11/site-packages', '/usr/lib/python3.11/site-packages']
2023-12-08 22:21:00,473: INFO   pgadmin:        Registering blueprint module: <AboutModule 'about'>
2023-12-08 22:21:00,474: INFO   pgadmin:        Registering blueprint module: <AuthenticateModule 'authenticate'>
2023-12-08 22:21:00,475: INFO   pgadmin:        Registering blueprint module: <BrowserModule 'browser'>
2023-12-08 22:21:01,764: INFO   pgadmin:        Registering blueprint module: <DashboardModule 'dashboard'>
2023-12-08 22:21:01,776: INFO   pgadmin:        Registering blueprint module: <DashboardModule 'dashboard'>
2023-12-08 22:21:01,776: INFO   pgadmin:        Registering blueprint module: <HelpModule 'help'>
2023-12-08 22:21:01,777: INFO   pgadmin:        Registering blueprint module: <MiscModule 'misc'>
2023-12-08 22:21:02,839: INFO   pgadmin:        Registering blueprint module: <PreferencesModule 'preferences'>
2023-12-08 22:21:02,841: INFO   pgadmin:        Registering blueprint module: <PgAdminModule 'redirects'>
2023-12-08 22:21:02,842: INFO   pgadmin:        Registering blueprint module: <SettingsModule 'settings'>
2023-12-08 22:21:02,846: INFO   pgadmin:        Registering blueprint module: <ToolsModule 'tools'>
2023-12-08 22:21:03,715: DEBUG  pgadmin:        Config server mode: True
2023-12-08 22:21:03,715: DEBUG  pgadmin:        Not running under the desktop runtime, port: 5050
NOTE: Configuring authentication for SERVER mode.

pgAdmin 4 - Application Initialisation
======================================

2023-12-08 22:21:13,718: INFO   pgadmin:        ########################################################
2023-12-08 22:21:13,718: INFO   pgadmin:        Starting pgAdmin 4 v8.0...
2023-12-08 22:21:13,718: INFO   pgadmin:        ########################################################
2023-12-08 22:21:13,718: DEBUG  pgadmin:        Python syspath: ['/pgadmin4', '/pgadmin4', '/usr/lib/python311.zip', '/usr/lib/python3.11', '/usr/lib/python3.11/lib-dynload', '/venv/lib/python3.11/site-packages', '/usr/lib/python3.11/site-packages']
2023-12-08 22:21:14,616: INFO   pgadmin:        Registering blueprint module: <AboutModule 'about'>
2023-12-08 22:21:14,617: INFO   pgadmin:        Registering blueprint module: <AuthenticateModule 'authenticate'>
2023-12-08 22:21:14,618: INFO   pgadmin:        Registering blueprint module: <BrowserModule 'browser'>
2023-12-08 22:21:15,900: INFO   pgadmin:        Registering blueprint module: <DashboardModule 'dashboard'>
2023-12-08 22:21:15,912: INFO   pgadmin:        Registering blueprint module: <DashboardModule 'dashboard'>
2023-12-08 22:21:15,912: INFO   pgadmin:        Registering blueprint module: <HelpModule 'help'>
2023-12-08 22:21:15,913: INFO   pgadmin:        Registering blueprint module: <MiscModule 'misc'>
2023-12-08 22:21:16,929: INFO   pgadmin:        Registering blueprint module: <PreferencesModule 'preferences'>
2023-12-08 22:21:16,932: INFO   pgadmin:        Registering blueprint module: <PgAdminModule 'redirects'>
2023-12-08 22:21:16,933: INFO   pgadmin:        Registering blueprint module: <SettingsModule 'settings'>
2023-12-08 22:21:16,936: INFO   pgadmin:        Registering blueprint module: <ToolsModule 'tools'>
----------
Loading servers with:
User: user@domain
SQLite pgAdmin config: /var/lib/pgadmin/pgadmin4.db
----------
Added 0 Server Group(s) and 2 Server(s).
postfix/postlog: starting the Postfix mail system
[2023-12-08 22:21:22 +0000] [1] [INFO] Starting gunicorn 20.1.0
[2023-12-08 22:21:22 +0000] [1] [INFO] Listening at: http://[::]:80 (1)
[2023-12-08 22:21:22 +0000] [1] [INFO] Using worker: gthread
[2023-12-08 22:21:22 +0000] [130] [INFO] Booting worker with pid: 130
2023-12-08 22:21:24,490: INFO   pgadmin:        ########################################################
2023-12-08 22:21:24,490: INFO   pgadmin:        Starting pgAdmin 4 v8.0...
2023-12-08 22:21:24,490: INFO   pgadmin:        ########################################################
2023-12-08 22:21:24,490: DEBUG  pgadmin:        Python syspath: ['/pgadmin4', '/venv/bin', '/pgadmin4', '/usr/lib/python311.zip', '/usr/lib/python3.11', '/usr/lib/python3.11/lib-dynload', '/venv/lib/python3.11/site-packages', '/usr/lib/python3.11/site-packages']
2023-12-08 22:21:25,435: INFO   pgadmin:        Registering blueprint module: <AboutModule 'about'>
2023-12-08 22:21:25,437: INFO   pgadmin:        Registering blueprint module: <AuthenticateModule 'authenticate'>
2023-12-08 22:21:25,438: INFO   pgadmin:        Registering blueprint module: <BrowserModule 'browser'>
2023-12-08 22:21:26,724: INFO   pgadmin:        Registering blueprint module: <DashboardModule 'dashboard'>
2023-12-08 22:21:26,741: INFO   pgadmin:        Registering blueprint module: <DashboardModule 'dashboard'>
2023-12-08 22:21:26,741: INFO   pgadmin:        Registering blueprint module: <HelpModule 'help'>
2023-12-08 22:21:26,742: INFO   pgadmin:        Registering blueprint module: <MiscModule 'misc'>
2023-12-08 22:21:27,820: INFO   pgadmin:        Registering blueprint module: <PreferencesModule 'preferences'>
2023-12-08 22:21:27,823: INFO   pgadmin:        Registering blueprint module: <PgAdminModule 'redirects'>
2023-12-08 22:21:27,824: INFO   pgadmin:        Registering blueprint module: <SettingsModule 'settings'>
2023-12-08 22:21:27,828: INFO   pgadmin:        Registering blueprint module: <ToolsModule 'tools'>
2023-12-08 22:21:28,625: DEBUG  pgadmin:        Config server mode: True
2023-12-08 22:21:28,626: DEBUG  pgadmin:        Not running under the desktop runtime, port: 5050
2023-12-08 22:22:19,344: ERROR  pgadmin:        400 Bad Request: The CSRF session token is missing.
Traceback (most recent call last):
  File "/venv/lib/python3.11/site-packages/flask_wtf/csrf.py", line 261, in protect
    validate_csrf(self._get_csrf_token())
  File "/venv/lib/python3.11/site-packages/flask_wtf/csrf.py", line 103, in validate_csrf
    raise ValidationError("The CSRF session token is missing.")
wtforms.validators.ValidationError: The CSRF session token is missing.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/venv/lib/python3.11/site-packages/flask/app.py", line 1482, in full_dispatch_request
    rv = self.preprocess_request()
         ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/venv/lib/python3.11/site-packages/flask/app.py", line 1974, in preprocess_request
    rv = self.ensure_sync(before_func)()
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/venv/lib/python3.11/site-packages/flask_wtf/csrf.py", line 229, in csrf_protect
    self.protect()
  File "/venv/lib/python3.11/site-packages/flask_wtf/csrf.py", line 264, in protect
    self._error_response(e.args[0])
  File "/venv/lib/python3.11/site-packages/flask_wtf/csrf.py", line 307, in _error_response
    raise CSRFError(reason)
flask_wtf.csrf.CSRFError: 400 Bad Request: The CSRF session token is missing.
15.248.1.242 - - [08/Dec/2023:22:22:19 +0000] "POST /settings/save_tree_state/ HTTP/1.1" 400 125 "https://pgadmin.domain.cloud/browser/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36 Edg/120.0.0.0"
15.248.1.242 - - [08/Dec/2023:22:22:19 +0000] "GET /browser/ HTTP/1.1" 302 237 "https://pgadmin.domain.cloud/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36 Edg/120.0.0.0"
2023-12-08 22:22:19,426: ERROR  pgadmin:        400 Bad Request: The CSRF session token is missing.
Traceback (most recent call last):
  File "/venv/lib/python3.11/site-packages/flask_wtf/csrf.py", line 261, in protect
    validate_csrf(self._get_csrf_token())
  File "/venv/lib/python3.11/site-packages/flask_wtf/csrf.py", line 103, in validate_csrf
    raise ValidationError("The CSRF session token is missing.")
wtforms.validators.ValidationError: The CSRF session token is missing.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/venv/lib/python3.11/site-packages/flask/app.py", line 1482, in full_dispatch_request
    rv = self.preprocess_request()
         ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/venv/lib/python3.11/site-packages/flask/app.py", line 1974, in preprocess_request
    rv = self.ensure_sync(before_func)()
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/venv/lib/python3.11/site-packages/flask_wtf/csrf.py", line 229, in csrf_protect
    self.protect()
  File "/venv/lib/python3.11/site-packages/flask_wtf/csrf.py", line 264, in protect
    self._error_response(e.args[0])
  File "/venv/lib/python3.11/site-packages/flask_wtf/csrf.py", line 307, in _error_response
    raise CSRFError(reason)
flask_wtf.csrf.CSRFError: 400 Bad Request: The CSRF session token is missing.
```

config_local.py

```
import logging

# Application log level - one of:
#   CRITICAL 50
#   ERROR    40
#   WARNING  30
#   SQL      25
#   INFO     20
#   DEBUG    10
#   NOTSET    0
CONSOLE_LOG_LEVEL = logging.DEBUG
FILE_LOG_LEVEL = logging.DEBUG

# Log format.
CONSOLE_LOG_FORMAT = '%(asctime)s: %(levelname)s\t%(name)s:\t%(message)s'
FILE_LOG_FORMAT = '%(asctime)s: %(levelname)s\t%(name)s:\t%(message)s'


##########################################################################
# Authentication Configuration
##########################################################################
AUTHENTICATION_SOURCES = ['oauth2']

##########################################################################
# OAuth2 Configuration
##########################################################################

# Multiple OAUTH2 providers can be added in the list like [{...},{...}]
# All parameters are required

OAUTH2_CONFIG = [
    {
        # The name of the of the oauth provider, ex: github, google
        'OAUTH2_NAME': '${SECRET_CLOUD_NAME_SHORT}',
        # The display name, ex: Google
        'OAUTH2_DISPLAY_NAME': '${SECRET_CLOUD_NAME}',
        # Oauth client id
        'OAUTH2_CLIENT_ID': 'pgadmin',
        # Oauth secret
        'OAUTH2_CLIENT_SECRET': '${SECRET_PGADMIN_OAUTH_CLIENT_SECRET}',
        # URL to generate a token,
        # Ex: https://github.com/login/oauth/access_token
        'OAUTH2_TOKEN_URL': "https://authelia.${SECRET_DEV_DOMAIN}/api/oidc/token",
        # URL is used for authentication,
        # Ex: https://github.com/login/oauth/authorize
        'OAUTH2_AUTHORIZATION_URL': "https://authelia.${SECRET_DEV_DOMAIN}/api/oidc/authorization",
        # server metadata url might optional for your provider
        'OAUTH2_SERVER_METADATA_URL': 'https://authelia.${SECRET_DEV_DOMAIN}/.well-known/openid-configuration',
        # Oauth base url, ex: https://api.github.com/
        'OAUTH2_API_BASE_URL': "https://authelia.${SECRET_DEV_DOMAIN}/",
        # Name of the Endpoint, ex: user
        'OAUTH2_USERINFO_ENDPOINT': "https://authelia.${SECRET_DEV_DOMAIN}/api/oidc/userinfo",
        # Oauth scope, ex: 'openid email profile'
        # Note that an 'email' claim is required in the resulting profile
        'OAUTH2_SCOPE': 'openid email profile',
        # The claim which is used for the username. If the value is empty the
        # email is used as username, but if a value is provided,
        # the claim has to exist.
        'OAUTH2_USERNAME_CLAIM': 'email',
        # Font-awesome icon, ex: fa-github
        'OAUTH2_ICON': 'keycdn',
        # UI button colour, ex: #0000ff
        'OAUTH2_BUTTON_COLOR': None,
        # The additional claims to check on user ID Token or Userinfo response.
        # This is useful to provide additional authorization checks
        # before allowing access.
        # Example for GitLab: allowing all maintainers teams, and a specific
        # developers group to access pgadmin:
        # 'OAUTH2_ADDITIONAL_CLAIMS': {
        #     'https://gitlab.org/claims/groups/maintainer': [
        #           'kuberheads/applications',
        #           'kuberheads/dba',
        #           'kuberheads/support'
        #      ],
        #     'https://gitlab.org/claims/groups/developer': [
        #           'kuberheads/applications/team01'
        #      ],
        # }
        # Example for AzureAD:
        # 'OAUTH2_ADDITIONAL_CLAIMS': {
        #     'groups': ["0760b6cf-170e-4a14-91b3-4b78e0739963"],
        #     'wids': ["cf1c38e5-3621-4004-a7cb-879624dced7c"],
        # }
        'OAUTH2_ADDITIONAL_CLAIMS': None,
    }
]

# After Oauth authentication, user will be added into the SQLite database
# automatically, if set to True.
# Set it to False, if user should not be added automatically,
# in this case Admin has to add the user manually in the SQLite database.
```

servers.json:

```
OAUTH2_AUTO_CREATE_USER = True
{
  "Servers": {
      "1": {
          "Name": "defaultpg",
          "Group": "Servers",
          "Host": "defaultpg-rw.databases.svc.cluster.local",
          "Port": 5432,
          "MaintenanceDB": "postgres",
          "Username": "postgres",
          "SSLMode": "prefer",
          "SSLCert": "",
          "SSLKey": "",
          "SSLCompression": 0,
          "Timeout": 10,
          "UseSSHTunnel": 0,
          "TunnelPort": "22",
          "TunnelAuthentication": 0
      },
      "2": {
          "Name": "backup",
          "Group": "Servers",
          "Host": "backup-rw.databases.svc.cluster.local",
          "Port": 5432,
          "MaintenanceDB": "postgres",
          "Username": "postgres",
          "SSLMode": "prefer",
          "SSLCert": "",
          "SSLKey": "",
          "SSLCompression": 0,
          "Timeout": 10,
          "UseSSHTunnel": 0,
          "TunnelPort": "22",
          "TunnelAuthentication": 0
      }
  }
}
```

**Comment by matietz** [comment]
You need to set the `Shared` attribute to `true` for each connection. E.g. in your example:

```json
{
  "Servers": {
      "1": {
          "Name": "defaultpg",
          "Group": "Servers",
          "Host": "defaultpg-rw.databases.svc.cluster.local",
          "Port": 5432,
          "MaintenanceDB": "postgres",
          "Username": "postgres",
          "Shared": true,
          "SSLMode": "prefer",
          "SSLCert": "",
          "SSLKey": "",
          "SSLCompression": 0,
          "Timeout": 10,
          "UseSSHTunnel": 0,
          "TunnelPort": "22",
          "TunnelAuthentication": 0
      },
      "2": {
          "Name": "backup",
          "Group": "Servers",
          "Host": "backup-rw.databases.svc.cluster.local",
          "Port": 5432,
          "MaintenanceDB": "postgres",
          "Username": "postgres",
          "Shared": true,
          "SSLMode": "prefer",
          "SSLCert": "",
          "SSLKey": "",
          "SSLCompression": 0,
          "Timeout": 10,
          "UseSSHTunnel": 0,
          "TunnelPort": "22",
          "TunnelAuthentication": 0
      }
  }
}
```

AFAIK connections that are imported via `servers.json` are owned by the master user of the pgAdmin instance and by default they are only visible to this single user. Setting it to shared makes it visible to all users of a pgAdmin instance. Read more about that concept here: [Shared Servers in pgAdmin 4
](https://www.enterprisedb.com/blog/shared-servers-pgadmin-4)

**Comment by adityatoshniwal** [comment]
Hi @lenaxia,
Currently, a server.json file is loaded for the pgAdmin default username supplied when starting the docker instance. So, the local user will see the servers loaded, in this case the default username.
As suggested by @matietz, you could make them shared so that all the users logged in can see the servers.

**Comment by lenaxia** [comment]
Shared worked. Thanks @matietz @adityatoshniwal, its at least usable now. 

One thing I notice is that shared servers do not honor the username field. 

```
{
  "Servers": {
      "1": {
          "Name": "defaultpg",
          "Group": "Servers",
          "Host": "defaultpg-rw.databases.svc.cluster.local",
          "Port": 5432,
          "MaintenanceDB": "postgres",
          "Username": "postgres",
          "Shared": true,
          "SSLMode": "prefer",
          "SSLCert": "<STORAGE_DIR>/.postgresql/postgresql.crt",
          "SSLKey": "<STORAGE_DIR>/.postgresql/postgresql.key",
          "SSLCompression": 0,
          "Timeout": 10,
          "UseSSHTunnel": 0,
          "TunnelPort": "22",
          "TunnelAuthentication": 0
      },
      "2": {
          "Name": "backup",
          "Group": "Servers",
          "Host": "backup-rw.databases.svc.cluster.local",
          "Port": 5432,
          "MaintenanceDB": "postgres",
          "Username": "postgres",
          "Shared": true,
          "SSLMode": "prefer",
          "SSLCert": "<STORAGE_DIR>/.postgresql/postgresql.crt",
          "SSLKey": "<STORAGE_DIR>/.postgresql/postgresql.key",
          "SSLCompression": 0,
          "Timeout": 10,
          "UseSSHTunnel": 0,
          "TunnelPort": "22",
          "TunnelAuthentication": 0
      }
  }
}
```

In both of these instances, upon first access to the defined servers, I have to manually type in the username before I can use the connection. 

Appreciate the help!

**Comment by adityatoshniwal** [comment]
Hi @lenaxia,
You can use "SharedUsername" key to set the username - https://www.pgadmin.org/docs/pgadmin4/8.1/import_export_servers.html#json-format.

Closing this. Thanks.
