### ISSUE TITLE
ldap authentication fails against ldap.js

### ISSUE THREAD

**Issue by andreimirt** [pgadmin-org/pgadmin4#7062]
**Describe the bug**

Authentication fails against ldap.js because the the requested schema doesn't pass validation, even though the schema is not needed for authentication, so the server could be defined using ```get_info=None``` instead of ```get_info=ALL```

**To Reproduce**

1. Spin [node ldap.js](https://github.com/ldapjs/node-ldapjs) server
2. Configure authentication by following [pgadmin documentation](https://www.pgadmin.org/docs/pgadmin4/8.1/ldap.html)
3. Check the logs for the error ```raise LDAPSchemaError('malformed schema definition, use get_info=NONE in Server definition')```

**Expected behavior**

The LDAP user should be authenticated considering that regardless of the validity of the schema, it is not needed for authentication.

**Error message**
```
2023-12-16 01:48 | ldap3.core.exceptions.LDAPSchemaError: malformed schema definition, use get_info=NONE in Server definition | stdout
-- | -- | --
2023-12-16 01:48 | raise LDAPSchemaError('malformed schema definition, use get_info=NONE in Server definition') | stdout
2023-12-16 01:48 | File "/venv/lib/python3.11/site-packages/ldap3/protocol/rfc4512.py", line 552, in from_definition | stdout
2023-12-16 01:48 | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ | stdout
2023-12-16 01:48 | self.object_classes = ObjectClassInfo.from_definition(attributes.pop('objectClasses', [])) | stdout
2023-12-16 01:48 | File "/venv/lib/python3.11/site-packages/ldap3/protocol/rfc4512.py", line 299, in __init__ | stdout
2023-12-16 01:48 | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ | stdout
2023-12-16 01:48 | self._schema_info = SchemaInfo(schema_entry, response[0]['attributes'], response[0]['raw_attributes']) | stdout
2023-12-16 01:48 | File "/venv/lib/python3.11/site-packages/ldap3/core/server.py", line 501, in _get_schema_info | stdout
2023-12-16 01:48 | self._get_schema_info(connection) | stdout
2023-12-16 01:48 | File "/venv/lib/python3.11/site-packages/ldap3/core/server.py", line 525, in get_info_from_server | stdout
2023-12-16 01:48 | self.server.get_info_from_server(self) | stdout
2023-12-16 01:48 | File "/venv/lib/python3.11/site-packages/ldap3/core/connection.py", line 1427, in refresh_server_info | stdout
2023-12-16 01:48 | self.refresh_server_info() | stdout
2023-12-16 01:48 | File "/venv/lib/python3.11/site-packages/ldap3/core/connection.py", line 671, in bind | stdout
2023-12-16 01:48 | self.bind(read_server_info=True) | stdout
2023-12-16 01:48 | File "/venv/lib/python3.11/site-packages/ldap3/core/connection.py", line 389, in _do_auto_bind | stdout
2023-12-16 01:48 | self._do_auto_bind() | stdout
2023-12-16 01:48 | File "/venv/lib/python3.11/site-packages/ldap3/core/connection.py", line 363, in __init__ | stdout
2023-12-16 01:48 | ^^^^^^^^^^^^^^^^^^ | stdout
2023-12-16 01:48 | self.conn = Connection(server, | stdout
2023-12-16 01:48 | File "/pgadmin4/pgadmin/authenticate/ldap.py", line 125, in connect | stdout
2023-12-16 01:48 | Traceback (most recent call last): | stdout
2023-12-16 01:48 | 2023-12-15  23:48:04,392: ERROR	pgadmin:	Error connecting to the LDAP server:  malformed schema definition, use get_info=NONE in Server definition
```

**Official Docker image**
 - OS: [e.g. Windows 10, OSX monterey]
 - Version: [8.1]
 - Mode: [Server]
 - Browser (if running in server mode): [firefox]
 - Package type: [Container]

**Additional context**

I am using the Azure-LDAP-wrapper that uses ldap.js server, but I'm using it to authenticate successfully multiple services, including postgresql. I am aware that if there wouldn't be any other issue either in the server or in the client, the current ldap client implementation in pgadmin should not make a difference, but considering that likely server.schema is not necessary for authentication, pgadmin should perhaps not request it, which allows ldap authentication on more systems.

**Workaround**

To temporary fix the issue I did exactly what the error message from [ldap3 ](https://github.com/cannatag/ldap3) library suggests in the error message. I modified [ldap.py](https://github.com/pgadmin-org/pgadmin4/blob/9379df25438ef4da19d2038307eac5c4ae0a6aab/web/pgadmin/authenticate/ldap.py#L257) in the sense of modifying ```get_info=ALL``` to ```get_info=None```. This allows authentication without any issues. Changing this would leave ```server.schema``` empty, but I couldn't find any place where it would be needed.

**Comment by khushboovashi** [comment]
@andreimirt, please test https://github.com/pgadmin-org/pgadmin4/pull/7080.
Set config parameter LDAP_IGNORE_MALFORMED_SCHEMA to True and test.

**Comment by yogeshmahajan-1903** [comment]
@andreimirt 
Can you please verify the fix?
I am not able to reproduce issue where I have setup the ldap server with ldap.js.
