### ISSUE TITLE
"PGadmin 4 quit unexpectedly" error on Mac

### ISSUE THREAD

**Issue by plmueller** [pgadmin-org/pgadmin4#7141]
**_Please note that security bugs or issues should be reported to security@pgadmin.org._**

**Describe the bug**

Whenever opening pgadmin on my mac the application starts up and then crashes immediately and provides the following error message 

**Expected behavior**

**Error message**

Translated Report (Full Report Below)
-------------------------------------

Process:               pgAdmin 4 [2514]
Path:                  /Users/USER/pgAdmin 4.app/Contents/MacOS/pgAdmin 4
Identifier:            org.pgadmin.pgadmin4
Version:               7.8 (4280.88)
Code Type:             X86-64 (Translated)
Parent Process:        launchd [1]
User ID:               501

Date/Time:             2024-01-20 12:17:28.4795 -0800
OS Version:            macOS 14.2.1 (23C71)
Report Version:        12
Anonymous UUID:        44A1EE73-93EC-8E77-1832-A71FAFF186F8

Time Awake Since Boot: 2100 seconds

System Integrity Protection: enabled

Notes:
PC register does not match crashing frame (0x0 vs 0x10298E9C8)

**Screenshots**

![image](https://github.com/pgadmin-org/pgadmin4/assets/138350289/bdda9a99-8aa2-48f1-9895-a3b91e891fe6)

**Comment by adityatoshniwal** [comment]
Hi @plmueller,
Which installer did you use? https://www.postgresql.org/ftp/pgadmin/pgadmin4/v8.2/macos/ there are 2 here - one is for M series Mac and other one is for intel one.

**Comment by plmueller** [comment]
Hi this is the list I downloaded from. I clicked on the most recent one under Mac OS XSent from my iPhoneOn Jan 21, 2024, at 7:32 PM, Aditya Toshniwal ***@***.***> wrote:﻿
Hi @plmueller,
Which installer did you use? https://www.postgresql.org/ftp/pgadmin/pgadmin4/v8.2/macos/ there are 2 here - one is for M series Mac and other one is for intel one.

**Comment by adityatoshniwal** [comment]
Hi @plmueller,
I cannot see the list you shared. If you're referring to what I shared, there 2 installers for different types of machines. Please share your Mac machine details.

**Comment by plmueller** [comment]
I have MacBook Air, version Sonoma 14.2.1Sent from my iPhoneOn Jan 21, 2024, at 8:35 PM, Aditya Toshniwal ***@***.***> wrote:﻿
Hi @plmueller,
I cannot see the list you shared. If you're referring to what I shared, there 2 installers for different types of machines. Please share your Mac machine details.

**Comment by adityatoshniwal** [comment]
@plmueller uninstall existing and install arm64 based from https://www.postgresql.org/ftp/pgadmin/pgadmin4/v8.2/macos/

**Comment by plmueller** [comment]
It seems to be working now. But now I am having trouble with importing my database. I keep getting the binary path errorSent from my iPhoneOn Jan 21, 2024, at 10:02 PM, Aditya Toshniwal ***@***.***> wrote:﻿
@plmueller uninstall existing and install arm64 based from https://www.postgresql.org/ftp/pgadmin/pgadmin4/v8.2/macos/

**Comment by sanskritibpandey** [comment]
Hi @adityatoshniwal, I have the same issue with 1.6 GHz Dual-Core Intel Core i5 on MacBook Air with Sonoma 14.2.1 (23C71) after downloading from both  https://www.postgresql.org/ftp/pgadmin/pgadmin4/v8.2/macos/ and https://www.enterprisedb.com/downloads/postgres-postgresql-downloads

**Comment by yogeshmahajan-1903** [comment]
@plmueller 
Can you please share error screenshot and pgadmin logs?

**Comment by ronwildt** [comment]
Having the same issue for the past several weeks.  Pgadmin4 screen goes entirely blank other than the application bar at the top of the screen, only thing you can do is Quit the app and restart.  This started happening when upgrading to v8.2 for Intel Macbook chipset.  Very annoying...!

**Comment by pravesh-sharma** [comment]
Hi @plmueller,

Can you please share logs from the menu pgAdmin4->Runtime->View log.

**Comment by ronwildt** [comment]
Hi @pravesh-sharma Here's the log from mine, even after upgrading to the pgadmin4 Feb 9th version, it's still hanging and the only thing I can do is quit or force quit pgadmin4...very frustrating.

pgAdmin Runtime Environment
--------------------------------------------------------
Python Path: "/Applications/pgAdmin 4.app/Contents/Frameworks/Python.framework/Versions/Current/bin/python3"
Runtime Config File: "/Users/z001wq8/Library/Preferences/pgadmin/runtime_config.json"
pgAdmin Config File: "/Applications/pgAdmin 4.app/Contents/Resources/web/config.py"
Webapp Path: "/Applications/pgAdmin 4.app/Contents/Resources/web/pgAdmin4.py"
pgAdmin Command: "/Applications/pgAdmin 4.app/Contents/Frameworks/Python.framework/Versions/Current/bin/python3 -s /Applications/pgAdmin 4.app/Contents/Resources/web/pgAdmin4.py"
Environment: 
  - MallocNanoZone: 0
  - USER: z001wq8
  - COMMAND_MODE: unix2003
  - __CFBundleIdentifier: org.pgadmin.pgadmin4
  - PATH: /usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin
  - LOGNAME: z001wq8
  - SYSTEM_VERSION_COMPAT: 0
  - SSH_AUTH_SOCK: /private/tmp/com.apple.launchd.56JR5BDaAc/Listeners
  - HOME: /Users/z001wq8
  - SHELL: /bin/zsh
  - TMPDIR: /var/folders/hq/glmd73_d2k504tk2x8xv61gh2xyfjm/T/
  - __CF_USER_TEXT_ENCODING: 0x5DF3A34:0x0:0x0
  - XPC_SERVICE_NAME: application.org.pgadmin.pgadmin4.294120334.294135485
  - XPC_FLAGS: 0x0
  - PGADMIN_INT_PORT: 58688
  - PGADMIN_INT_KEY: d95b1fc0-9c39-4bc1-8313-923e2563223c
  - PGADMIN_SERVER_MODE: OFF
--------------------------------------------------------

Total spawn time to start the pgAdmin4 server: 0.095 Sec
2024-02-09 13:09:06,937: WARNING	werkzeug:	Werkzeug appears to be used in a production deployment. Consider switching to a production web server instead.

 * Serving Flask app 'pgadmin'
 * Debug mode: off

------------------------------------------
Total time taken to ping pgAdmin4 server: 27.239 Sec
------------------------------------------
Total launch time of pgAdmin4: 27.563 Sec
------------------------------------------
Application Server URL: http://127.0.0.1:58688/?key=d95b1fc0-9c39-4bc1-8313-923e2563223c
2024-02-09 13:09:10,976: ERROR	pgadmin:	Exception when checking for update
Traceback (most recent call last):
  File "/Applications/pgAdmin 4.app/Contents/Frameworks/Python.framework/Versions/3.11/lib/python3.11/urllib/request.py", line 1348, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "/Applications/pgAdmin 4.app/Contents/Frameworks/Python.framework/Versions/3.11/lib/python3.11/http/client.py", line 1286, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/Applications/pgAdmin 4.app/Contents/Frameworks/Python.framework/Versions/3.11/lib/python3.11/http/client.py", line 1332, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/Applications/pgAdmin 4.app/Contents/Frameworks/Python.framework/Versions/3.11/lib/python3.11/http/client.py", line 1281, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/Applications/pgAdmin 4.app/Contents/Frameworks/Python.framework/Versions/3.11/lib/python3.11/http/client.py", line 1041, in _send_output
    self.send(msg)
  File "/Applications/pgAdmin 4.app/Contents/Frameworks/Python.framework/Versions/3.11/lib/python3.11/http/client.py", line 979, in send
    self.connect()
  File "/Applications/pgAdmin 4.app/Contents/Frameworks/Python.framework/Versions/3.11/lib/python3.11/http/client.py", line 1458, in connect
    self.sock = self._context.wrap_socket(self.sock,
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Applications/pgAdmin 4.app/Contents/Frameworks/Python.framework/Versions/3.11/lib/python3.11/ssl.py", line 517, in wrap_socket
    return self.sslsocket_class._create(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Applications/pgAdmin 4.app/Contents/Frameworks/Python.framework/Versions/3.11/lib/python3.11/ssl.py", line 1108, in _create
    self.do_handshake()
  File "/Applications/pgAdmin 4.app/Contents/Frameworks/Python.framework/Versions/3.11/lib/python3.11/ssl.py", line 1379, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1006)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Applications/pgAdmin 4.app/Contents/Resources/web/pgadmin/misc/__init__.py", line 272, in upgrade_check
    response = urlopen(url, data, 5, cafile=config.CA_FILE)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Applications/pgAdmin 4.app/Contents/Frameworks/Python.framework/Versions/3.11/lib/python3.11/urllib/request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Applications/pgAdmin 4.app/Contents/Frameworks/Python.framework/Versions/3.11/lib/python3.11/urllib/request.py", line 519, in open
    response = self._open(req, data)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Applications/pgAdmin 4.app/Contents/Frameworks/Python.framework/Versions/3.11/lib/python3.11/urllib/request.py", line 536, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Applications/pgAdmin 4.app/Contents/Frameworks/Python.framework/Versions/3.11/lib/python3.11/urllib/request.py", line 496, in _call_chain
    result = func(*args)
             ^^^^^^^^^^^
  File "/Applications/pgAdmin 4.app/Contents/Frameworks/Python.framework/Versions/3.11/lib/python3.11/urllib/request.py", line 1391, in https_open
    return self.do_open(http.client.HTTPSConnection, req,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Applications/pgAdmin 4.app/Contents/Frameworks/Python.framework/Versions/3.11/lib/python3.11/urllib/request.py", line 1351, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1006)>

2024-02-09 13:12:43,288: ERROR	pgadmin:	Failed to execute query (execute_async) for the server #72 - CONN:3276194(Query-id: 6232605):
Error Message:ERROR:  column "ns.hostname" must appear in the GROUP BY clause or be used in an aggregate function
LINE 1: select RTRIM(ns.hostname, '.hq.target.com') as hostname, str...
                     ^ 

SQL state: 42803
Character: 14

2024-02-09 13:27:49,561: ERROR	pgadmin:	Failed to execute query (execute_async) for the server #72 - CONN:3276194(Query-id: 3723680):
Error Message:ERROR:  column "request_json" does not exist
LINE 1: select bd.portfolio, request_json ->> 'osName' as osName, * 
                             ^ 

SQL state: 42703
Character: 22

2024-02-09 13:35:01,153: ERROR	pgadmin:	Failed to execute query (execute_async) for the server #72 - CONN:3276194(Query-id: 6974885):
Error Message:ERROR:  column "request_json" does not exist
LINE 1: select bd.portfolio, request_json ->> 'osName' as osName, * 
                             ^ 

SQL state: 42703
Character: 22

2024-02-09 13:37:43,683: ERROR	pgadmin:	Failed to execute query (execute_async) for the server #72 - CONN:3276194(Query-id: 2471674):
Error Message:ERROR:  column "json_data" does not exist
LINE 1: select bd.portfolio, json_data ->> 'osName' as osName, * 
                             ^ 

SQL state: 42703
Character: 22

2024-02-09 13:38:16,845: ERROR	pgadmin:	Failed to execute query (execute_async) for the server #72 - CONN:3276194(Query-id: 1087599):
Error Message:ERROR:  column "json_data" does not exist
LINE 2: select bd.portfolio, json_data -> 'osName' osName, * 
                             ^ 

SQL state: 42703
Character: 76

2024-02-09 13:42:52,817: ERROR	pgadmin:	Failed to execute query (execute_async) for the server #72 - CONN:3276194(Query-id: 912226):
Error Message:ERROR:  column "bd.portfolio" must appear in the GROUP BY clause or be used in an aggregate function
LINE 1: select bd.portfolio, ns.platform_specific_attributes ->> 'os...
               ^ 

SQL state: 42803
Character: 8

2024-02-09 13:43:26,471: ERROR	pgadmin:	Failed to execute query (execute_async) for the server #72 - CONN:3276194(Query-id: 1764490):
Error Message:ERROR:  column "ns.platform_specific_attributes" must appear in the GROUP BY clause or be used in an aggregate function
LINE 1: select bd.portfolio, ns.platform_specific_attributes ->> 'os...
                             ^ 

SQL state: 42803
Character: 22

2024-02-09 13:46:35,017: ERROR	pgadmin:	Failed to execute query (execute_async) for the server #72 - CONN:3276194(Query-id: 927343):
Error Message:ERROR:  column "ns.platform_specific_attributes" must appear in the GROUP BY clause or be used in an aggregate function
LINE 1: select bd.portfolio, ns.platform_specific_attributes ->> 'os...
                             ^ 

SQL state: 42803
Character: 22

--------------[UI error]---------------
[object Object] "It's a leaf node"
------------[UI End]----------------
2024-02-09 14:12:04,832: ERROR	pgadmin:	Failed to execute query (execute_async) for the server #71 - CONN:8078037(Query-id: 2070580):
Error Message:ERROR:  permission denied for schema inventory
CONTEXT:  remote SQL command: SELECT r4.portfolio, r2.platform_specific_attributes FROM ((inventory.cluster_state r1 INNER JOIN inventory.node_state r2 ON (((r1.cluster_id = r2.cluster_id)) AND ((r2.platform = 'VMAAS'::text)) AND ((r1.technology = 'POSTGRES'::text)) AND ((r1.lifecycle_state = 'PROVISIONED'::text)))) INNER JOIN inventory.blossom_details r4 ON (((r1.blossom_id = r4.blossom_id)))) 

SQL state: 42501

2024-02-09 15:30:07,808: ERROR	pgadmin:	<asyncio.locks.Lock object at 0x10a892010 [unlocked, waiters:1]> is bound to a different event loop
Traceback (most recent call last):
  File "/Applications/pgAdmin 4.app/Contents/Resources/web/pgadmin/utils/driver/psycopg3/cursor.py", line 281, in execute
    return asyncio.run(self._execute(query, params))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Applications/pgAdmin 4.app/Contents/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/Applications/pgAdmin 4.app/Contents/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Applications/pgAdmin 4.app/Contents/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/Applications/pgAdmin 4.app/Contents/Resources/web/pgadmin/utils/driver/psycopg3/cursor.py", line 292, in _execute
    return await _async_cursor.execute(self, query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Applications/pgAdmin 4.app/Contents/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/psycopg/cursor_async.py", line 89, in execute
    async with self._conn.lock:
  File "/Applications/pgAdmin 4.app/Contents/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/locks.py", line 15, in __aenter__
    await self.acquire()
  File "/Applications/pgAdmin 4.app/Contents/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/locks.py", line 106, in acquire
    fut = self._get_loop().create_future()
          ^^^^^^^^^^^^^^^^
  File "/Applications/pgAdmin 4.app/Contents/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/mixins.py", line 20, in _get_loop
    raise RuntimeError(f'{self!r} is bound to a different event loop')
RuntimeError: <asyncio.locks.Lock object at 0x10a892010 [unlocked, waiters:1]> is bound to a different event loop

2024-02-09 15:30:07,826: ERROR	pgadmin:	<asyncio.locks.Lock object at 0x10a892010 [unlocked, waiters:1]> is bound to a different event loop
Traceback (most recent call last):
  File "/Applications/pgAdmin 4.app/Contents/Resources/web/pgadmin/utils/driver/psycopg3/cursor.py", line 281, in execute
    return asyncio.run(self._execute(query, params))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Applications/pgAdmin 4.app/Contents/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/Applications/pgAdmin 4.app/Contents/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Applications/pgAdmin 4.app/Contents/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/Applications/pgAdmin 4.app/Contents/Resources/web/pgadmin/utils/driver/psycopg3/cursor.py", line 292, in _execute
    return await _async_cursor.execute(self, query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Applications/pgAdmin 4.app/Contents/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/psycopg/cursor_async.py", line 89, in execute
    async with self._conn.lock:
  File "/Applications/pgAdmin 4.app/Contents/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/locks.py", line 15, in __aenter__
    await self.acquire()
  File "/Applications/pgAdmin 4.app/Contents/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/locks.py", line 106, in acquire
    fut = self._get_loop().create_future()
          ^^^^^^^^^^^^^^^^
  File "/Applications/pgAdmin 4.app/Contents/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/mixins.py", line 20, in _get_loop
    raise RuntimeError(f'{self!r} is bound to a different event loop')
RuntimeError: <asyncio.locks.Lock object at 0x10a892010 [unlocked, waiters:1]> is bound to a different event loop
2024-02-09 15:30:07,828: ERROR	pgadmin:	<asyncio.locks.Lock object at 0x10a892010 [unlocked, waiters:1]> is bound to a different event loop
Traceback (most recent call last):
  File "/Applications/pgAdmin 4.app/Contents/Resources/web/pgadmin/utils/driver/psycopg3/cursor.py", line 281, in execute
    return asyncio.run(self._execute(query, params))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Applications/pgAdmin 4.app/Contents/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/Applications/pgAdmin 4.app/Contents/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Applications/pgAdmin 4.app/Contents/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/Applications/pgAdmin 4.app/Contents/Resources/web/pgadmin/utils/driver/psycopg3/cursor.py", line 292, in _execute
    return await _async_cursor.execute(self, query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Applications/pgAdmin 4.app/Contents/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/psycopg/cursor_async.py", line 89, in execute
    async with self._conn.lock:
  File "/Applications/pgAdmin 4.app/Contents/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/locks.py", line 15, in __aenter__
    await self.acquire()
  File "/Applications/pgAdmin 4.app/Contents/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/locks.py", line 106, in acquire
    fut = self._get_loop().create_future()
          ^^^^^^^^^^^^^^^^
  File "/Applications/pgAdmin 4.app/Contents/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/mixins.py", line 20, in _get_loop
    raise RuntimeError(f'{self!r} is bound to a different event loop')
RuntimeError: <asyncio.locks.Lock object at 0x10a892010 [unlocked, waiters:1]> is bound to a different event loop

**Comment by adityatoshniwal** [comment]
@ronwildt What is your pgAdmin version?

**Comment by ronwildt** [comment]
@adityatoshniwal Just upgraded to version 8.3 in hopes of eliminating the 'crash / hang' by pgadmin4, on Friday, fyi.

**Comment by akshay-joshi** [comment]
We are closing this issue now, feel free to open it again if the issue persists.
