### ISSUE TITLE
Better error message than "hnsw"

### ISSUE THREAD

**Issue by IndigoCurnick** [pgadmin-org/pgadmin4#7291]
**Describe the solution you'd like**

When comparing databases, sometimes there can be a "hnsw" error. I believe(?) this is happening because one database has [pgvector](https://github.com/pgvector/pgvector) installed and the other does not. 

This isn't a very helpful error message! It would be better if it was something like "Error: installed extensions don't match"

**Additional context**

Here's the entire error message we get

![image](https://github.com/pgadmin-org/pgadmin4/assets/81766659/53f4d008-b933-44a7-a308-33c56954e6a3)

**Comment by pravesh-sharma** [comment]
Hi @IndigoCurnick,

I am not able to reproduce the issue. I have tried with pgvector 0.7.3. Can you please share the logs if you can still reproduce this issue?

You can find logs at:
for macOS `pgAdmin4 -> View Logs` 
for Linux/Window `File -> View Logs`

**Comment by akshay-joshi** [comment]
No response from the author, hence closing it.

**Comment by Starbuck5** [comment]
I just ran into this as well, posting some additional info in case someone else comes across this in the future.

I encountered this bug on pgAdmin 4 v8.0, and updating to the current latest (8.14) fixed it for me.

The logs looked like this:
```py
2024-12-20 12:13:15,233: ERROR	pgadmin:	'hnsw'
Traceback (most recent call last):
  File "C:\Users\charl\AppData\Local\Programs\pgAdmin 4\web\pgadmin\tools\schema_diff\__init__.py", line 632, in compare_schema
    compare_schema_objects(
  File "C:\Users\charl\AppData\Local\Programs\pgAdmin 4\web\pgadmin\tools\schema_diff\__init__.py", line 868, in compare_schema_objects
    res = view.compare(source_sid=source_sid,
  File "C:\Users\charl\AppData\Local\Programs\pgAdmin 4\web\pgadmin\browser\server_groups\servers\databases\schemas\tables\schema_diff_utils.py", line 83, in compare
    return compare_dictionaries(view_object=self,
  File "C:\Users\charl\AppData\Local\Programs\pgAdmin 4\web\pgadmin\tools\schema_diff\directory_compare.py", line 463, in compare_dictionaries
    identical, different = _get_identical_and_different_list(
  File "C:\Users\charl\AppData\Local\Programs\pgAdmin 4\web\pgadmin\tools\schema_diff\directory_compare.py", line 315, in _get_identical_and_different_list
    view_object.get_sql_from_table_diff(**temp_src_params)
  File "C:\Users\charl\AppData\Local\Programs\pgAdmin 4\web\pgadmin\browser\server_groups\servers\databases\schemas\tables\utils.py", line 163, in wrap
    return f(*args, **kwargs)
  File "C:\Users\charl\AppData\Local\Programs\pgAdmin 4\web\pgadmin\browser\server_groups\servers\databases\schemas\tables\__init__.py", line 1298, in get_sql_from_table_diff
    sql, partition_sql = BaseTableView.get_reverse_engineered_sql(
  File "C:\Users\charl\AppData\Local\Programs\pgAdmin 4\web\pgadmin\browser\server_groups\servers\databases\schemas\tables\utils.py", line 1057, in get_reverse_engineered_sql
    self._get_resql_for_index(did, tid, main_sql, json_resp, schema,
  File "C:\Users\charl\AppData\Local\Programs\pgAdmin 4\web\pgadmin\browser\server_groups\servers\databases\schemas\tables\utils.py", line 756, in _get_resql_for_index
    index_sql = index_utils.get_reverse_engineered_sql(
  File "C:\Users\charl\AppData\Local\Programs\pgAdmin 4\web\pgadmin\browser\server_groups\servers\databases\schemas\tables\indexes\utils.py", line 33, in wrap
    return f(*args, **kwargs)
  File "C:\Users\charl\AppData\Local\Programs\pgAdmin 4\web\pgadmin\browser\server_groups\servers\databases\schemas\tables\indexes\utils.py", line 321, in get_reverse_engineered_sql
    storage_params = get_storage_params(data['amname'])
  File "C:\Users\charl\AppData\Local\Programs\pgAdmin 4\web\pgadmin\browser\server_groups\servers\databases\schemas\tables\indexes\utils.py", line 366, in get_storage_params
    return storage_parameters[amname]
KeyError: 'hnsw'
```

One of the databases is using vector 0.7.0, the other is using 0.4.4.
