### ISSUE TITLE
Docker deployment fails on migration

### ISSUE THREAD

**Issue by MaartenUreel** [pgadmin-org/pgadmin4#7312]
I am trying to deploy pgadmin as Azure Web App.

The deployment fails and the log displays:
```
2024-03-24T20:27:36.408360868Z [2024-03-24 20:27:36 +0000] [1] [INFO] Starting gunicorn 20.1.0
2024-03-24T20:27:36.408699574Z [2024-03-24 20:27:36 +0000] [1] [INFO] Listening at: http://[::]:80 (1)
2024-03-24T20:27:36.408731574Z [2024-03-24 20:27:36 +0000] [1] [INFO] Using worker: gthread
2024-03-24T20:27:36.419748279Z [2024-03-24 20:27:36 +0000] [23] [INFO] Booting worker with pid: 23
2024-03-24T20:27:47.790461833Z NOTE: Configuring authentication for SERVER mode.
2024-03-24T20:27:47.790506634Z 
2024-03-24T20:27:47.790515334Z Enter the email address and password to use for the initial pgAdmin user account:
2024-03-24T20:27:47.790522034Z 
2024-03-24T20:27:47.796822352Z 2024-03-24 20:27:47,796: ERROR	pgadmin:	Database migration failed
2024-03-24T20:27:47.806488333Z 2024-03-24 20:27:47,806: ERROR	pgadmin:	Traceback (most recent call last):
2024-03-24T20:27:47.806534633Z   File "/pgadmin4/pgadmin/__init__.py", line 386, in upgrade_db
2024-03-24T20:27:47.806542834Z     db_upgrade(app)
2024-03-24T20:27:47.806548534Z   File "/pgadmin4/pgadmin/setup/db_upgrade.py", line 22, in db_upgrade
2024-03-24T20:27:47.806554134Z     flask_migrate.upgrade(migration_folder)
2024-03-24T20:27:47.806559034Z   File "/venv/lib/python3.11/site-packages/flask_migrate/__init__.py", line 111, in wrapped
2024-03-24T20:27:47.806572534Z     f(*args, **kwargs)
2024-03-24T20:27:47.806577734Z   File "/venv/lib/python3.11/site-packages/flask_migrate/__init__.py", line 200, in upgrade
2024-03-24T20:27:47.806583034Z     command.upgrade(config, revision, sql=sql, tag=tag)
2024-03-24T20:27:47.806588034Z   File "/venv/lib/python3.11/site-packages/alembic/command.py", line 403, in upgrade
2024-03-24T20:27:47.806592935Z     script.run_env()
2024-03-24T20:27:47.806598735Z   File "/venv/lib/python3.11/site-packages/alembic/script/base.py", line 583, in run_env
2024-03-24T20:27:47.806603935Z     util.load_python_file(self.dir, "env.py")
2024-03-24T20:27:47.806608735Z   File "/venv/lib/python3.11/site-packages/alembic/util/pyfiles.py", line 95, in load_python_file
2024-03-24T20:27:47.806613935Z     module = load_module_py(module_id, path)
2024-03-24T20:27:47.806618535Z              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-03-24T20:27:47.806623335Z   File "/venv/lib/python3.11/site-packages/alembic/util/pyfiles.py", line 113, in load_module_py
2024-03-24T20:27:47.806628435Z     spec.loader.exec_module(module)  # type: ignore
2024-03-24T20:27:47.806633335Z     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-03-24T20:27:47.806638135Z   File "<frozen importlib._bootstrap_external>", line 940, in exec_module
2024-03-24T20:27:47.806643436Z   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
2024-03-24T20:27:47.806648236Z   File "/pgadmin4/pgadmin/setup/../../migrations/env.py", line 95, in <module>
2024-03-24T20:27:47.806653336Z     run_migrations_online()
2024-03-24T20:27:47.807347049Z   File "/pgadmin4/pgadmin/setup/../../migrations/env.py", line 87, in run_migrations_online
2024-03-24T20:27:47.807355449Z     context.run_migrations()
2024-03-24T20:27:47.807360349Z   File "<string>", line 8, in run_migrations
2024-03-24T20:27:47.807365149Z   File "/venv/lib/python3.11/site-packages/alembic/runtime/environment.py", line 948, in run_migrations
2024-03-24T20:27:47.807370249Z     self.get_context().run_migrations(**kw)
2024-03-24T20:27:47.807374949Z   File "/venv/lib/python3.11/site-packages/alembic/runtime/migration.py", line 627, in run_migrations
2024-03-24T20:27:47.807381949Z     step.migration_fn(**kw)
2024-03-24T20:27:47.807386549Z   File "/pgadmin4/migrations/versions/fdc58d9bd449_.py", line 38, in upgrade
2024-03-24T20:27:47.807391249Z     email, password = user_info()
2024-03-24T20:27:47.807395650Z                       ^^^^^^^^^^^
2024-03-24T20:27:47.807401650Z   File "/pgadmin4/pgadmin/setup/user_info.py", line 75, in user_info
2024-03-24T20:27:47.807406250Z     email, p1 = user_info_server()
2024-03-24T20:27:47.807410850Z                 ^^^^^^^^^^^^^^^^^^
2024-03-24T20:27:47.807415450Z   File "/pgadmin4/pgadmin/setup/user_info.py", line 52, in user_info_server
2024-03-24T20:27:47.807420050Z     email = input(ENTER_EMAIL_ADDRESS)
2024-03-24T20:27:47.807424450Z             ^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-03-24T20:27:47.807428950Z EOFError: EOF when reading a line
2024-03-24T20:27:47.807433450Z 
```

I do have PGADMIN_DEFAULT_EMAIL and PGADMIN_DEFAULT_PASSWORD environment variables configured so unclear why this input is tried to be collected.

**Comment by khushboovashi** [comment]
Hi @MaartenUreel, please provide your docker configuration file.

**Comment by MaartenUreel** [comment]
I am using Pulumi to deploy this to Azure, it looks like this:

```python
    def _create_pgadmin_app(self):
        # The app itself
        app = azure.web.WebApp(
            f"app-pgadmin-{self._name}",
            resource_group_name=self._rg,
            server_farm_id=self._app_service_plan.id,
            virtual_network_subnet_id=self._app_subnet.id,
            identity=azure.web.ManagedServiceIdentityArgs(
                type=azure.web.ManagedServiceIdentityType.SYSTEM_ASSIGNED,
            ),
            https_only=True,
            site_config=azure.web.SiteConfigArgs(
                ftps_state=azure.web.FtpsState.DISABLED,
                linux_fx_version="DOCKER|dpage/pgadmin4",
                health_check_path="/misc/ping",
                app_settings=[
                    azure.web.NameValuePairArgs(name="DOCKER_REGISTRY_SERVER_URL", value="https://index.docker.io/v1"),
                    azure.web.NameValuePairArgs(name="DOCKER_ENABLE_CI", value="true"),
                    # azure.web.NameValuePairArgs(name="WEBSITE_HTTPLOGGING_RETENTION_DAYS", value="7"),
                    # pgAdmin settings
                    azure.web.NameValuePairArgs(name="PGADMIN_DISABLE_POSTFIX", value="true"),
                    azure.web.NameValuePairArgs(name="PGADMIN_DEFAULT_EMAIL", value="dbadmin@dbadmin.net"),
                    azure.web.NameValuePairArgs(name="PGADMIN_DEFAULT_PASSWORD", value="dbadmin"),
                ],
            ),
        )

        # Create a storage container for persistent data (SMB share)
        share = azure.storage.FileShare(
            f"share-pgadmin-{self._name}",
            resource_group_name=self._rg,
            account_name=self._storage_account.name,
            share_name="pgadmin",
        )

        # Mount the storage container
        azure.web.WebAppAzureStorageAccounts(
            f"app-pgadmin-mount-{self._name}",
            resource_group_name=self._rg,
            name=app.name,
            properties={
                "pgadmin-data": azure.web.AzureStorageInfoValueArgs(
                    account_name=self._storage_account.name,
                    access_key=self._get_storage_account_access_keys(self._storage_account)[0].value,
                    mount_path="/var/lib/pgadmin",
                    share_name=share.name,
                    type=azure.web.AzureStorageType.AZURE_FILES,
                )
            },
        )

        pulumi.export("pgadmin_url", app.default_host_name.apply(lambda host: f"https://{host}"))
```

This results in a Web App with these environment variables:
![image](https://github.com/pgadmin-org/pgadmin4/assets/1901942/b53bb16c-b894-49d8-a689-8adf2fdf4ac8)

The diagnostics tool of Azure also shows the existence of these variables:
![image](https://github.com/pgadmin-org/pgadmin4/assets/1901942/0fba9dfb-b4b5-4be4-bc02-f6a4fda327e2)

Intrestingly I have this deployed on two other Azure accounts and it worked with the same code.

I also tried sticking to an older version (8.0) but no difference.
