### ISSUE TITLE
psycopg2 not found

### ISSUE THREAD

**Issue by HeartConnector** [pgadmin-org/pgadmin4#7314]
'''
2024-03-25 10:46:54,608: INFO   pgadmin:        ########################################################
2024-03-25 10:46:54,608: INFO   pgadmin:        Starting pgAdmin 4 v8.4...
2024-03-25 10:46:54,608: INFO   pgadmin:        ########################################################
2024-03-25 10:46:54,609: DEBUG  pgadmin:        Python syspath: ['/pgadmin4', '/pgadmin4', '/usr/lib/python311.zip', '/usr/lib/python3.11', '/usr/lib/python3.11/lib-dynload', '/venv/lib/python3.11/site-packages', '/usr/lib/python3.11/site-packages']
Traceback (most recent call last):
  File "/pgadmin4/run_pgadmin.py", line 4, in <module>
    from pgAdmin4 import app
  File "/pgadmin4/pgAdmin4.py", line 103, in <module>
    app = create_app()
          ^^^^^^^^^^^^
  File "/pgadmin4/pgadmin/__init__.py", line 352, in create_app
    db.init_app(app)
  File "/venv/lib/python3.11/site-packages/flask_sqlalchemy/extension.py", line 374, in init_app
    engines[key] = self._make_engine(key, options, app)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/venv/lib/python3.11/site-packages/flask_sqlalchemy/extension.py", line 665, in _make_engine
    return sa.engine_from_config(options, prefix="")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/venv/lib/python3.11/site-packages/sqlalchemy/engine/create.py", line 809, in engine_from_config
    return create_engine(url, **options)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<string>", line 2, in create_engine
  File "/venv/lib/python3.11/site-packages/sqlalchemy/util/deprecations.py", line 281, in warned
    return fn(*args, **kwargs)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^
  File "/venv/lib/python3.11/site-packages/sqlalchemy/engine/create.py", line 599, in create_engine
    dbapi = dbapi_meth(**dbapi_args)
            ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/venv/lib/python3.11/site-packages/sqlalchemy/dialects/postgresql/psycopg2.py", line 690, in import_dbapi
    import psycopg2
ModuleNotFoundError: No module named 'psycopg2' '''

when add external postgres database CONFIG_DATABASE_URI =  "postgresql://postgres:password@postgres:5432/postgres"

Version [8.*]

**Comment by khushboovashi** [comment]
Hi @HeartConnector, try `"postgresql+psycopg://postgres:password@postgres:5432/postgres"`.

**Comment by HeartConnector** [comment]
sorry, all work, bad URI

**Comment by adityatoshniwal** [comment]
> Hi @HeartConnector, try `"postgresql+psycopg://postgres:password@postgres:5432/postgres"`.

I think pgAdmin converts `postgresql://` to `postgresql+psycopg://` if not in format. https://github.com/pgadmin-org/pgadmin4/blob/cc1ce09b739b8835a39825d9221863729b06510c/web/pgadmin/evaluate_config.py#L102
