### ISSUE TITLE
Unable to access post-login page

### ISSUE THREAD

**Issue by RampantDespair** [pgadmin-org/pgadmin4#7404]
**Describe the bug**

Upon entering the correct credentials in the login page, I am redirected to `https://pgadmin.mydomain.com/browser/` and am met with an empty page.

**To Reproduce**

Might be a setup issue, so N/A

**Expected behavior**

I expected to be able to access the pgadmin4 browser page.

**Error message**

Upon viewing my web browser's console I see a bunch of `404`s.
```
index.js:2562 
 GET https://pgadmin.mydomain.com/browser/constraints/static/img/constraints.svg?ver=80500 404 (Not Found)
index.js:2562 
 GET https://pgadmin.mydomain.com/browser/exclusion_constraint/static/img/coll-exclusion_constraint.svg?ver=80500 404 (Not Found)
index.js:2562 
 GET https://pgadmin.mydomain.com/browser/foreign_key/static/img/coll-foreign_key.svg?ver=80500 404 (Not Found)
index.js:2562 
 GET https://pgadmin.mydomain.com/browser/primary_key/static/img/coll-primary_key.svg?ver=80500 404 (Not Found)
index.js:2562 
 GET https://pgadmin.mydomain.com/browser/unique_constraint/static/img/coll-unique_constraint.svg?ver=80500 404 (Not Found)
content.js:364 getEmbedInfo
content.js:425 OEMBED https://pgadmin.mydomain.com/browser/
index.js:2562 
 GET https://pgadmin.mydomain.com/browser/dbms_job_scheduler/static/img/dbms_job_scheduler.svg?ver=80500 404 (Not Found)
index.js:2562 
 GET https://pgadmin.mydomain.com/browser/dbms_job/static/img/coll-dbms_job.svg?ver=80500 404 (Not Found)
index.js:2562 
 GET https://pgadmin.mydomain.com/browser/dbms_job/static/img/dbms_job.svg?ver=80500 404 (Not Found)
index.js:2562 
 GET https://pgadmin.mydomain.com/browser/dbms_program/static/img/coll-dbms_program.svg?ver=80500 404 (Not Found)
index.js:2562 
 GET https://pgadmin.mydomain.com/browser/dbms_program/static/img/dbms_program.svg?ver=80500 404 (Not Found)
index.js:2562 
 GET https://pgadmin.mydomain.com/browser/dbms_schedule/static/img/coll-dbms_schedule.svg?ver=80500 404 (Not Found)
index.js:2562 
 GET https://pgadmin.mydomain.com/browser/dbms_schedule/static/img/dbms_schedule.svg?ver=80500 404 (Not Found)
require.min.js?ver=80500:9 [Violation] 'load' handler took 555ms
vendor.others.js?ver=80500:109 
 GET https://pgadmin.mydomain.com/preferences/get_all 400 (Bad Request)
vendor.others.js?ver=80500:109 
 GET https://pgadmin.mydomain.com/browser/check_corrupted_db_file 400 (Bad Request)
vendor.others.js?ver=80500:109 
 GET https://pgadmin.mydomain.com/misc/bgprocess/ 400 (Bad Request)
app.bundle.js?ver=80500:1 
B {message: 'Request failed with status code 400', name: 'AxiosError', code: 'ERR_BAD_REQUEST', config: {…}, request: XMLHttpRequest, …}
app.bundle.js?ver=80500:1 Uncaught (in promise) TypeError: Cannot read properties of null (reading 'toString')
    at Object._bindWithHotkeys (app.bundle.js?ver=80500:1:534085)
    at app.bundle.js?ver=80500:1:533988
    at vendor.others.js?ver=80500:109:950490
    at _r (vendor.others.js?ver=80500:109:940094)
    at vendor.others.js?ver=80500:109:950295
    at Function.ys (vendor.others.js?ver=80500:109:962874)
    at Object.bindShortcuts (app.bundle.js?ver=80500:1:533948)
    at app.bundle.js?ver=80500:1:533398
    at vendor.others.js?ver=80500:109:2081227
    at Set.forEach (<anonymous>)
app.bundle.js?ver=80500:1 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'alert')
    at app.bundle.js?ver=80500:1:501559
```

As for the errors I get in the console server-side:
```
[2024-04-18 18:15:05 -0400] [1763] [INFO] Starting gunicorn 22.0.0
[2024-04-18 18:15:05 -0400] [1763] [INFO] Listening at: unix:/tmp/pgadmin4.sock (1763)
[2024-04-18 18:15:05 -0400] [1763] [INFO] Using worker: gthread
[2024-04-18 18:15:05 -0400] [1765] [INFO] Booting worker with pid: 1765
2024-04-18 18:15:20,567: ERROR  pgadmin:        400 Bad Request: The CSRF tokens do not match.
Traceback (most recent call last):
  File "/root/environments/my_env/lib/python3.8/site-packages/flask_wtf/csrf.py", line 261, in protect
    validate_csrf(self._get_csrf_token())
  File "/root/environments/my_env/lib/python3.8/site-packages/flask_wtf/csrf.py", line 115, in validate_csrf
    raise ValidationError("The CSRF tokens do not match.")
wtforms.validators.ValidationError: The CSRF tokens do not match.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/environments/my_env/lib/python3.8/site-packages/flask/app.py", line 1482, in full_dispatch_request
    rv = self.preprocess_request()
  File "/root/environments/my_env/lib/python3.8/site-packages/flask/app.py", line 1974, in preprocess_request
    rv = self.ensure_sync(before_func)()
  File "/root/environments/my_env/lib/python3.8/site-packages/flask_wtf/csrf.py", line 229, in csrf_protect
    self.protect()
  File "/root/environments/my_env/lib/python3.8/site-packages/flask_wtf/csrf.py", line 264, in protect
    self._error_response(e.args[0])
  File "/root/environments/my_env/lib/python3.8/site-packages/flask_wtf/csrf.py", line 307, in _error_response
    raise CSRFError(reason)
flask_wtf.csrf.CSRFError: 400 Bad Request: The CSRF tokens do not match.
2024-04-18 18:15:20,570: ERROR  pgadmin:        400 Bad Request: The CSRF tokens do not match.
Traceback (most recent call last):
  File "/root/environments/my_env/lib/python3.8/site-packages/flask_wtf/csrf.py", line 261, in protect
    validate_csrf(self._get_csrf_token())
  File "/root/environments/my_env/lib/python3.8/site-packages/flask_wtf/csrf.py", line 115, in validate_csrf
    raise ValidationError("The CSRF tokens do not match.")
wtforms.validators.ValidationError: The CSRF tokens do not match.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/environments/my_env/lib/python3.8/site-packages/flask/app.py", line 1482, in full_dispatch_request
    rv = self.preprocess_request()
  File "/root/environments/my_env/lib/python3.8/site-packages/flask/app.py", line 1974, in preprocess_request
    rv = self.ensure_sync(before_func)()
  File "/root/environments/my_env/lib/python3.8/site-packages/flask_wtf/csrf.py", line 229, in csrf_protect
    self.protect()
  File "/root/environments/my_env/lib/python3.8/site-packages/flask_wtf/csrf.py", line 264, in protect
    self._error_response(e.args[0])
  File "/root/environments/my_env/lib/python3.8/site-packages/flask_wtf/csrf.py", line 307, in _error_response
    raise CSRFError(reason)
flask_wtf.csrf.CSRFError: 400 Bad Request: The CSRF tokens do not match.
2024-04-18 18:15:20,575: ERROR  pgadmin:        400 Bad Request: The CSRF tokens do not match.
Traceback (most recent call last):
  File "/root/environments/my_env/lib/python3.8/site-packages/flask_wtf/csrf.py", line 261, in protect
    validate_csrf(self._get_csrf_token())
  File "/root/environments/my_env/lib/python3.8/site-packages/flask_wtf/csrf.py", line 115, in validate_csrf
    raise ValidationError("The CSRF tokens do not match.")
wtforms.validators.ValidationError: The CSRF tokens do not match.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/environments/my_env/lib/python3.8/site-packages/flask/app.py", line 1482, in full_dispatch_request
    rv = self.preprocess_request()
  File "/root/environments/my_env/lib/python3.8/site-packages/flask/app.py", line 1974, in preprocess_request
    rv = self.ensure_sync(before_func)()
  File "/root/environments/my_env/lib/python3.8/site-packages/flask_wtf/csrf.py", line 229, in csrf_protect
    self.protect()
  File "/root/environments/my_env/lib/python3.8/site-packages/flask_wtf/csrf.py", line 264, in protect
    self._error_response(e.args[0])
  File "/root/environments/my_env/lib/python3.8/site-packages/flask_wtf/csrf.py", line 307, in _error_response
    raise CSRFError(reason)
flask_wtf.csrf.CSRFError: 400 Bad Request: The CSRF tokens do not match.
```

**Screenshots**

N/A

**Desktop (please complete the following information):**

 - OS: Ubuntu 
 - Version: 20.04.6 LTS (Focal Fossa)
 - Mode: Server
 - Browser (if running in server mode): Chrome
 - Package type: Python

**Additional context**

I'm running pgadmin4 `8.5` through a python environment on my ubuntu VPS.
I'm using the exact setup as the one shown [here](https://www.digitalocean.com/community/tutorials/how-to-install-and-configure-pgadmin-4-in-server-mode-on-ubuntu-22-04).
I've tried different browsers and clearing my cookies to no avail.

My Nginx config:
```
ssl_certificate     /etc/letsencrypt/live/mydomain.com/cert.pem;
ssl_certificate_key /etc/letsencrypt/live/mydomain.com/privkey.pem;

server {
  listen 80;
  listen [::]:80;

  listen 443 ssl;
  listen [::]:443 ssl;

  server_name pgadmin.mydomain.com;

  access_log /var/log/nginx/pgadmin.mydomain.com/access.log;
  error_log  /var/log/nginx/pgadmin.mydomain.com/error.log;

  location / {
    proxy_pass http://unix:/tmp/pgadmin4.sock;
    include proxy_params;
  }
}
```

**Comment by adityatoshniwal** [comment]
Did you check the docs here - https://www.pgadmin.org/docs/pgadmin4/8.5/container_deployment.html#https-via-nginx?

**Comment by khushboovashi** [comment]
@RampantDespair, as per your logs, the path is /root/environments/my_env/lib/python3.8/.... Are you sure you have set the right permission? From which user are you running the application?

**Comment by ChristophKe** [comment]
Same problem here.

**Comment by RampantDespair** [comment]
@adityatoshniwal @khushboovashi 
Apologies for the delay, I did a clean and fresh install and everything works as intended now.
I think it's because I got messed up with the other user creation in the tutorial; I just went with straight root and everything works fine now.
