### ISSUE TITLE
Password reset fails with 'ResetPasswordForm' object has no attribute 'user'

### ISSUE THREAD

**Issue by thaDude** [pgadmin-org/pgadmin4#7500]
**Describe the bug**
When submitting the new password and password confirmation to /browser/reset_password the server responds with 500, the password is not reset.

**To Reproduce**

```
docker run -p 8000:80 \
    -e 'PGADMIN_DEFAULT_EMAIL=user@domain.com' \                                 
    -e 'PGADMIN_DEFAULT_PASSWORD=SuperSecret' \
    -d dpage/pgadmin4:8.6 
```

1. Login with admin user and create a normal user.
1. Open [/browser/reset_password](http://localhost:8000/browser/reset_password).
2. Enter email address of user that was created.
3. Receive mail and click on link.
4. Enter new password/confirm then submit form.

**Expected behavior**
I expect the password to be reset without error.

**Error message**
```
{
  "success": 0,
  "errormsg": "'ResetPasswordForm' object has no attribute 'user'",
  "info": "",
  "result": null,
  "data": null
}
```

**Desktop (please complete the following information):**
 - OS: macOS 14.2.1 (23C71)
 - Version: 8.6
 - Mode: Server
 - Browser (if running in server mode): Chrome
 - Package type: Container

**Additional context**

Some more output from the server logs:
```
2024-05-22 17:42:09,594: ERROR  pgadmin:        'ResetPasswordForm' object has no attribute 'user'
Traceback (most recent call last):
  File "/venv/lib/python3.11/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/venv/lib/python3.11/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/venv/lib/python3.11/site-packages/flask_security/decorators.py", line 645, in wrapper
    return current_app.ensure_sync(f)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/pgadmin4/pgadmin/browser/__init__.py", line 1111, in reset_password
  File "/venv/lib/python3.11/site-packages/flask_wtf/form.py", line 86, in validate_on_submit
    return self.is_submitted() and self.validate(extra_validators=extra_validators)
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/venv/lib/python3.11/site-packages/flask_security/forms.py", line 717, in validate
    self.password.data, False, user=self.user
                                    ^^^^^^^^^
AttributeError: 'ResetPasswordForm' object has no attribute 'user'
```

Thank you!

/David

**Comment by RohitBhati8269** [comment]
Tested on snapshot build: 2024-05-20
OS: macOS
Version: 8.6
Mode: Server/Desktop
Browser: Chrome

Issue fixed.
