### ISSUE TITLE
Docker v8.7 fails to start

### ISSUE THREAD

**Issue by mmomjian** [pgadmin-org/pgadmin4#7520]
I am running pgAdmin on Debian 12, Docker 

Since 8.7 Docker image, I get the following in the logs, and pgAdmin fails to start. Changing the docker back to `image: dpage/pgadmin4:8.6` fixes the problem. I was on `image: dpage/pgadmin4:latest`

```
[2024-05-30 21:54:17 -0400] [118] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/venv/lib/python3.12/site-packages/gunicorn/arbiter.py", line 589, in spawn_worker
    worker.init_process()
  File "/venv/lib/python3.12/site-packages/gunicorn/workers/gthread.py", line 92, in init_process
    super().init_process()
  File "/venv/lib/python3.12/site-packages/gunicorn/workers/base.py", line 142, in init_process
    self.run()
  File "/venv/lib/python3.12/site-packages/gunicorn/workers/gthread.py", line 203, in run
    callback(key.fileobj)
  File "/venv/lib/python3.12/site-packages/gunicorn/workers/gthread.py", line 124, in accept
    self.enqueue_req(conn)
  File "/venv/lib/python3.12/site-packages/gunicorn/workers/gthread.py", line 112, in enqueue_req
    conn.init()
  File "/venv/lib/python3.12/site-packages/gunicorn/workers/gthread.py", line 52, in init
    self.sock = ssl.wrap_socket(self.sock, server_side=True,
                ^^^^^^^^^^^^^^^
AttributeError: module 'ssl' has no attribute 'wrap_socket'
[2024-05-30 21:54:17 -0400] [118] [INFO] Worker exiting (pid: 118)
[2024-05-30 21:54:17 -0400] [146] [INFO] Booting worker with pid: 146
pgAdmin 4 - Application Initialisation
======================================

[2024-05-30 21:54:49 -0400] [146] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/venv/lib/python3.12/site-packages/gunicorn/arbiter.py", line 589, in spawn_worker
    worker.init_process()
  File "/venv/lib/python3.12/site-packages/gunicorn/workers/gthread.py", line 92, in init_process
    super().init_process()
  File "/venv/lib/python3.12/site-packages/gunicorn/workers/base.py", line 142, in init_process
    self.run()
  File "/venv/lib/python3.12/site-packages/gunicorn/workers/gthread.py", line 203, in run
    callback(key.fileobj)
  File "/venv/lib/python3.12/site-packages/gunicorn/workers/gthread.py", line 124, in accept
    self.enqueue_req(conn)
  File "/venv/lib/python3.12/site-packages/gunicorn/workers/gthread.py", line 112, in enqueue_req
    conn.init()
  File "/venv/lib/python3.12/site-packages/gunicorn/workers/gthread.py", line 52, in init
    self.sock = ssl.wrap_socket(self.sock, server_side=True,
                ^^^^^^^^^^^^^^^
AttributeError: module 'ssl' has no attribute 'wrap_socket'
[2024-05-30 21:54:49 -0400] [146] [INFO] Worker exiting (pid: 146)
[2024-05-30 21:54:50 -0400] [181] [INFO] Booting worker with pid: 181
pgAdmin 4 - Application Initialisation
======================================

[2024-05-30 21:55:49 -0400] [181] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/venv/lib/python3.12/site-packages/gunicorn/arbiter.py", line 589, in spawn_worker
    worker.init_process()
  File "/venv/lib/python3.12/site-packages/gunicorn/workers/gthread.py", line 92, in init_process
    super().init_process()
  File "/venv/lib/python3.12/site-packages/gunicorn/workers/base.py", line 142, in init_process
    self.run()
  File "/venv/lib/python3.12/site-packages/gunicorn/workers/gthread.py", line 203, in run
    callback(key.fileobj)
  File "/venv/lib/python3.12/site-packages/gunicorn/workers/gthread.py", line 124, in accept
    self.enqueue_req(conn)
  File "/venv/lib/python3.12/site-packages/gunicorn/workers/gthread.py", line 112, in enqueue_req
    conn.init()
  File "/venv/lib/python3.12/site-packages/gunicorn/workers/gthread.py", line 52, in init
    self.sock = ssl.wrap_socket(self.sock, server_side=True,
                ^^^^^^^^^^^^^^^
AttributeError: module 'ssl' has no attribute 'wrap_socket'
[2024-05-30 21:55:49 -0400] [181] [INFO] Worker exiting (pid: 181)
[2024-05-30 21:55:50 -0400] [217] [INFO] Booting worker with pid: 217
pgAdmin 4 - Application Initialisation
======================================
```

System info:

```
sudo docker version
Client: Docker Engine - Community
 Version:           26.1.3
 API version:       1.45
 Go version:        go1.21.10
 Git commit:        b72abbb
 Built:             Thu May 16 08:33:42 2024
 OS/Arch:           linux/amd64
 Context:           default

Server: Docker Engine - Community
 Engine:
  Version:          26.1.3
  API version:      1.45 (minimum version 1.24)
  Go version:       go1.21.10
  Git commit:       8e96db1
  Built:            Thu May 16 08:33:42 2024
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.32
  GitCommit:        8b3b7ca2e5ce38e8f31a34f35b2b68ceb8470d89
 runc:
  Version:          1.1.12
  GitCommit:        v1.1.12-0-g51d5e94
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

Image: 

```
dpage/pgadmin4                                   latest        c3d1e82c1e18   2 days ago      485MB
```

**Comment by yogeshmahajan-1903** [comment]
@mmomjian 
Are you using any SSL enabled container? Can you please provide your docker command?

**Comment by MHenn1g** [comment]
@yogeshmahajan-1903 yes, this happens in the context of utilizing ssl.

Without ssl it works:
```
  docker run \
  -p 80:80 \
  -e "PGADMIN_DEFAULT_EMAIL=$PGADMIN_DEFAULT_EMAIL" \
  -e "PGADMIN_DEFAULT_PASSWORD=$PGADMIN_DEFAULT_PASSWORD" \
  --name=pgadmin \
  --hostname=pgadmin \
  -d dpage/pgadmin4:8.7
```
  
But if you enable ssl like this, it crashes with the error mentioned by @mmomjian :
```
  docker run \
  -p 443:443 \
  -e "PGADMIN_DEFAULT_EMAIL=$PGADMIN_DEFAULT_EMAIL" \
  -e "PGADMIN_DEFAULT_PASSWORD=$PGADMIN_DEFAULT_PASSWORD" \
  -e "PGADMIN_ENABLE_TLS=True" \
  -v $(pwd)/certs/cert.pem:/certs/server.cert \
  -v $(pwd)/certs/key.pem:/certs/server.key \
  --name=pgadmin \
  --hostname=pgadmin \
  -d dpage/pgadmin4:8.7
```

**Comment by thokich** [comment]
Hello, I have the same error

**Comment by akshay-joshi** [comment]
All,

We have fixed the issue and planning a release of v8.8 this Thursday.

**Comment by khushboovashi** [comment]
All,

Before release, you can test the snapshot (dpage/pgadmin4:snapshot) to verify the fix.

**Comment by yogeshmahajan-1903** [comment]
This is working fine on candidate build
