### ISSUE TITLE
OAUTH2 with Authelia not working

### ISSUE THREAD

**Issue by belangp** [pgadmin-org/pgadmin4#7541]
**Describe the bug**

When integrating with Authelia, I receive this error upon successful authentication:

{"success":0,"errormsg":"'NoneType' object has no attribute 'is_active'","info":"","result":null,"data":null}

Followed guide from Authelia’s site: https://www.authelia.com/integration/openid-connect/pgadmin/

**To Reproduce**

Enable the OAUTH2 login using Authelia (haven’t checked is same behaviour with other auth apps)
Try logging in with OAUTH2

**Expected behavior**

Login should work.

**Error message**

2024-06-06 16:53:32,735: ERROR  pgadmin:        'NoneType' object has no attribute 'is_active'
Traceback (most recent call last):
  File "/venv/lib/python3.12/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/venv/lib/python3.12/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/pgadmin4/pgadmin/authenticate/oauth2.py", line 56, in oauth_authorize
    status, msg = auth_obj.login()
                  ^^^^^^^^^^^^^^^^
  File "/pgadmin4/pgadmin/authenticate/__init__.py", line 299, in login
    status, msg = self.source.login(self.form)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/pgadmin4/pgadmin/authenticate/oauth2.py", line 206, in login
    return login_user(user), None
           ^^^^^^^^^^^^^^^^
  File "/venv/lib/python3.12/site-packages/flask_security/utils.py", line 183, in login_user
    if not _login_user(user, remember):  # pragma: no cover
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/venv/lib/python3.12/site-packages/flask_login/utils.py", line 180, in login_user
    if not force and not user.is_active:
                         ^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'is_active'
[06/Jun/2024:16:53:32 -0300] "GET /oauth2/authorize?code=authelia_ac_uAOLSZs_CSFfaHA4uurHAZxr5FH9mW1WoxPdYluMs4Y.rKIpRTy2EcmQ6L0XOw6fsXMHtsh0VOdl99b0M-pAWOc&iss=https%3A%2F%2Fauth.redacted.server&scope=openid+email+profile+groups&state=maEl2NvPU5gyugmHUpyyhnai7Ri52U HTTP/1.1" 500 109 "https://auth.redacted.server/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.5 Safari/605.1.15"

**Desktop (please complete the following information):**
 - OS: iPadOS 
 - Version: 17.5.1
 - Mode: Server
 - Browser (if running in server mode): Safari
 - Package type: Docker container

**Additional context**
PgAdmin config_local.py:

UTHENTICATION_SOURCES = ['oauth2', 'internal']
OAUTH2_AUTO_CREATE_USER = False
OAUTH2_CONFIG = [{
'OAUTH2_NAME': 'Authelia',
'OAUTH2_DISPLAY_NAME': 'Authelia',
'OAUTH2_CLIENT_ID': 'pgadmin',
'OAUTH2_CLIENT_SECRET': 'secret',
'OAUTH2_API_BASE_URL': 'https://auth.redacted.server',
'OAUTH2_AUTHORIZATION_URL': 'https://auth.redacted.server/api/oidc/authorization',
'OAUTH2_TOKEN_URL': 'https://auth.redacted.server/api/oidc/token',
'OAUTH2_USERINFO_ENDPOINT': 'https://auth.redacted.server/api/oidc/userinfo',
'OAUTH2_SERVER_METADATA_URL': 'https://auth.redacted.server/.well-known/openid-configuration',
'OAUTH2_SCOPE': 'openid email profile groups',
'OAUTH2_USERNAME_CLAIM': 'email',
'OAUTH2_ICON': 'fa-right-to-bracket',
'OAUTH2_BUTTON_COLOR': 'blue'
}]

Authelia configuration:

 - client_id: 'pgadmin'
        client_name: 'pgAdmin'
   client_secret: 'secret'
 public: false
 authorization_policy: 'two_factor'
 redirect_uris:
   - 'https://pg.redacted.server/oauth2/authorize'
        scopes:
   - 'openid'
 - 'profile'
 - 'email'
     - 'groups'
    userinfo_signed_response_alg: 'none'
  token_endpoint_auth_method: 'client_secret_basic'

**Comment by belangp** [comment]
OAUTH2_AUTO_CREATE_USER set to False was triggering this error
