### ISSUE TITLE
cannot start pgAdmin container with external database for pgAdmin user settings

### ISSUE THREAD

**Issue by aremund** [pgadmin-org/pgadmin4#7556]
**Describe the bug**

I configured pgAdmin to use PostgreSQL instead of SQLite for user settings. Now, it cannot start up anymore.

**To Reproduce**

1. create database `pgadmindb`
2. create schema `pgadmin`
3. deploy pgAdmin with the following `deployment.yaml` file

```
kind: Deployment
apiVersion: apps/v1
metadata:
  name: pgadmin
spec:
  selector:
   matchLabels:
    app: pgadmin
  replicas: 1
  template:
    metadata:
      labels:
        app: pgadmin
    spec:
      containers:
      - name: pgadmin4
        image: dpage/pgadmin4:8.8
        imagePullPolicy: IfNotPresent
        env:
        - name: PGADMIN_DEFAULT_EMAIL
          value: test@test.com
        - name: PGADMIN_DEFAULT_PASSWORD
          value: testsecret
        - name: PGADMIN_CONFIG_CONFIG_DATABASE_URI
          value: "'postgresql://pgadmin:secret@db-host:5432/pgadmindb?options=-csearch_path=pgadmin'"
```

**Expected behavior**

pgAdmin should successfully create the tables in the empty database and then start.

**Error message**

On the database `pgadmindb`
```
2024-06-07 19:28:14.142 CEST [2133648] pgadmin@pgadmindb ERROR:  relation "version" does not exist at character 75
2024-06-07 19:28:14.142 CEST [2133648] pgadmin@pgadmindb STATEMENT:  SELECT version.name AS version_name, version.value AS version_value
        FROM version
        WHERE version.name = $1::VARCHAR
         LIMIT $2::INTEGER
2024-06-07 19:28:14.550 CEST [2133648] pgadmin@pgadmindb LOG:  could not receive data from client: Connection reset by peer
```

In the Container-Log:
```
2024-06-07 17:27:42,133: INFO	pgadmin:	########################################################
2024-06-07 17:27:42,133: INFO	pgadmin:	Starting pgAdmin 4 v8.8...
2024-06-07 17:27:42,133: INFO	pgadmin:	########################################################
2024-06-07 17:27:42,133: DEBUG	pgadmin:	Python syspath: ['/pgadmin4', '/venv/bin', '/pgadmin4', '/usr/lib/python312.zip', '/usr/lib/python3.12', '/usr/lib/python3.12/lib-dynload', '/venv/lib/python3.12/site-packages', '/usr/lib/python3.12/site-packages']
NOTE: Configuring authentication for SERVER mode.

Enter the email address and password to use for the initial pgAdmin user account:

[2024-06-07 17:27:42 +0000] [90] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/venv/lib/python3.12/site-packages/gunicorn/arbiter.py", line 609, in spawn_worker
    worker.init_process()
  File "/venv/lib/python3.12/site-packages/gunicorn/workers/gthread.py", line 95, in init_process
    super().init_process()
  File "/venv/lib/python3.12/site-packages/gunicorn/workers/base.py", line 134, in init_process
    self.load_wsgi()
  File "/venv/lib/python3.12/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
                ^^^^^^^^^^^^^^^
  File "/venv/lib/python3.12/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
                    ^^^^^^^^^^^
  File "/venv/lib/python3.12/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
           ^^^^^^^^^^^^^^^^^^^
  File "/venv/lib/python3.12/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/venv/lib/python3.12/site-packages/gunicorn/util.py", line 371, in import_app
    mod = importlib.import_module(module)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/pgadmin4/run_pgadmin.py", line 4, in <module>
    from pgAdmin4 import app
  File "/pgadmin4/pgAdmin4.py", line 103, in <module>
    app = create_app()
          ^^^^^^^^^^^^
  File "/pgadmin4/pgadmin/__init__.py", line 471, in create_app
    run_migration_for_others()
  File "/pgadmin4/pgadmin/__init__.py", line 456, in run_migration_for_others
    db_upgrade(app)
  File "/pgadmin4/pgadmin/setup/db_upgrade.py", line 25, in db_upgrade
    flask_migrate.upgrade(migration_folder)
  File "/venv/lib/python3.12/site-packages/flask_migrate/__init__.py", line 111, in wrapped
    f(*args, **kwargs)
  File "/venv/lib/python3.12/site-packages/flask_migrate/__init__.py", line 200, in upgrade
    command.upgrade(config, revision, sql=sql, tag=tag)
  File "/venv/lib/python3.12/site-packages/alembic/command.py", line 403, in upgrade
    script.run_env()
  File "/venv/lib/python3.12/site-packages/alembic/script/base.py", line 583, in run_env
    util.load_python_file(self.dir, "env.py")
  File "/venv/lib/python3.12/site-packages/alembic/util/pyfiles.py", line 95, in load_python_file
    module = load_module_py(module_id, path)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/venv/lib/python3.12/site-packages/alembic/util/pyfiles.py", line 113, in load_module_py
    spec.loader.exec_module(module)  # type: ignore
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/pgadmin4/pgadmin/setup/../../migrations/env.py", line 95, in <module>
    run_migrations_online()
  File "/pgadmin4/pgadmin/setup/../../migrations/env.py", line 87, in run_migrations_online
    context.run_migrations()
  File "<string>", line 8, in run_migrations
  File "/venv/lib/python3.12/site-packages/alembic/runtime/environment.py", line 948, in run_migrations
    self.get_context().run_migrations(**kw)
  File "/venv/lib/python3.12/site-packages/alembic/runtime/migration.py", line 627, in run_migrations
    step.migration_fn(**kw)
  File "/pgadmin4/migrations/versions/fdc58d9bd449_.py", line 38, in upgrade
    email, password = user_info()
                      ^^^^^^^^^^^
  File "/pgadmin4/pgadmin/setup/user_info.py", line 75, in user_info
    email, p1 = user_info_server()
                ^^^^^^^^^^^^^^^^^^
  File "/pgadmin4/pgadmin/setup/user_info.py", line 52, in user_info_server
    email = input(ENTER_EMAIL_ADDRESS)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^
EOFError: EOF when reading a line
[2024-06-07 17:27:42 +0000] [90] [INFO] Worker exiting (pid: 90)
[2024-06-07 17:27:42 +0000] [1] [ERROR] Worker (pid:90) exited with code 3
[2024-06-07 17:27:42 +0000] [1] [ERROR] Shutting down: Master
[2024-06-07 17:27:42 +0000] [1] [ERROR] Reason: Worker failed to boot.
Email address: 
```

**Comment by yogeshmahajan-1903** [comment]
@aremund 
Are you updating(specifically from 8.7 to 8.8) existing pgadmin app or doing fresh install?

**Comment by aremund** [comment]
@yogeshmahajan-1903 I wanted to migrate to an external database for our existing installation (8.8) and added the PGADMIN_CONFIG_CONFIG_DATABASE_URI for our existing Installation.
Since this did not work, I tried it with a new installation and reported the ticket based on a new installation.
Yes, I use a secret for PGADMIN_DEFAULT_EMAIL, PGADMIN_DEFAULT_PASSWORD.

**Comment by yogeshmahajan-1903** [comment]
@aremund 
Can you please check you secrets, I am doubting error is because empty secrets. Or May be just try directly passing PGADMIN_DEFAULT_EMAIL, PGADMIN_DEFAULT_PASSWORD just for test. I am not able to reproduce the issue , but I do not use secrets.

**Comment by mitchellkellett** [comment]
I had this issue too when I tried a fresh install of 8.8. I ended up installing 8.6. Then migrating to 8.8. 

Mine didn't want to create anything, from memory it wanted to start the db migrations with an update to preferences.

**Comment by sdsys-ch** [comment]
I ran into the same issue today on a fresh install with 8.8. Environment was

Docker version 25.0.1, build 29cf629
Docker Compose version v2.24.2

Environment via docker compose `env_file: .env.pgadmin` statement:

```
PGADMIN_DEFAULT_EMAIL=--redacted--
PGADMIN_DEFAULT_PASSWORD=--redacted--
PGADMIN_DISABLE_POSTFIX=True
PGADMIN_CONFIG_APP_NAME="'... PGAdmin'"
PGADMIN_CONFIG_LANGUAGES="{'en': 'English', 'de': 'German', 'fr': 'French'}"
PGADMIN_CONFIG_DEFAULT_SERVER_PORT=80
PGADMIN_CONFIG_LOGIN_BANNER="'...'"
PGADMIN_CONFIG_DEBUG=False
PGADMIN_CONFIG_CONFIG_DATABASE_URI="'postgresql://pgadm_usr:--redacted--@db_srv:5432/pgadmin'"
PGADMIN_CONFIG_MAIL_SERVER="'...'"
PGADMIN_CONFIG_MAIL_PORT=587
PGADMIN_CONFIG_MAIL_SSL=False
PGADMIN_CONFIG_MAIL_TLS=True
PGADMIN_CONFIG_MAIL_USERNAME="'...'"
PGADMIN_CONFIG_MAIL_PASSWORD="'...'"
PGADMIN_CONFIG_SECURITY_EMAIL_SENDER="'...'"
PGADMIN_CONFIG_SESSION_EXPIRATION_TIME=5
```

Workaround by @mitchellkellett did the trick here as well. Thanks @mitchellkellett !

**Comment by pravesh-sharma** [comment]
Issue fixed. Verified on docker snapshot image.

**Comment by maximemoreillon** [comment]
I am still getting this error with `dpage/pgadmin4:8.9`

**Comment by n0099** [comment]
It's still reproducible with the latest `8.14` docker image.

**Comment by khushboovashi** [comment]
> It's still reproducible with the latest `8.14` docker image.

Please share the error log.

**Comment by borutnet** [comment]
I'm pretty sure it's the same error as above. By quickly checking the code, maybe variable naming is the issue: https://github.com/pgadmin-org/pgadmin4/blob/90cdeeff0abbff603f8c45360135a54e9f6b166a/web/pgadmin/setup/user_info.py#L38

Linked line checks PGADMIN_SETUP_EMAIL and PGADMIN_SETUP_PASSWORD, env is PGADMIN_DEFAULT_EMAIL and PGADMIN_DEFAULT_PASSWORD.

**Comment by borutnet** [comment]
I've added PGADMIN_SETUP_EMAIL and PGADMIN_SETUP_PASSWORD to environmental variables and I could initialize  it worked.

`kind: Deployment
apiVersion: apps/v1
metadata:
  name: pgadmin
spec:
  selector:
   matchLabels:
    app: pgadmin
  replicas: 1
  template:
    metadata:
      labels:
        app: pgadmin
    spec:
      containers:
      - name: pgadmin4
        image: dpage/pgadmin4:latest
        env:
        - name: PGADMIN_DEFAULT_EMAIL
          value: test@test.com
        - name: PGADMIN_DEFAULT_PASSWORD
          value: testsecret
        - name: PGADMIN_SETUP_EMAIL
          value: test@test.com
        - name: PGADMIN_SETUP_PASSWORD
          value: testsecret     
        - name: PGADMIN_CONFIG_CONFIG_DATABASE_URI
          value: "'postgresql://pgadmin:secret@db-host:5432/pgadmindb?options=-csearch_path=pgadmin'"`

**Comment by MilanSavaliya** [comment]
Solution by @borutnet is working for me. Thanks @borutnet

**Comment by havedill** [comment]
I'm getting this same error on the latest elestio docker image

```
2025-06-06T13:40:58.221490460Z During handling of the above exception, another exception occurred:
2025-06-06T13:40:58.221492674Z 
2025-06-06T13:40:58.221494723Z Traceback (most recent call last):
2025-06-06T13:40:58.221496884Z   File "/pgadmin4/pgadmin/__init__.py", line 376, in backup_db_file
2025-06-06T13:40:58.221499227Z     db_upgrade(app)
2025-06-06T13:40:58.221501344Z   File "/pgadmin4/pgadmin/setup/db_upgrade.py", line 25, in db_upgrade
2025-06-06T13:40:58.221503606Z     flask_migrate.upgrade(migration_folder)
2025-06-06T13:40:58.221505848Z   File "/venv/lib/python3.12/site-packages/flask_migrate/__init__.py", line 111, in wrapped
2025-06-06T13:40:58.221508258Z     f(*args, **kwargs)
2025-06-06T13:40:58.221510451Z   File "/venv/lib/python3.12/site-packages/flask_migrate/__init__.py", line 200, in upgrade
2025-06-06T13:40:58.221512701Z     command.upgrade(config, revision, sql=sql, tag=tag)
2025-06-06T13:40:58.221514865Z   File "/venv/lib/python3.12/site-packages/alembic/command.py", line 483, in upgrade
2025-06-06T13:40:58.221517086Z     script.run_env()
2025-06-06T13:40:58.221519205Z   File "/venv/lib/python3.12/site-packages/alembic/script/base.py", line 551, in run_env
2025-06-06T13:40:58.221521446Z     util.load_python_file(self.dir, "env.py")
2025-06-06T13:40:58.221523768Z   File "/venv/lib/python3.12/site-packages/alembic/util/pyfiles.py", line 114, in load_python_file
2025-06-06T13:40:58.221526033Z     module = load_module_py(module_id, path)
2025-06-06T13:40:58.221528252Z              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2025-06-06T13:40:58.221531691Z   File "/venv/lib/python3.12/site-packages/alembic/util/pyfiles.py", line 134, in load_module_py
2025-06-06T13:40:58.221534129Z     spec.loader.exec_module(module)  # type: ignore
2025-06-06T13:40:58.221536380Z     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2025-06-06T13:40:58.221538678Z   File "<frozen importlib._bootstrap_external>", line 999, in exec_module
2025-06-06T13:40:58.221540947Z   File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
2025-06-06T13:40:58.221543270Z   File "/pgadmin4/pgadmin/setup/../../migrations/env.py", line 95, in <module>
2025-06-06T13:40:58.221545563Z     run_migrations_online()
2025-06-06T13:40:58.221547703Z   File "/pgadmin4/pgadmin/setup/../../migrations/env.py", line 87, in run_migrations_online
2025-06-06T13:40:58.221549965Z     context.run_migrations()
2025-06-06T13:40:58.221552103Z   File "<string>", line 8, in run_migrations
2025-06-06T13:40:58.221554349Z   File "/venv/lib/python3.12/site-packages/alembic/runtime/environment.py", line 946, in run_migrations
2025-06-06T13:40:58.221556816Z     self.get_context().run_migrations(**kw)
2025-06-06T13:40:58.221558996Z   File "/venv/lib/python3.12/site-packages/alembic/runtime/migration.py", line 623, in run_migrations
2025-06-06T13:40:58.221561260Z     step.migration_fn(**kw)
2025-06-06T13:40:58.221563357Z   File "/pgadmin4/migrations/versions/fdc58d9bd449_.py", line 38, in upgrade
2025-06-06T13:40:58.221565577Z     email, password = user_info()
2025-06-06T13:40:58.221576241Z                       ^^^^^^^^^^^
2025-06-06T13:40:58.221580052Z   File "/pgadmin4/pgadmin/setup/user_info.py", line 75, in user_info
2025-06-06T13:40:58.221582322Z     email, p1 = user_info_server()
2025-06-06T13:40:58.221584657Z                 ^^^^^^^^^^^^^^^^^^
2025-06-06T13:40:58.221586901Z   File "/pgadmin4/pgadmin/setup/user_info.py", line 52, in user_info_server
2025-06-06T13:40:58.221589142Z     email = input(ENTER_EMAIL_ADDRESS)
2025-06-06T13:40:58.221591293Z             ^^^^^^^^^^^^^^^^^^^^^^^^^^
2025-06-06T13:40:58.221593424Z EOFError: EOF when reading a line
2025-06-06T13:40:58.221595573Z 
2025-06-06T13:40:58.221597644Z During handling of the above exception, another exception occurred:
2025-06-06T13:40:58.221599848Z 
2025-06-06T13:40:58.221601921Z Traceback (most recent call last):
2025-06-06T13:40:58.221604078Z   File "/venv/lib/python3.12/site-packages/gunicorn/arbiter.py", line 608, in spawn_worker
2025-06-06T13:40:58.221606356Z     worker.init_process()
2025-06-06T13:40:58.221608495Z   File "/venv/lib/python3.12/site-packages/gunicorn/workers/gthread.py", line 94, in init_process
2025-06-06T13:40:58.221610769Z     super().init_process()
2025-06-06T13:40:58.221614398Z   File "/venv/lib/python3.12/site-packages/gunicorn/workers/base.py", line 135, in init_process
2025-06-06T13:40:58.221616798Z     self.load_wsgi()
2025-06-06T13:40:58.221618984Z   File "/venv/lib/python3.12/site-packages/gunicorn/workers/base.py", line 147, in load_wsgi
2025-06-06T13:40:58.221621361Z     self.wsgi = self.app.wsgi()
2025-06-06T13:40:58.221623524Z                 ^^^^^^^^^^^^^^^
2025-06-06T13:40:58.221625654Z   File "/venv/lib/python3.12/site-packages/gunicorn/app/base.py", line 66, in wsgi
2025-06-06T13:40:58.221627983Z     self.callable = self.load()
2025-06-06T13:40:58.221630116Z                     ^^^^^^^^^^^
2025-06-06T13:40:58.221632243Z   File "/venv/lib/python3.12/site-packages/gunicorn/app/wsgiapp.py", line 57, in load
2025-06-06T13:40:58.221634476Z     return self.load_wsgiapp()
2025-06-06T13:40:58.221636676Z            ^^^^^^^^^^^^^^^^^^^
2025-06-06T13:40:58.221638824Z   File "/venv/lib/python3.12/site-packages/gunicorn/app/wsgiapp.py", line 47, in load_wsgiapp
2025-06-06T13:40:58.221641109Z     return util.import_app(self.app_uri)
2025-06-06T13:40:58.221643365Z            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2025-06-06T13:40:58.221645526Z   File "/venv/lib/python3.12/site-packages/gunicorn/util.py", line 370, in import_app
2025-06-06T13:40:58.221647768Z     mod = importlib.import_module(module)
2025-06-06T13:40:58.221649928Z           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2025-06-06T13:40:58.221652070Z   File "/usr/lib/python3.12/importlib/__init__.py", line 90, in import_module
2025-06-06T13:40:58.221654313Z     return _bootstrap._gcd_import(name[level:], package, level)
2025-06-06T13:40:58.221657003Z            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2025-06-06T13:40:58.221659282Z   File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
2025-06-06T13:40:58.221661575Z   File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
2025-06-06T13:40:58.221663823Z   File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
2025-06-06T13:40:58.221666104Z   File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
2025-06-06T13:40:58.221668349Z   File "<frozen importlib._bootstrap_external>", line 999, in exec_module
2025-06-06T13:40:58.221670610Z   File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
2025-06-06T13:40:58.221672877Z   File "/pgadmin4/run_pgadmin.py", line 4, in <module>
2025-06-06T13:40:58.221675322Z     from pgAdmin4 import app
2025-06-06T13:40:58.221677482Z   File "/pgadmin4/pgAdmin4.py", line 93, in <module>
2025-06-06T13:40:58.221679758Z     app = create_app()
2025-06-06T13:40:58.221681881Z           ^^^^^^^^^^^^
2025-06-06T13:40:58.221684015Z   File "/pgadmin4/pgadmin/__init__.py", line 478, in create_app
2025-06-06T13:40:58.221687687Z     run_migration_for_sqlite()
2025-06-06T13:40:58.221689875Z   File "/pgadmin4/pgadmin/__init__.py", line 413, in run_migration_for_sqlite
2025-06-06T13:40:58.221692151Z     upgrade_db()
2025-06-06T13:40:58.221694308Z   File "/pgadmin4/pgadmin/__init__.py", line 395, in upgrade_db
2025-06-06T13:40:58.221696532Z     backup_db_file()
2025-06-06T13:40:58.221698658Z   File "/pgadmin4/pgadmin/__init__.py", line 383, in backup_db_file
2025-06-06T13:40:58.221700894Z     raise RuntimeError('Migration failed')
2025-06-06T13:40:58.221703061Z RuntimeError: Migration failed
2025-06-06T13:40:58.221705190Z [2025-06-06 13:40:58 +0000] [83] [INFO] Worker exiting (pid: 83)
2025-06-06T13:40:58.524201195Z [2025-06-06 13:40:58 +0000] [1] [ERROR] Worker (pid:83) exited with code 3
2025-06-06T13:40:58.524507668Z [2025-06-06 13:40:58 +0000] [1] [ERROR] Shutting down: Master
2025-06-06T13:40:58.524522606Z [2025-06-06 13:40:58 +0000] [1] [ERROR] Reason: Worker failed to boot.
2025-06-06T13:40:58.768107363Z Email address: 2025-06-06T13:40:59.368162420Z postfix/postlog: starting the Postfix mail system
2025-06-06T13:41:01.995203301Z /venv/lib/python3.12/site-packages/passlib/pwd.py:16: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
2025-06-06T13:41:01.995235591Z   import pkg_resources
2025-06-06T13:41:06.909156843Z /venv/lib/python3.12/site-packages/passlib/pwd.py:16: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
2025-06-06T13:41:06.909182859Z   import pkg_resources

```


Tried rolling back, no luck, tried PGADMIN_SETUP_EMAIL  PGADMIN_SETUP_PASSWORD no luck

**Comment by havedill** [comment]
My solution:

I created a duplicate container / fresh container. Then i went to my docker volume on my host, and did a backup

`sqlite3 pgadmin4.db ".dump server" > backup.sql`

I took this backup.sql to the new containers volume, and restored it

`sqlite3 pgadmin4.db < backup.sql`
