### ISSUE TITLE
Screen goes white and unusable, losing all query progress as no ability to save

### ISSUE THREAD

**Issue by Carl-Llewellyn** [pgadmin-org/pgadmin4#7596]
Using the query editor the whole window goes white and is unusable, except for the top bar. Pressing things on the top bar does nothing.

This means I lose all progress on any queries.

**To Reproduce**

Use the query edits. It seems to happen randomly.

![image](https://github.com/pgadmin-org/pgadmin4/assets/22121713/6ac2bbf1-27b1-4571-a4fc-953e2e50b2f1)

**Desktop (please complete the following information):**
 - OS: Ununtu 22.04 (Xorg with Nvidia dGPU)
 - Version: 8.8
 - Mode: Desktop connected to remote server
 - **Not** in browser
 - Package type: Apt

**Additional context**

This hasn't happened in a while, not sure if it's linked to the latest update but it has come back.

**Comment by pravesh-sharma** [comment]
Hi @Carl-Llewellyn,

Can you please share the logs for further investigation? You can view logs from `File -> Runtime -> View log`.

**Comment by RedShift1** [comment]
I'm having the same issue, here's what's in the log:

```

--------------[UI error]---------------
TypeError: Cannot read properties of undefined (reading 'constructor')
    at d.getItemAtIndex (http://127.0.0.1:53710/static/js/generated/vendor.others.js?ver=80900:312:1306959)
    at getItemKey (http://127.0.0.1:53710/static/js/generated/vendor.others.js?ver=80900:312:1307410)
    at w.render (http://127.0.0.1:53710/static/js/generated/vendor.react.js?ver=80900:2:218391)
    at Bl (http://127.0.0.1:53710/static/js/generated/vendor.react.js?ver=80900:2:113104)
    at $l (http://127.0.0.1:53710/static/js/generated/vendor.react.js?ver=80900:2:112904)
    at Ga (http://127.0.0.1:53710/static/js/generated/vendor.react.js?ver=80900:2:153519)
    at Ou (http://127.0.0.1:53710/static/js/generated/vendor.react.js?ver=80900:2:139810)
    at zu (http://127.0.0.1:53710/static/js/generated/vendor.react.js?ver=80900:2:139738)
    at Ru (http://127.0.0.1:53710/static/js/generated/vendor.react.js?ver=80900:2:139601)
    at bu (http://127.0.0.1:53710/static/js/generated/vendor.react.js?ver=80900:2:136598)
------------[UI End]----------------
```

**Comment by khushboovashi** [comment]
@RedShift1, do you face the same issue? By looking at your logs, it seems pgAdmin goes blank while using Object Explorer and not the Query Editor, as mentioned by @Carl-Llewellyn .

**Comment by Carl-Llewellyn** [comment]
> @RedShift1, do you face the same issue? By looking at your logs, it seems pgAdmin goes blank while using Object Explorer and not the Query Editor, as mentioned by @Carl-Llewellyn .

It can also happen with object explorer for me, not just the query editor.

**Comment by Carl-Llewellyn** [comment]
> Hi @Carl-Llewellyn,
> 
> Can you please share the logs for further investigation? You can view logs from `File -> Runtime -> View log`.

Here's an extraction of all UI errors from the logs (it happens randomly - sometimes many times a day, then not for a while - so I'm unsure of the timing):

```
--------------[UI error]---------------
AxiosError: Request failed with status code 500
    at http://127.0.0.1:38395/static/js/generated/vendor.others.js?ver=70700:109:4120750
    at XMLHttpRequest.u (http://127.0.0.1:38395/static/js/generated/vendor.others.js?ver=70700:109:4120895)
------------[UI End]----------------
Log File: /home/carl/.local/share/pgadmin/pgadmin4.1696349628232.log
Error Start Line: 176

--------------[UI error]---------------
Error: Request failed with status code 500
    at e.exports (http://127.0.0.1:34387/static/js/generated/vendor.others.js?ver=70100:109:169883)
    at e.exports (http://127.0.0.1:34387/static/js/generated/vendor.others.js?ver=70100:109:172306)
    at XMLHttpRequest.v (http://127.0.0.1:34387/static/js/generated/vendor.others.js?ver=70100:109:165203)
------------[UI End]----------------
Log File: /home/carl/.local/share/pgadmin/pgadmin4.1685637712362.log
Error Start Line: 310

--------------[UI error]---------------
AxiosError: Request failed with status code 500
    at http://127.0.0.1:45465/static/js/generated/vendor.others.js?ver=80200:109:2201900
    at XMLHttpRequest.d (http://127.0.0.1:45465/static/js/generated/vendor.others.js?ver=80200:109:2202045)
------------[UI End]----------------
Log File: /home/carl/.local/share/pgadmin/pgadmin4.1707514064719.log
Error Start Line: 76

--------------[UI error]---------------
[object Object] "It's a leaf node"
------------[UI End]----------------
Log File: /home/carl/.local/share/pgadmin/pgadmin4.1687971583496.log
Error Start Line: 197

--------------[UI error]---------------
Error: Request failed with status code 500
    at e.exports (http://127.0.0.1:37351/static/js/generated/vendor.others.js?ver=70100:109:169883)
    at e.exports (http://127.0.0.1:37351/static/js/generated/vendor.others.js?ver=70100:109:172306)
    at XMLHttpRequest.v (http://127.0.0.1:37351/static/js/generated/vendor.others.js?ver=70100:109:165203)
------------[UI End]----------------
Log File: /home/carl/.local/share/pgadmin/pgadmin4.1684428414351.log
Error Start Line: 496

--------------[UI error]---------------
Error: Request failed with status code 500
    at e.exports (http://127.0.0.1:37351/static/js/generated/vendor.others.js?ver=70100:109:169883)
    at e.exports (http://127.0.0.1:37351/static/js/generated/vendor.others.js?ver=70100:109:172306)
    at XMLHttpRequest.v (http://127.0.0.1:37351/static/js/generated/vendor.others.js?ver=70100:109:165203)
------------[UI End]----------------
Log File: /home/carl/.local/share/pgadmin/pgadmin4.1684428414351.log
Error Start Line: 513

--------------[UI error]---------------
Error: Request failed with status code 500
    at e.exports (http://127.0.0.1:37351/static/js/generated/vendor.others.js?ver=70100:109:169883)
    at e.exports (http://127.0.0.1:37351/static/js/generated/vendor.others.js?ver=70100:109:172306)
    at XMLHttpRequest.v (http://127.0.0.1:37351/static/js/generated/vendor.others.js?ver=70100:109:165203)
------------[UI End]----------------
Log File: /home/carl/.local/share/pgadmin/pgadmin4.1684428414351.log
Error Start Line: 522

--------------[UI error]---------------
Error: Request failed with status code 500
    at e.exports (http://127.0.0.1:37351/static/js/generated/vendor.others.js?ver=70100:109:169883)
    at e.exports (http://127.0.0.1:37351/static/js/generated/vendor.others.js?ver=70100:109:172306)
    at XMLHttpRequest.v (http://127.0.0.1:37351/static/js/generated/vendor.others.js?ver=70100:109:165203)
------------[UI End]----------------
Log File: /home/carl/.local/share/pgadmin/pgadmin4.1684428414351.log
Error Start Line: 531

--------------[UI error]---------------
Error: Request failed with status code 500
    at e.exports (http://127.0.0.1:37351/static/js/generated/vendor.others.js?ver=70100:109:169883)
    at e.exports (http://127.0.0.1:37351/static/js/generated/vendor.others.js?ver=70100:109:172306)
    at XMLHttpRequest.v (http://127.0.0.1:37351/static/js/generated/vendor.others.js?ver=70100:109:165203)
------------[UI End]----------------
Log File: /home/carl/.local/share/pgadmin/pgadmin4.1684428414351.log
Error Start Line: 540

--------------[UI error]---------------
Error: Request failed with status code 500
    at e.exports (http://127.0.0.1:37351/static/js/generated/vendor.others.js?ver=70100:109:169883)
    at e.exports (http://127.0.0.1:37351/static/js/generated/vendor.others.js?ver=70100:109:172306)
    at XMLHttpRequest.v (http://127.0.0.1:37351/static/js/generated/vendor.others.js?ver=70100:109:165203)
------------[UI End]----------------
Log File: /home/carl/.local/share/pgadmin/pgadmin4.1684428414351.log
Error Start Line: 549

--------------[UI error]---------------
Error: Request failed with status code 500
    at e.exports (http://127.0.0.1:37351/static/js/generated/vendor.others.js?ver=70100:109:169883)
    at e.exports (http://127.0.0.1:37351/static/js/generated/vendor.others.js?ver=70100:109:172306)
    at XMLHttpRequest.v (http://127.0.0.1:37351/static/js/generated/vendor.others.js?ver=70100:109:165203)
------------[UI End]----------------
Log File: /home/carl/.local/share/pgadmin/pgadmin4.1684428414351.log
Error Start Line: 558

--------------[UI error]---------------
Error: Request failed with status code 500
    at e.exports (http://127.0.0.1:37351/static/js/generated/vendor.others.js?ver=70100:109:169883)
    at e.exports (http://127.0.0.1:37351/static/js/generated/vendor.others.js?ver=70100:109:172306)
    at XMLHttpRequest.v (http://127.0.0.1:37351/static/js/generated/vendor.others.js?ver=70100:109:165203)
------------[UI End]----------------
Log File: /home/carl/.local/share/pgadmin/pgadmin4.1684428414351.log
Error Start Line: 567

--------------[UI error]---------------
Error: Request failed with status code 500
    at e.exports (http://127.0.0.1:37351/static/js/generated/vendor.others.js?ver=70100:109:169883)
    at e.exports (http://127.0.0.1:37351/static/js/generated/vendor.others.js?ver=70100:109:172306)
    at XMLHttpRequest.v (http://127.0.0.1:37351/static/js/generated/vendor.others.js?ver=70100:109:165203)
------------[UI End]----------------
Log File: /home/carl/.local/share/pgadmin/pgadmin4.1684428414351.log
Error Start Line: 581

--------------[UI error]---------------
Error: Request failed with status code 500
    at e.exports (http://127.0.0.1:37351/static/js/generated/vendor.others.js?ver=70100:109:169883)
    at e.exports (http://127.0.0.1:37351/static/js/generated/vendor.others.js?ver=70100:109:172306)
    at XMLHttpRequest.v (http://127.0.0.1:37351/static/js/generated/vendor.others.js?ver=70100:109:165203)
------------[UI End]----------------
Log File: /home/carl/.local/share/pgadmin/pgadmin4.1684428414351.log
Error Start Line: 904

--------------[UI error]---------------
[object Object] "It's a leaf node"
------------[UI End]----------------
Log File: /home/carl/.local/share/pgadmin/pgadmin4.1688166035007.log
Error Start Line: 75

--------------[UI error]---------------
AxiosError: Request failed with status code 500
    at http://127.0.0.1:43469/static/js/generated/vendor.others.js?ver=70600:109:4011035
    at XMLHttpRequest.u (http://127.0.0.1:43469/static/js/generated/vendor.others.js?ver=70600:109:4011180)
------------[UI End]----------------
Log File: /home/carl/.local/share/pgadmin/pgadmin4.1694033716095.log
Error Start Line: 130

--------------[UI error]---------------
AxiosError: Request failed with status code 500
    at http://127.0.0.1:43469/static/js/generated/vendor.others.js?ver=70600:109:4011035
    at XMLHttpRequest.u (http://127.0.0.1:43469/static/js/generated/vendor.others.js?ver=70600:109:4011180)
------------[UI End]----------------
Log File: /home/carl/.local/share/pgadmin/pgadmin4.1694033716095.log
Error Start Line: 140

--------------[UI error]---------------
AxiosError: Request failed with status code 500
    at http://127.0.0.1:43469/static/js/generated/vendor.others.js?ver=70600:109:4011035
    at XMLHttpRequest.u (http://127.0.0.1:43469/static/js/generated/vendor.others.js?ver=70600:109:4011180)
------------[UI End]----------------
Log File: /home/carl/.local/share/pgadmin/pgadmin4.1694033716095.log
Error Start Line: 150

--------------[UI error]---------------
AxiosError: Request failed with status code 500
    at http://127.0.0.1:43469/static/js/generated/vendor.others.js?ver=70600:109:4011035
    at XMLHttpRequest.u (http://127.0.0.1:43469/static/js/generated/vendor.others.js?ver=70600:109:4011180)
------------[UI End]----------------
Log File: /home/carl/.local/share/pgadmin/pgadmin4.1694033716095.log
Error Start Line: 161

--------------[UI error]---------------
AxiosError: Request failed with status code 500
    at http://127.0.0.1:43469/static/js/generated/vendor.others.js?ver=70600:109:4011035
    at XMLHttpRequest.u (http://127.0.0.1:43469/static/js/generated/vendor.others.js?ver=70600:109:4011180)
------------[UI End]----------------
Log File: /home/carl/.local/share/pgadmin/pgadmin4.1694033716095.log
Error Start Line: 170

--------------[UI error]---------------
AxiosError: Request failed with status code 500
    at http://127.0.0.1:43469/static/js/generated/vendor.others.js?ver=70600:109:4011035
    at XMLHttpRequest.u (http://127.0.0.1:43469/static/js/generated/vendor.others.js?ver=70600:109:4011180)
------------[UI End]----------------
Log File: /home/carl/.local/share/pgadmin/pgadmin4.1694033716095.log
Error Start Line: 179

--------------[UI error]---------------
AxiosError: Request failed with status code 500
    at http://127.0.0.1:43469/static/js/generated/vendor.others.js?ver=70600:109:4011035
    at XMLHttpRequest.u (http://127.0.0.1:43469/static/js/generated/vendor.others.js?ver=70600:109:4011180)
------------[UI End]----------------
Log File: /home/carl/.local/share/pgadmin/pgadmin4.1694033716095.log
Error Start Line: 189

--------------[UI error]---------------
AxiosError: Request failed with status code 500
    at http://127.0.0.1:43469/static/js/generated/vendor.others.js?ver=70600:109:4011035
    at XMLHttpRequest.u (http://127.0.0.1:43469/static/js/generated/vendor.others.js?ver=70600:109:4011180)
------------[UI End]----------------
Log File: /home/carl/.local/share/pgadmin/pgadmin4.1694033716095.log
Error Start Line: 197

--------------[UI error]---------------
AxiosError: Request failed with status code 500
    at http://127.0.0.1:43469/static/js/generated/vendor.others.js?ver=70600:109:4011035
    at XMLHttpRequest.u (http://127.0.0.1:43469/static/js/generated/vendor.others.js?ver=70600:109:4011180)
------------[UI End]----------------
Log File: /home/carl/.local/share/pgadmin/pgadmin4.1694033716095.log
Error Start Line: 218
```

**Comment by yogeshmahajan-1903** [comment]
@Carl-Llewellyn 
Are you using keyboard to navigate through Object Explorer?

**Comment by Carl-Llewellyn** [comment]
> @Carl-Llewellyn Are you using keyboard to navigate through Object Explorer?

Could be but it's not the way I usually use the object explorer (I usually use the mouse). It also happens when typing or clicking in the query editor.

**Comment by fharper** [comment]
I have the same issue with 8.9 on macOS. It happen when I expand the "Servers" in the "Object Explorer".

Here is the content of the logs

```
pgAdmin Runtime Environment
--------------------------------------------------------
Python Path: "/Applications/pgAdmin 4.app/Contents/Frameworks/Python.framework/Versions/Current/bin/python3"
Runtime Config File: "/Users/fharper/Library/Preferences/pgadmin/runtime_config.json"
pgAdmin Config File: "/Applications/pgAdmin 4.app/Contents/Resources/web/config.py"
Webapp Path: "/Applications/pgAdmin 4.app/Contents/Resources/web/pgAdmin4.py"
pgAdmin Command: "/Applications/pgAdmin 4.app/Contents/Frameworks/Python.framework/Versions/Current/bin/python3 -s /Applications/pgAdmin 4.app/Contents/Resources/web/pgAdmin4.py"
Environment: 
  - MallocNanoZone: 0
  - USER: fharper
  - SECURITYSESSIONID: 186b3
  - COMMAND_MODE: unix2003
  - __CFBundleIdentifier: org.pgadmin.pgadmin4
  - PATH: /usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin
  - LOGNAME: fharper
  - SYSTEM_VERSION_COMPAT: 0
  - SSH_AUTH_SOCK: /private/tmp/com.apple.launchd.aMmAqpW0Lm/Listeners
  - HOME: /Users/fharper
  - SHELL: /bin/zsh
  - TMPDIR: /var/folders/kv/1rgbm3852ld_2k2r9rpbns580000gn/T/
  - LaunchInstanceID: 50D6234E-8AED-4BBA-8918-4BA898E65471
  - __CF_USER_TEXT_ENCODING: 0x1F5:0x0:0x0
  - XPC_SERVICE_NAME: application.org.pgadmin.pgadmin4.90300872.166208883
  - XPC_FLAGS: 0x0
  - PGADMIN_INT_PORT: 57523
  - PGADMIN_INT_KEY: 88fb5a64-2dcf-498a-954f-23a2f6bedd71
  - PGADMIN_SERVER_MODE: OFF
--------------------------------------------------------

Total spawn time to start the pgAdmin4 server: 0.002 Sec
2024-07-22 16:27:54,896: WARNING	werkzeug:	Werkzeug appears to be used in a production deployment. Consider switching to a production web server instead.

 * Serving Flask app 'pgadmin'
 * Debug mode: off

------------------------------------------
Total time taken to ping pgAdmin4 server: 2.014 Sec
------------------------------------------
Total launch time of pgAdmin4: 2.658 Sec
------------------------------------------
Application Server URL: http://127.0.0.1:57523/?key=88fb5a64-2dcf-498a-954f-23a2f6bedd71

```

**Comment by Carl-Llewellyn** [comment]
Just happened twice. Lost a lot of work...:

```
--------------[UI error]---------------
AxiosError: Network Error
    at c.onerror (http://127.0.0.1:41565/static/js/generated/vendor.others.js?ver=80900:312:2127609)
    at nt.request (http://127.0.0.1:41565/static/js/generated/vendor.others.js?ver=80900:312:2134988)
------------[UI End]----------------
Log File: /home/carl/.local/share/pgadmin/pgadmin4.1722272298605.log
Error Start Line: 88
```

The server pgadmin is connecting to is currently under very heavy load which is slowing down the communication. Maybe something to do with it?

**Comment by anilsahoo20** [comment]
Hi @Carl-Llewellyn 
Can you please share the complete log file? Also share the log file = /home/carl/.local/share/pgadmin/pgadmin4.1722272298605.log.

**Comment by Carl-Llewellyn** [comment]
> Hi @Carl-Llewellyn Can you please share the complete log file? Also share the log file = /home/carl/.local/share/pgadmin/pgadmin4.1722272298605.log.

Sure, attached. Thanks!

[pgadmin4.1722272298605.log](https://github.com/user-attachments/files/16486763/pgadmin4.1722272298605.log)

**Comment by casparsch** [comment]
> I have the same issue with 8.9 on macOS. It happen when I expand the "Servers" in the "Object Explorer".

Seems to me kind of similar as I reported in [7025](https://github.com/pgadmin-org/pgadmin4/issues/7025)
So apparently I'm not the only one.

**Comment by aergul** [comment]
I too have the same issue currently running 8.10 but had it in a few prior versions as well. While editing queries (copy/paste/type/etc), all windows go blank, key presses generate a beep (unless dev tools open), menu options fail to open windows (except "Configure runtime"). 

My logs do not contain any application errors as some have reported (maybe because debug mode is off) - just errors in my queries which have been edited out:
```
pgAdmin Runtime Environment
--------------------------------------------------------
Python Path: "/Applications/pgAdmin 4.app/Contents/Frameworks/Python.framework/Versions/Current/bin/python3"
Runtime Config File: "/Users/aergul/Library/Application Support/pgAdmin 4/config.json"
Webapp Path: "/Applications/pgAdmin 4.app/Contents/Resources/web/pgAdmin4.py"
pgAdmin Command: "/Applications/pgAdmin 4.app/Contents/Frameworks/Python.framework/Versions/Current/bin/python3 -s /Applications/pgAdmin 4.app/Contents/Resources/web/pgAdmin4.py"
Environment: 
  - MallocNanoZone: 0
  - USER: aergul
  - COMMAND_MODE: unix2003
  - __CFBundleIdentifier: org.pgadmin.pgadmin4
  - PATH: /usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin
  - LOGNAME: aergul
  - DISPLAY: /private/tmp/com.apple.launchd.etK3RyWnAf/org.macosforge.xquartz:0
  - SYSTEM_VERSION_COMPAT: 0
  - SSH_AUTH_SOCK: /private/tmp/com.apple.launchd.HqBj7Ouz4N/Listeners
  - HOME: /Users/aergul
  - SHELL: /bin/zsh
  - TMPDIR: /var/folders/y2/0b1ssm3172g65lxdml8fn66r0000gq/T/
  - __CF_USER_TEXT_ENCODING: 0x1F7:0x0:0x0
  - XPC_SERVICE_NAME: application.org.pgadmin.pgadmin4.392305562.392321072
  - XPC_FLAGS: 0x0
  - ORIGINAL_XDG_CURRENT_DESKTOP: undefined
  - ELECTRON_ENABLE_SECURITY_WARNINGS: false
  - PGADMIN_INT_PORT: 50978
  - PGADMIN_INT_KEY: fea6cd8a-4c9a-4882-8d20-7bd6231d4d2f
  - PGADMIN_SERVER_MODE: OFF
--------------------------------------------------------

Total spawn time to start the pgAdmin4 server: 0.003 Sec
2024-07-31 14:54:30,549: WARNING	werkzeug:	Werkzeug appears to be used in a production deployment. Consider switching to a production web server instead.

 * Serving Flask app 'pgadmin'
 * Debug mode: off

------------------------------------------
Total time taken to ping pgAdmin4 server: 5.031 Sec
------------------------------------------
Total launch time of pgAdmin4: 5.324 Sec
------------------------------------------
Application Server URL: http://127.0.0.1:50978/?key=fea6cd8a-4c9a-4882-8d20-7bd6231d4d2f
```

**Comment by augustomen** [comment]
I have also noticed this for a while, and it's still present in v8.11. I got the error while typing in a psql tab:

    Exception in thread Thread-63709 (read_and_forward_pty_output):

    Traceback (most recent call last):
      File "threading.py", line 1073, in _bootstrap_inner

      File "threading.py", line 1010, in run
      File "C:\Program Files\pgAdmin 4\python\Lib\site-packages\flask\ctx.py", line 191, in wrapper
        return ctx.app.ensure_sync(f)(*args, **kwargs)  # type: ignore[union-attr]

               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "C:\Program Files\pgAdmin 4\web\pgadmin\tools\psql\__init__.py", line 291, in read_and_forward_pty_output

        pty_handel_io(connection_data, data, sid)

      File "C:\Program Files\pgAdmin 4\web\pgadmin\tools\psql\__init__.py", line 275, in pty_handel_io

        windows_platform(connection_data, sid, max_read_bytes)

      File "C:\Program Files\pgAdmin 4\web\pgadmin\tools\psql\__init__.py", line 248, in windows_platform
        read_stdout(process, sid, max_read_bytes,
      File "C:\Program Files\pgAdmin 4\web\pgadmin\tools\psql\__init__.py", line 227, in read_stdout

        output = process.read(max_read_bytes)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "C:\Program Files\pgAdmin 4\python\Lib\site-packages\winpty\ptyprocess.py", line 194, in read

        raise EOFError('Pty is closed')

    EOFError: Pty is closed

Hope it helps.

**Comment by Carl-Llewellyn** [comment]
Just an update and not sure if this has anything to do with it. However, I find this happens _way more_ if my network is unstable.

**Comment by brandwork-jb** [comment]
I am having the same issue for over a year now with any version of PGadmin.

Sometimes it is a workaround for me to enable the dev-tools of the browser and shrink the available screen space. After a reload, the PGadmin UI is present again. But this does only work in about 2/3 of all cases.

**Comment by seyed-abas-alavi** [comment]
i also have pretty much the same issue when i click at create Script or want to see commands history displaying white space except left-hand tab bar.
Ubuntu 22.04.5 LTS
![Screenshot from 2024-12-17 17-43-16](https://github.com/user-attachments/assets/cb020092-2655-4125-9143-31168e8c3298)

**Comment by Carl-Llewellyn** [comment]
> Hi, I am consistently experiencing pgadmin whitescreening, with no recovery other than View | Reload, resulting loss in all unsaved work that wasn't part of recent query history. Pretty stink.
> 
> Reproducing is easy for me. Simply have a fullish working session in place, eg. 5+ number of working tabs open with a number of queries returning in excess of 1000 rows on screen. Also have a number of expanded tables and columns in the object explorer...
> 
> Then to make it crash, simply move the mouse over to the Object Explorer and Rapidly Wheelmouse down to the bottom of the object explorer, and hey presto (not every time, but annoyingly often) crash, lose work, reset.
> 
> Also, there seems to be something funky going on at the bottom of the Object Explorer, because if u mouse scroll wheel past the last object entry (tablespaces for me) you end up observing a shimmer effect as per the image below taken w my phone
> 
> ![image](https://private-user-images.githubusercontent.com/33166116/397528402-4b5fad90-3f4d-4c01-a24f-8ac27a634bf3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ2NDIxMjAsIm5iZiI6MTczNDY0MTgyMCwicGF0aCI6Ii8zMzE2NjExNi8zOTc1Mjg0MDItNGI1ZmFkOTAtM2Y0ZC00YzAxLWEyNGYtOGFjMjdhNjM0YmYzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjE5VDIwNTcwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI4Mzg5YzY0MzVkOWM1MmYyZTUxZmJiNWY5Y2QxMjg2OGM0MmQ2YWQ5YmY1ODBhNjZkYzczZTM2YzIxZjBhYzAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.Mr_sHgpKHlCo-A3W2CpVBOeS31mKRqFMPCY1W5P0tbY)
> 
> Pretty, pretty please fix

I'm just OP, not a pgadmin dev. 

However, include your log and system specs and it'll probably help move this forward!

**Comment by brandwork-jb** [comment]
> i also have pretty much the same issue when i click at create Script or want to see commands history displaying white space except left-hand tab bar. Ubuntu 22.04.5 LTS ![Screenshot from 2024-12-17 17-43-16](https://private-user-images.githubusercontent.com/108953552/396530771-cb020092-2655-4125-9143-31168e8c3298.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzYxNDIwODgsIm5iZiI6MTczNjE0MTc4OCwicGF0aCI6Ii8xMDg5NTM1NTIvMzk2NTMwNzcxLWNiMDIwMDkyLTI2NTUtNDEyNS05MTQzLTMxMTY4ZThjMzI5OC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUwMTA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MDEwNlQwNTM2MjhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yZTcxNDBkMTY0YjE3OWNiZDI5NzBlOTkwMjFmN2I4ODQzNDNiOWU1M2QzMzg4Mjk1MGYwZmM3NmFkZTI3YTc1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.kOPpQxF08pzFCUPbVThELKv_SYcErrtaOL-FPF3BQMg)
> 
> furthermore:
> 
> i have two databases, after reading query history in 'create script' section the screen goes white and I turn back from history of other database into query tab so it works as well and does not display white screen!

This is not "pretty much the same issue" in my opinion. For my case, I am getting a fully blank screen, without any content shown in the browser tab.

**Comment by C0NN0RAD0** [comment]
I am also having this blank screen issue across multiple browsers.

**Comment by yogeshmahajan-1903** [comment]
@C0NN0RAD0 
What is pgadmin version? And also can you please share pgadmin logs?

**Comment by dj-jordan** [comment]
Hiya,

I’m now on version 9.0.  I’ve just spent the last 10 minutes trying to recreate the issue, and I’m happy to report that with the new Object Explorer interface I am unable to reproduce the issue.

i.e. The issue of loosing all expanded objects appears to be FIXED in v9.0

Many thanks, that was super annoying and had made pgadmin unworkable.  Now it’s fixed I’ll happily return

Case closed (for me at least)
Cheers
DJ
:-)

**Comment by october25** [comment]
I have been facing this issue since today. Logs for reference-

<img width="1440" alt="Image" src="https://github.com/user-attachments/assets/e0c072c2-b97a-4cb4-91e7-b32ab156db52" />
<img width="1440" alt="Image" src="https://github.com/user-attachments/assets/876e7e08-2247-49a3-9e07-5bdd35ba6add" />
<img width="1440" alt="Image" src="https://github.com/user-attachments/assets/43fe3cff-c998-4133-9a02-752179d06058" />

**Comment by october25** [comment]
> Still broken as of 9.2, can't use the app at all, even after restarting many times

I am facing the same issue.

**Comment by sjbruce** [comment]
I'm getting the following errors in the developer tools console when these errors occur in my instance of 9.2 on Windows.

Uninstalling and re-installing does not affect outcome.  I've rolled back to 8.4.12 and that seems to be behaving properly.

```
RangeError: Incorrect locale information provided                 vendor.react.js?ver=90200:2 
    at Date.toLocaleDateString (<anonymous>)
    at A (sqleditor.js?ver=90200:1:1314554)
    at I.isDaysBefore (sqleditor.js?ver=90200:1:1314942)
    at I.getDatePrefix (sqleditor.js?ver=90200:1:1315034)
    at I.getGroupHeader (sqleditor.js?ver=90200:1:1315669)
    at sqleditor.js?ver=90200:1:1315798
    at Array.map (<anonymous>)
    at I.getGroups (sqleditor.js?ver=90200:1:1315773)
    at sqleditor.js?ver=90200:1:1310243
    at Object.$i [as useMemo] (vendor.react.js?ver=90200:2:274873)


Uncaught RangeError: Incorrect locale information provided        vendor.react.js?ver=90200:2 
    at Date.toLocaleDateString (<anonymous>)
    at A (sqleditor.js?ver=90200:1:1314554)
    at I.isDaysBefore (sqleditor.js?ver=90200:1:1314942)
    at I.getDatePrefix (sqleditor.js?ver=90200:1:1315034)
    at I.getGroupHeader (sqleditor.js?ver=90200:1:1315669)
    at sqleditor.js?ver=90200:1:1315798
    at Array.map (<anonymous>)
    at I.getGroups (sqleditor.js?ver=90200:1:1315773)
    at sqleditor.js?ver=90200:1:1310243
    at Object.$i [as useMemo] (vendor.react.js?ver=90200:2:274873)
```

**Comment by ahmgithubahm** [comment]
Getting the same in 9.2, although it worked fine for a few days.  Back to 8.14 and no more white screens.

**Comment by ssge** [comment]
Same exceptions in the dev console as above. Unusable pgAdmin

**Comment by aagostino31** [comment]
I have the same issue. And it just happened out of the blue, and is unrecoverable.. I had to install a new version

**Comment by yogeshmahajan-1903** [comment]
@aagostino31 Can you please share the version and pgadmin4 logs?

**Comment by Phrease** [comment]
Still getting this issue on my end.

**Comment by DutchMofo** [comment]
I also run into issues with the query editor consistantly white-screening. It seems to happen when trying to explain a query that has an update inside a with statement. I can use the following code to reproduce:

```SQL
WITH lala AS (
	UPDATE key_event
	SET cost = 0::money
	WHERE id = 0
	RETURNING id
)
SELECT * FROM lala
```

**Comment by arjuntalati** [comment]
still running into this issue. pgadmin unusable.

**Comment by s-lukas** [comment]
Had a similar issue (query view turning blank after enabling edit mode in select / query editor) after updating from pgadmin4 9.2.0 to 9.11.0, the matching error in the backend seems to be:

```
10.1.0.2 - - [14/Dec/2025:12:00:00 +0000] "GET /preferences/get_all HTTP/1.1" 401 119 "https://pgadmin.my.domain.com/browser/" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:145.0) Gecko/20100101 Firefox/145.0"
```
After deleting all cookies, local & session storage in the browser for this page the query editor now works again.

**Comment by Ranexia04** [comment]
getting the same issue

**Comment by OmerFI** [comment]
issue still exists, i set it up using docker

<img width="1552" height="903" alt="Image" src="https://github.com/user-attachments/assets/e3fbc104-11f2-4066-9936-52314548443a" />
