### ISSUE TITLE
PGAdmin4 not starting after update

### ISSUE THREAD

**Issue by canedje** [pgadmin-org/pgadmin4#7631]
**_Please note that security bugs or issues should be reported to security@pgadmin.org._**

**Describe the bug**
PGADMIN not starting up anymore after latest update

**To Reproduce**
Just update 
3. See the error

**Expected behavior**

**Error message**
postfix/postlog: starting the Postfix mail system
[2024-06-27 11:51:59 +0200] [1] [INFO] Starting gunicorn 22.0.0
[2024-06-27 11:51:59 +0200] [1] [INFO] Listening at: http://0.0.0.0:80 (1)
[2024-06-27 11:51:59 +0200] [1] [INFO] Using worker: gthread
[2024-06-27 11:51:59 +0200] [88] [INFO] Booting worker with pid: 88
[2024-06-27 11:52:02 +0200] [88] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/venv/lib/python3.12/site-packages/gunicorn/arbiter.py", line 609, in spawn_worker
    worker.init_process()
  File "/venv/lib/python3.12/site-packages/gunicorn/workers/gthread.py", line 95, in init_process
    super().init_process()
  File "/venv/lib/python3.12/site-packages/gunicorn/workers/base.py", line 134, in init_process
    self.load_wsgi()
  File "/venv/lib/python3.12/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
                ^^^^^^^^^^^^^^^
  File "/venv/lib/python3.12/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
                    ^^^^^^^^^^^
  File "/venv/lib/python3.12/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
           ^^^^^^^^^^^^^^^^^^^
  File "/venv/lib/python3.12/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/venv/lib/python3.12/site-packages/gunicorn/util.py", line 371, in import_app
    mod = importlib.import_module(module)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/pgadmin4/run_pgadmin.py", line 4, in <module>
    from pgAdmin4 import app
  File "/pgadmin4/pgAdmin4.py", line 103, in <module>
    app = create_app()
          ^^^^^^^^^^^^
  File "/pgadmin4/pgadmin/__init__.py", line 473, in create_app
    run_migration_for_sqlite()
  File "/pgadmin4/pgadmin/__init__.py", line 448, in run_migration_for_sqlite
    os.chmod(config.SQLITE_PATH, 0o600)
PermissionError: [Errno 1] Operation not permitted: '/var/lib/pgadmin/pgadmin4.db'
[2024-06-27 11:52:02 +0200] [88] [INFO] Worker exiting (pid: 88)
[2024-06-27 11:52:02 +0200] [1] [ERROR] Worker (pid:88) exited with code 3
[2024-06-27 11:52:02 +0200] [1] [ERROR] Shutting down: Master
[2024-06-27 11:52:02 +0200] [1] [ERROR] Reason: Worker failed to boot.
If possible, include the full, unedited text of any error messages displayed.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Docker under Unraid
 - Version: [e.g. 6.15]
 - Mode: Server
 - Browser (if running in server mode): [e.g. chrome, safari]
 - Package type: [e.g. RPM, DEB, Python, Container, etc.]

**Additional context**

**Comment by canedje** [comment]
Fixed it by removing the pgadmin4.db file.
Not the right permissions

**Comment by TheBlindHawk** [comment]
I had around 20 pgadmin4-_something_.db files inside docker/pgadmin4.
It was not a permission related issue, but deleting all the pgadmin4- files fixed the issue for me.
