### ISSUE TITLE
pgadmin:	404 Not Found: The requested URL was not found on the server

### ISSUE THREAD

**Issue by IgorLytkin** [pgadmin-org/pgadmin4#7710]
**_Please note that security bugs or issues should be reported to security@pgadmin.org._**

I see erros in pgAdmin docker container log

**To Reproduce**

1. Go to Portianer
2. Click on container with pgAdmin, then Logs
3. See the error

**Expected behavior**
No error

**Error message**
2024-07-18 07:55:15,724: ERROR	pgadmin:	404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
Traceback (most recent call last):
  File "/venv/lib/python3.12/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/venv/lib/python3.12/site-packages/flask/app.py", line 854, in dispatch_request
    self.raise_routing_exception(req)
  File "/venv/lib/python3.12/site-packages/flask/app.py", line 463, in raise_routing_exception
    raise request.routing_exception  # type: ignore[misc]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/venv/lib/python3.12/site-packages/flask/ctx.py", line 362, in match_request
    result = self.url_adapter.match(return_rule=True)  # type: ignore
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/venv/lib/python3.12/site-packages/werkzeug/routing/map.py", line 629, in match
    raise NotFound() from None
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.

If possible, include the full, unedited text of any error messages displayed.

**Desktop (please complete the following information):**
 - OS: Ubuntu, Docker
 - Version: 22.04 LTS
 - Mode: Server
 - Browser Yandex browser
 - Package type: docker

**Comment by yogeshmahajan-1903** [comment]
@IgorLytkin 
What is docker image are you using? Can you please share docket command?

**Comment by IgorLytkin** [comment]
services:
  db:
    image: postgres:16.3
    restart: always
    env_file:
      - stack.env
    ports:
      - 54320:5432
    volumes:
      - db_data:/var/lib/postgresql/data
  db_beta7:
    image: postgres:17beta2
    restart: always
    env_file:
      - stack.env
    ports:
      - 54321:5432
    volumes:
      - db_beta7_data:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4:snapshot
    restart: always
    env_file:
      - stack.env

    ports:
      - "8888:80"
    extra_hosts:
      - "singularity:127.0.0.1"
    volumes:
      - pgadmin-data:/var/lib/pgadmin

volumes:
  db_data:
  db_beta7_data:
  pgadmin-data:

**Comment by IgorLytkin** [comment]
[_postgresql-pgadmin-1_logs.txt](https://github.com/user-attachments/files/16441664/_postgresql-pgadmin-1_logs.txt)

**Comment by anilsahoo20** [comment]
Hi @IgorLytkin 
Is there any particular scenario where you are getting this error log?

**Comment by IgorLytkin** [comment]
Whta you mean? I have errors every time, when i start my stack of containers. For example, i see it now
```werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
2024-08-02 15:06:28,357: ERROR	pgadmin:	404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
Traceback (most recent call last):
  File "/venv/lib/python3.12/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/venv/lib/python3.12/site-packages/flask/app.py", line 854, in dispatch_request
    self.raise_routing_exception(req)
  File "/venv/lib/python3.12/site-packages/flask/app.py", line 463, in raise_routing_exception
    raise request.routing_exception  # type: ignore[misc]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/venv/lib/python3.12/site-packages/flask/ctx.py", line 362, in match_request
    result = self.url_adapter.match(return_rule=True)  # type: ignore
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/venv/lib/python3.12/site-packages/werkzeug/routing/map.py", line 629, in match
    raise NotFound() from None
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.```

**Comment by khushboovashi** [comment]
@IgorLytkin, 

This error occurs when any API call to the pgAdmin server fails. Please browse the pgAdmin; in the developer tools, please check the network tab, where you can find if any API calls fail. Please provide that details.

**Comment by adityatoshniwal** [comment]
No response from the user. Closing.
