### ISSUE TITLE
python installation failed

### ISSUE THREAD

**Issue by liaohongxing** [pgadmin-org/pgadmin4#7747]
https://www.pgadmin.org/download/pgadmin-4-python/

**Error message**

```
(pgadmin4) aoc@Aoc-EliteMini-Series:~$ pip install pgadmin4
Collecting pgadmin4
  Using cached pgadmin4-8.9-py3-none-any.whl.metadata (3.6 kB)
Collecting Flask-Compress==1.* (from pgadmin4)
  Using cached Flask_Compress-1.15-py3-none-any.whl.metadata (8.4 kB)
Collecting Flask-Login==0.* (from pgadmin4)
  Using cached Flask_Login-0.6.3-py3-none-any.whl.metadata (5.8 kB)
Collecting Flask-Mail==0.* (from pgadmin4)
  Using cached flask_mail-0.10.0-py3-none-any.whl.metadata (2.1 kB)
Collecting Flask-Migrate==4.* (from pgadmin4)
  Using cached Flask_Migrate-4.0.7-py3-none-any.whl.metadata (3.1 kB)
Collecting Flask-Paranoid==0.* (from pgadmin4)
  Using cached Flask_Paranoid-0.3.0-py3-none-any.whl.metadata (2.1 kB)
Collecting Flask-SocketIO==5.3.* (from pgadmin4)
  Using cached Flask_SocketIO-5.3.6-py3-none-any.whl.metadata (2.6 kB)
Collecting SQLAlchemy==2.* (from pgadmin4)
  Using cached SQLAlchemy-2.0.31-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (9.6 kB)
Collecting azure-mgmt-rdbms==10.1.0 (from pgadmin4)
  Using cached azure_mgmt_rdbms-10.1.0-py3-none-any.whl.metadata (20 kB)
Collecting azure-mgmt-subscription==3.1.1 (from pgadmin4)
  Using cached azure_mgmt_subscription-3.1.1-py3-none-any.whl.metadata (9.5 kB)
Collecting bcrypt==4.1.* (from pgadmin4)
  Using cached bcrypt-4.1.3-cp39-abi3-manylinux_2_28_x86_64.whl.metadata (9.5 kB)
Collecting cryptography==42.0.* (from pgadmin4)
  Using cached cryptography-42.0.8-cp39-abi3-manylinux_2_28_x86_64.whl.metadata (5.3 kB)
Collecting eventlet==0.36.1 (from pgadmin4)
  Using cached eventlet-0.36.1-py3-none-any.whl.metadata (5.5 kB)
Collecting google-api-python-client==2.* (from pgadmin4)
  Using cached google_api_python_client-2.138.0-py2.py3-none-any.whl.metadata (6.7 kB)
Collecting google-auth-oauthlib==1.2.0 (from pgadmin4)
  Using cached google_auth_oauthlib-1.2.0-py2.py3-none-any.whl.metadata (2.7 kB)
Collecting httpagentparser==1.9.* (from pgadmin4)
  Using cached httpagentparser-1.9.5.tar.gz (7.7 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [20 lines of output]
      Traceback (most recent call last):
        File "/home/aoc/pgadmin4/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/home/aoc/pgadmin4/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/home/aoc/pgadmin4/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-raze28p1/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 327, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=[])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-raze28p1/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 297, in _get_build_requires
          self.run_setup()
        File "/tmp/pip-build-env-raze28p1/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 497, in run_setup
          super().run_setup(setup_script=setup_script)
        File "/tmp/pip-build-env-raze28p1/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 313, in run_setup
          exec(code, locals())
        File "<string>", line 2, in <module>
      ModuleNotFoundError: No module named 'setuptools.command.test'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

```

**Desktop (please complete the following information):**
 - OS: [Debian sid]
 - Version: [Debian GNU/Linux trixie/sid]

**Comment by khushboovashi** [comment]
Hi @liaohongxing, with the pgAdmin release 8.10, this should be fixed. Try installing again.

**Comment by liaohongxing** [comment]
@khushboovashi 

After testing, it has been successfully installed, thank you
