### ISSUE TITLE
"'NoneType' object is not iterable" when getting role properties

### ISSUE THREAD

**Issue by leemars** [pgadmin-org/pgadmin4#7837]
I am using pgadmin4 for Alibabacloud AnalyticDB for PostgreSQL, which is Postgresql compatiable.
```
PostgreSQL 12.12 (Greenplum Database 7.0.0-beta.0 build dev) on aarch64-unknown-linux-gnu, compiled by gcc (GCC) 9.2.1 20190812 (Alibaba 9.2.1-2 2.17), 64-bit compiled on Aug  2 2024 09:35:07 Bhuvnesh C.
```

When I tried to get Roles Properties, I got an exception.

![image](https://github.com/user-attachments/assets/ae9f4414-aab3-4a13-85ec-1d0ca5cf143c)

![image](https://github.com/user-attachments/assets/745edd27-f1b3-4dbf-85b3-f52e9de92db4)

I found this exception detail in log:

```python
2024-08-23 11:18:01,123: ERROR	pgadmin:	'NoneType' object is not iterable
Traceback (most recent call last):
  File "/Applications/pgAdmin 4.app/Contents/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Applications/pgAdmin 4.app/Contents/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Applications/pgAdmin 4.app/Contents/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/flask/views.py", line 110, in view
    return current_app.ensure_sync(self.dispatch_request)(**kwargs)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Applications/pgAdmin 4.app/Contents/Resources/web/pgadmin/browser/utils.py", line 309, in dispatch_request
    return method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Applications/pgAdmin 4.app/Contents/Resources/web/pgadmin/browser/server_groups/servers/roles/__init__.py", line 700, in wrapped
    return f(self, **kwargs)
           ^^^^^^^^^^^^^^^^^
  File "/Applications/pgAdmin 4.app/Contents/Resources/web/pgadmin/browser/server_groups/servers/roles/__init__.py", line 837, in properties
    self.transform(res)
  File "/Applications/pgAdmin 4.app/Contents/Resources/web/pgadmin/browser/server_groups/servers/roles/__init__.py", line 820, in transform
    self._set_rolemembership(row)
  File "/Applications/pgAdmin 4.app/Contents/Resources/web/pgadmin/browser/server_groups/servers/roles/__init__.py", line 799, in _set_rolemembership
    for role in row['rolmembers']:
TypeError: 'NoneType' object is not iterable
```

Then I found the problem may be here:
https://github.com/pgadmin-org/pgadmin4/blob/REL-8_11/web/pgadmin/browser/server_groups/servers/roles/__init__.py#L799

![image](https://github.com/user-attachments/assets/7f647e97-130f-47e2-8b30-ef9d628eafbe)

For some weird reasons, `row` has `rolmembers` key but with `None` value. It may be check just like that in `_set_seclabels` before using it.

**Comment by anilsahoo20** [comment]
Tested and verified on snapshot build: https://www.postgresql.org/ftp/pgadmin/pgadmin4/snapshots/2024-10-03/
Package: arm64, pip wheel
Environment: macOs Ventura 13.5.1
