### ISSUE TITLE
404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.

### ISSUE THREAD

**Issue by iwebroot** [pgadmin-org/pgadmin4#7914]
**_Please note that security bugs or issues should be reported to security@pgadmin.org._**

**Describe the bug**
No error during installation but after go to the URL, I have this issue
![image](https://github.com/user-attachments/assets/315ea95d-ccda-459c-9429-06d3353dde74)

**To Reproduce**

1. Install dependencies:
```
apt install htop virtualenv libpq-dev python3-dev gunicorn postgresql python3-flask python3-keyring python3-dateutil python3-flask-migrate python3-flask-babel python3-flask-sqlalchemy python3-flask-login python3-flask-security python3-flask-paranoid python3-flask-mail python3-flask-socketio python3.11-venv -y
```
2. Create folder for pgadmin4
```
mkdir -p /var/lib/pgadmin4/sessions && mkdir /var/lib/pgadmin4/storage && mkdir /var/log/pgadmin4 && mkdir /opt/pgadmin4
```
3. Create user
```
adduser --system --group --home /var/lib/pgadmin4 --disabled-login --shell /usr/sbin/nologin pgadmin 
```
4. Init environment and active this
```
python3 -m venv /opt/pgadmin4/venv
source /opt/pgadmin4/venv/bin/activate
```
5. Downgrade pip because the installation will failed
```
pip install --upgrade 'pip<24.1' wheel
```
6. Install pgAdmin4, gunicorn, setuptools
```
python3 -m pip install pgadmin4 && python3 -m pip install gunicorn && python3 -m pip install setuptools
```
7. Configure **config_local.py**
- Location: `/opt/pgadmin4/venv/lib/python3.11/site-packages/pgadmin4/config_local.py`
```
LOG_FILE = '/var/log/pgadmin4/pgadmin4.log'
SQLITE_PATH = '/var/lib/pgadmin4/pgadmin4.db'
SESSION_DB_PATH = '/var/lib/pgadmin4/sessions'
STORAGE_DIR = '/var/lib/pgadmin4/storage'
AZURE_CREDENTIAL_CACHE_DIR = ''
KERBEROS_CCACHE_DIR = ''
SERVER_MODE = True
```
8. Setup DB and set mail and password administrator
```
python3 /opt/pgadmin4/venv/lib/python3.11/site-packages/pgadmin4/setup.py setup-db
```
9. Set correct permission
```
chown -R pgadmin:pgadmin /var/log/pgadmin4 /var/lib/pgadmin4 /opt/pgadmin4
```
10. Create systemd
```
nano /etc/systemd/system/pgadmin4.service
```
Paste ...
```
[Unit]
Description = pgAdmin4 Service
After = network.target network-online.target
Wants = network-online.target

[Service]
User=pgadmin
WorkingDirectory=/opt/pgadmin4/
ExecStart=/opt/pgadmin4/venv/bin/gunicorn \
	--bind unix:/tmp/pgadmin4.sock \
	--workers=1 \
	--threads=25 \
	--chdir /opt/pgadmin4/venv/lib/python3.11/site-packages/pgadmin4 \
	pgAdmin4:app
	
[Install]
WantedBy = multi-user.target
```
11. Enable and start service and deactivate the environment
```
systemctl enable pgadmin4.service && systemctl start pgadmin4.service && deactivate
```
12. Configure App Server from WebAdmin OpenLiteSpeed
![image](https://github.com/user-attachments/assets/7a4b1a6a-157e-4934-af5e-84c50f12f355)
13. Configure Context from WebAdmin OpenLiteSpeed
![image](https://github.com/user-attachments/assets/c604beb4-bef1-4dfb-a43d-0ed4c3c9b80c)

14. Restart OpenLiteSpeed
15. Go to https://domain.tld/pgsql-manager/

**Error message into log**
```
2024-09-12 07:56:35,579: ERROR  pgadmin:        404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
Traceback (most recent call last):
  File "/opt/pgadmin4/venv/lib/python3.11/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/pgadmin4/venv/lib/python3.11/site-packages/flask/app.py", line 854, in dispatch_request
    self.raise_routing_exception(req)
  File "/opt/pgadmin4/venv/lib/python3.11/site-packages/flask/app.py", line 463, in raise_routing_exception
    raise request.routing_exception  # type: ignore[misc]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/pgadmin4/venv/lib/python3.11/site-packages/flask/ctx.py", line 362, in match_request
    result = self.url_adapter.match(return_rule=True)  # type: ignore
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/pgadmin4/venv/lib/python3.11/site-packages/werkzeug/routing/map.py", line 629, in match
    raise NotFound() from None
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
```

**Screenshots**
![image](https://github.com/user-attachments/assets/955bdc36-1ffc-403d-a9dc-6f130ecc23d7)

**Desktop (please complete the following information):**
 - OS: Debian
 - Version: 12
 - Mode: Server
 - Browser (if running in server mode): chrome
 - Package type: Python

**Additional context**
- Web server: OpenLiteSpeed
- Version: 1.8.1

**Comment by pravesh-sharma** [comment]
Hi @iwebroot,

You need to set the script name to `/pgsql-manager` in your web server configuration.

**Comment by pravesh-sharma** [comment]
No response from the author. Closing the issue.

**Comment by iwebroot** [comment]
Hello,
I solved the problem by adjusting the configurations.

I added a `wsgi.py` file in the `/opt/pgadmin4/` folder.

```python
import sys
import os
from werkzeug.middleware.dispatcher import DispatcherMiddleware

sys.path.insert(0, '/opt/pgadmin4/venv/lib/python3.12/site-packages/pgadmin4')

os.chdir('/opt/pgadmin4/venv/lib/python3.12/site-packages/pgadmin4')

from pgAdmin4 import app as pgadmin_app

application = DispatcherMiddleware(None, {
 '/pgsql-manager': pgadmin_app  # ou '/pgadmin'
})
```
Then I modified the file `/etc/systemd/system/pgadmin4.service`
```conf
[Unit]
Description=pgAdmin4 Service
After=network.target network-online.target
Wants=network-online.target

[Service]
User=pgadmin
WorkingDirectory=/opt/pgadmin4
ExecStart=/opt/pgadmin4/venv/bin/gunicorn \
    --bind unix:/tmp/pgadmin4.sock \
    --workers=1 \
    --threads=25 \
    wsgi:application

[Install]
WantedBy=multi-user.target
```

```
sudo systemctl daemon-reload
sudo systemctl start pgadmin4
```

**Comment by rking-bennie** [comment]
this is happening and i'm using the docker container. I even pulled old versions of the docker image. It seems this project is getting commits and support not sure how such an issue is occuring in released versions? I assume there must be some other configuration to provide?

Basic reproducible docker compose.

```
services:
  pgadmin:
    image: dpage/pgadmin4:latest
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: something@email.com
      PGADMIN_DEFAULT_PASSWORD: somepassword
    ports:
      - "9080:80"
```
