### ISSUE TITLE
Application Initialisation broken in 8.12 (at least in Docker)

### ISSUE THREAD

**Issue by r7l** [pgadmin-org/pgadmin4#7973]
**Describe the bug**

When using the Docker images, after upgrading to 8.12, i am no longer able to initialize pgadmin on a fresh database. Downgrading the image to 8.11 does fix the issue. It seems as if the new version does no longer use `PGADMIN_DEFAULT_EMAIL` environment variable.

I am using a custom Docker Compose file with settings according to the docs. I've not touched this file (besides version updates) for a number of recent 8.x versions. It always worked but just stopped doing so with 8.12. I've checked the docs but couldn't find any related changes.

**To Reproduce**

```
docker run -p 80:80 \
    -e 'PGADMIN_DEFAULT_EMAIL=user@domain.com' \
    -e 'PGADMIN_DEFAULT_PASSWORD=SuperSecret' \
    -d dpage/pgadmin4:8.12
```

**Expected behavior**

This is the output of 8.11 on a fresh database:

```
[2024-09-25 15:05:58 +0200] [1] [INFO] Starting gunicorn 22.0.0
[2024-09-25 15:05:58 +0200] [1] [INFO] Listening at: http://[::]:80 (1)
[2024-09-25 15:05:58 +0200] [1] [INFO] Using worker: gthread
[2024-09-25 15:05:58 +0200] [51] [INFO] Booting worker with pid: 51
NOTE: Configuring authentication for SERVER mode.

pgAdmin 4 - Application Initialisation
======================================
```

**Error message**

This is the output of 8.12 on a fresh database:

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/pgadmin4/pgadmin/utils/check_external_config_db.py", line 18, in check_external_config_db
    engine = create_engine(database_uri)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<string>", line 2, in create_engine
  File "/venv/lib/python3.12/site-packages/sqlalchemy/util/deprecations.py", line 281, in warned
    return fn(*args, **kwargs)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^
  File "/venv/lib/python3.12/site-packages/sqlalchemy/engine/create.py", line 599, in create_engine
    dbapi = dbapi_meth(**dbapi_args)
            ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/venv/lib/python3.12/site-packages/sqlalchemy/dialects/postgresql/psycopg2.py", line 690, in import_dbapi
    import psycopg2
ModuleNotFoundError: No module named 'psycopg2'
[2024-09-25 15:06:47 +0200] [1] [INFO] Starting gunicorn 22.0.0
[2024-09-25 15:06:47 +0200] [1] [INFO] Listening at: http://[::]:80 (1)
[2024-09-25 15:06:47 +0200] [1] [INFO] Using worker: gthread
[2024-09-25 15:06:47 +0200] [22] [INFO] Booting worker with pid: 22
NOTE: Configuring authentication for SERVER mode.

Enter the email address and password to use for the initial pgAdmin user account:

[2024-09-25 15:06:52 +0200] [22] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/venv/lib/python3.12/site-packages/gunicorn/arbiter.py", line 609, in spawn_worker
    worker.init_process()
  File "/venv/lib/python3.12/site-packages/gunicorn/workers/gthread.py", line 95, in init_process
    super().init_process()
  File "/venv/lib/python3.12/site-packages/gunicorn/workers/base.py", line 134, in init_process
    self.load_wsgi()
  File "/venv/lib/python3.12/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
                ^^^^^^^^^^^^^^^
  File "/venv/lib/python3.12/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
                    ^^^^^^^^^^^
  File "/venv/lib/python3.12/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
           ^^^^^^^^^^^^^^^^^^^
  File "/venv/lib/python3.12/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/venv/lib/python3.12/site-packages/gunicorn/util.py", line 371, in import_app
    mod = importlib.import_module(module)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/pgadmin4/run_pgadmin.py", line 4, in <module>
    from pgAdmin4 import app
  File "/pgadmin4/pgAdmin4.py", line 103, in <module>
    app = create_app()
          ^^^^^^^^^^^^
  File "/pgadmin4/pgadmin/__init__.py", line 471, in create_app
    run_migration_for_others()
  File "/pgadmin4/pgadmin/__init__.py", line 456, in run_migration_for_others
    db_upgrade(app)
  File "/pgadmin4/pgadmin/setup/db_upgrade.py", line 25, in db_upgrade
    flask_migrate.upgrade(migration_folder)
  File "/venv/lib/python3.12/site-packages/flask_migrate/__init__.py", line 111, in wrapped
    f(*args, **kwargs)
  File "/venv/lib/python3.12/site-packages/flask_migrate/__init__.py", line 200, in upgrade
    command.upgrade(config, revision, sql=sql, tag=tag)
  File "/venv/lib/python3.12/site-packages/alembic/command.py", line 406, in upgrade
    script.run_env()
  File "/venv/lib/python3.12/site-packages/alembic/script/base.py", line 582, in run_env
    util.load_python_file(self.dir, "env.py")
  File "/venv/lib/python3.12/site-packages/alembic/util/pyfiles.py", line 95, in load_python_file
    module = load_module_py(module_id, path)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/venv/lib/python3.12/site-packages/alembic/util/pyfiles.py", line 113, in load_module_py
    spec.loader.exec_module(module)  # type: ignore
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/pgadmin4/pgadmin/setup/../../migrations/env.py", line 95, in <module>
    run_migrations_online()
  File "/pgadmin4/pgadmin/setup/../../migrations/env.py", line 87, in run_migrations_online
    context.run_migrations()
  File "<string>", line 8, in run_migrations
  File "/venv/lib/python3.12/site-packages/alembic/runtime/environment.py", line 946, in run_migrations
    self.get_context().run_migrations(**kw)
  File "/venv/lib/python3.12/site-packages/alembic/runtime/migration.py", line 628, in run_migrations
    step.migration_fn(**kw)
  File "/pgadmin4/migrations/versions/fdc58d9bd449_.py", line 38, in upgrade
    email, password = user_info()
                      ^^^^^^^^^^^
  File "/pgadmin4/pgadmin/setup/user_info.py", line 75, in user_info
    email, p1 = user_info_server()
                ^^^^^^^^^^^^^^^^^^
  File "/pgadmin4/pgadmin/setup/user_info.py", line 52, in user_info_server
    email = input(ENTER_EMAIL_ADDRESS)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^
EOFError: EOF when reading a line
[2024-09-25 15:06:52 +0200] [22] [INFO] Worker exiting (pid: 22)
[2024-09-25 15:06:52 +0200] [1] [ERROR] Worker (pid:22) exited with code 3
[2024-09-25 15:06:52 +0200] [1] [ERROR] Shutting down: Master
[2024-09-25 15:06:52 +0200] [1] [ERROR] Reason: Worker failed to boot.
Email address: #
```

**Desktop (please complete the following information):**
 - OS: Linux
 - Mode: Server
 - Package type: Docker

**Additional context**

My pgadmin stack in Docker Compose file, which works for 8.11 and below but not for 8.12:

```
  pgadmin:
    image: dpage/pgadmin4:8.12
    depends_on:
      - postgresql
    networks:
      - my-project
    environment:
      PGADMIN_DISABLE_POSTFIX: "True"
      PGADMIN_DEFAULT_EMAIL: "mail@domain.com"
      PGADMIN_DEFAULT_PASSWORD: "password"
      PGADMIN_CONFIG_CONFIG_DATABASE_URI: "'postgresql://pgadmin:pgadmin@postgresql:5432/pgadmin'"
      PGADMIN_CONFIG_MINIFY_PAGE: "True"
      PGADMIN_CONFIG_ALLOW_SAVE_PASSWORD: "False"
      PGADMIN_CONFIG_UPGRADE_CHECK_ENABLED: "False"
```

**Comment by yogeshmahajan-1903** [comment]
@r7l 
Please refer [this](https://www.pgadmin.org/docs/pgadmin4/development/external_database.html#use-external-database).
You need to specify driver along with external db url.
E.g. - 
```
postgresql+psycopg://username:password@host:port/database
```

**Comment by r7l** [comment]
Thanks allot for your help. Didn't had time to test sooner but this change to the driver does fix the issue with the connection for 8.12 and fixes the first part of the error output. But the error with the email remains and seems to be a race condition within the Docker stack actually. This behaviour was different before 8.12.

When starting up a fresh stack with PostgreSQL and pgadmin, it ends up with this output for me:

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/pgadmin4/pgadmin/utils/check_external_config_db.py", line 27, in check_external_config_db
    connection.close()
    ^^^^^^^^^^
UnboundLocalError: cannot access local variable 'connection' where it is not associated with a value
[2024-09-26 17:18:10 +0200] [1] [INFO] Starting gunicorn 22.0.0
[2024-09-26 17:18:10 +0200] [1] [INFO] Listening at: http://[::]:80 (1)
[2024-09-26 17:18:10 +0200] [1] [INFO] Using worker: gthread
[2024-09-26 17:18:10 +0200] [22] [INFO] Booting worker with pid: 22
NOTE: Configuring authentication for SERVER mode.

Enter the email address and password to use for the initial pgAdmin user account:

[2024-09-26 17:18:14 +0200] [22] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/venv/lib/python3.12/site-packages/gunicorn/arbiter.py", line 609, in spawn_worker
    worker.init_process()
  File "/venv/lib/python3.12/site-packages/gunicorn/workers/gthread.py", line 95, in init_process
    super().init_process()
  File "/venv/lib/python3.12/site-packages/gunicorn/workers/base.py", line 134, in init_process
    self.load_wsgi()
  File "/venv/lib/python3.12/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
                ^^^^^^^^^^^^^^^
  File "/venv/lib/python3.12/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
                    ^^^^^^^^^^^
  File "/venv/lib/python3.12/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
           ^^^^^^^^^^^^^^^^^^^
  File "/venv/lib/python3.12/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/venv/lib/python3.12/site-packages/gunicorn/util.py", line 371, in import_app
    mod = importlib.import_module(module)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/pgadmin4/run_pgadmin.py", line 4, in <module>
    from pgAdmin4 import app
  File "/pgadmin4/pgAdmin4.py", line 103, in <module>
    app = create_app()
          ^^^^^^^^^^^^
  File "/pgadmin4/pgadmin/__init__.py", line 471, in create_app
    run_migration_for_others()
  File "/pgadmin4/pgadmin/__init__.py", line 456, in run_migration_for_others
    db_upgrade(app)
  File "/pgadmin4/pgadmin/setup/db_upgrade.py", line 25, in db_upgrade
    flask_migrate.upgrade(migration_folder)
  File "/venv/lib/python3.12/site-packages/flask_migrate/__init__.py", line 111, in wrapped
    f(*args, **kwargs)
  File "/venv/lib/python3.12/site-packages/flask_migrate/__init__.py", line 200, in upgrade
    command.upgrade(config, revision, sql=sql, tag=tag)
  File "/venv/lib/python3.12/site-packages/alembic/command.py", line 406, in upgrade
    script.run_env()
  File "/venv/lib/python3.12/site-packages/alembic/script/base.py", line 582, in run_env
    util.load_python_file(self.dir, "env.py")
  File "/venv/lib/python3.12/site-packages/alembic/util/pyfiles.py", line 95, in load_python_file
    module = load_module_py(module_id, path)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/venv/lib/python3.12/site-packages/alembic/util/pyfiles.py", line 113, in load_module_py
    spec.loader.exec_module(module)  # type: ignore
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/pgadmin4/pgadmin/setup/../../migrations/env.py", line 95, in <module>
    run_migrations_online()
  File "/pgadmin4/pgadmin/setup/../../migrations/env.py", line 87, in run_migrations_online
    context.run_migrations()
  File "<string>", line 8, in run_migrations
  File "/venv/lib/python3.12/site-packages/alembic/runtime/environment.py", line 946, in run_migrations
    self.get_context().run_migrations(**kw)
  File "/venv/lib/python3.12/site-packages/alembic/runtime/migration.py", line 628, in run_migrations
    step.migration_fn(**kw)
  File "/pgadmin4/migrations/versions/fdc58d9bd449_.py", line 38, in upgrade
    email, password = user_info()
                      ^^^^^^^^^^^
  File "/pgadmin4/pgadmin/setup/user_info.py", line 75, in user_info
    email, p1 = user_info_server()
                ^^^^^^^^^^^^^^^^^^
  File "/pgadmin4/pgadmin/setup/user_info.py", line 52, in user_info_server
    email = input(ENTER_EMAIL_ADDRESS)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^
EOFError: EOF when reading a line
```

If PostgreSQL has fully started prior to pgadmin, it doesn't happen. It's only if PostgreSQL is slower during startup then pgadmin. It is possible to go round this by adding `restart: always` as the second startup for pgadm does work. Even so, it's odd to fail over the Email configuration when it has connection issues.

**Comment by yogeshmahajan-1903** [comment]
@r7l 
You need to have Postgres up and running before using it. You can Postgres service dependency for pgadmin container to avoid this issue.
As there is no issue from pgadmin closing the issue.

**Comment by borutnet** [comment]
There is a chance that this wasn't properly debugged and that the underlying issue is related to variable naming, as I have suggested here:
https://github.com/pgadmin-org/pgadmin4/issues/7556#issuecomment-2571437156

I have tested this and deployment was successful after I have added PGADMIN_SETUP_EMAIL and PGADMIN_SETUP_PASSWORD environmental variables.
