### ISSUE TITLE
Add support for Python 3.13

### ISSUE THREAD

**Issue by RohitBhati8269** [pgadmin-org/pgadmin4#8068]
eventlet library not supporting Python 3.13, Due to that we are getting the below error:-

`Traceback (most recent call last):
  File "/Users/runner/work/pgadmin4/pgadmin4/web/regression/runtests.py", line 111, in <module>
    from pgAdmin4 import app
  File "/Users/runner/work/pgadmin4/pgadmin4/web/pgAdmin4.py", line 103, in <module>
    app = create_app()
  File "/Users/runner/work/pgadmin4/pgadmin4/web/pgadmin/__init__.py", line 754, in create_app
    app.register_blueprint(module)
    ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^
  File "/Users/runner/work/pgadmin4/pgadmin4/venv/lib/python3.13/site-packages/flask/sansio/scaffold.py", line 47, in wrapper_func
    return f(self, *args, **kwargs)
  File "/Users/runner/work/pgadmin4/pgadmin4/venv/lib/python3.13/site-packages/flask/sansio/app.py", line 595, in register_blueprint
    blueprint.register(self, options)
    ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "/Users/runner/work/pgadmin4/pgadmin4/web/pgadmin/tools/__init__.py", line 52, in register
    from .psql import blueprint as module
  File "/Users/runner/work/pgadmin4/pgadmin4/web/pgadmin/tools/psql/__init__.py", line 15, in <module>
    from eventlet.green import subprocess
  File "/Users/runner/work/pgadmin4/pgadmin4/venv/lib/python3.13/site-packages/eventlet/green/subprocess.py", line [8](https://github.com/pgadmin-org/pgadmin4/actions/runs/11514380919/job/32052886297?pr=8067#step:17:9), in <module>
    from eventlet.green import select, threading, time
  File "/Users/runner/work/pgadmin4/pgadmin4/venv/lib/python3.13/site-packages/eventlet/green/threading.py", line 18, in <module>
    eventlet.patcher.inject(
    ~~~~~~~~~~~~~~~~~~~~~~~^
        'threading',
        ^^^^^^^^^^^^
        globals(),
        ^^^^^^^^^^
        ('_thread', thread),
        ^^^^^^^^^^^^^^^^^^^^
        ('time', time))
        ^^^^^^^^^^^^^^^
  File "/Users/runner/work/pgadmin4/pgadmin4/venv/lib/python3.13/site-packages/eventlet/patcher.py", line 10[9](https://github.com/pgadmin-org/pgadmin4/actions/runs/11514380919/job/32052886297?pr=8067#step:17:10), in inject
    module = __import__(module_name, {}, {}, module_name.split('.')[:-1])
  File "/opt/homebrew/Cellar/python@3.13/3.13.0_1/Frameworks/Python.framework/Versions/3.13/lib/python3.13/threading.py", line 35, in <module>
    _start_joinable_thread = _thread.start_joinable_thread
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'eventlet.green.thread' has no attribute 'start_joinable_thread'`

Python 3.7-3.12 are currently supported by eventlet.
Reference :- https://pypi.org/project/eventlet/

**Comment by khushboovashi** [comment]
Upstream issue link: https://github.com/eventlet/eventlet/issues/964

**Comment by akshay-joshi** [comment]
Tested on OSX Sonoma and Windows 11. No issues found
