### ISSUE TITLE
Port could not be cast to integer value as ':'

### ISSUE THREAD

**Issue by emoxam** [pgadmin-org/pgadmin4#8073]
What i am trying.

rm -rf /opt/pgadmin
mkdir /opt/pgadmin/ && chown -R 5050:5050 /opt/pgadmin/ && ls -l
docker run -p 80:80 -v /opt/pgadmin:/var/lib/pgadmin --restart always -e 'PGADMIN_DEFAULT_EMAIL=username@domain.com' -e 'PGADMIN_DEFAULT_PASSWORD=pass' -d dpage/pgadmin4:8.12
docker logs 7c -f

`pgAdmin 4 - Application Initialisation
======================================

postfix/postlog: starting the Postfix mail system
[2024-10-28 14:04:19 +0000] [1] [INFO] Starting gunicorn 22.0.0
[2024-10-28 14:04:19 +0000] [1] [INFO] Listening at: http://[::]:80 (1)
[2024-10-28 14:04:19 +0000] [1] [INFO] Using worker: gthread
[2024-10-28 14:04:19 +0000] [117] [INFO] Booting worker with pid: 117
2024-10-28 14:04:37,065: ERROR  pgadmin:        Port could not be cast to integer value as ':'
Traceback (most recent call last):
  File "/venv/lib/python3.12/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/venv/lib/python3.12/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/venv/lib/python3.12/site-packages/flask_login/utils.py", line 285, in decorated_view
    return current_app.login_manager.unauthorized()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/venv/lib/python3.12/site-packages/flask_login/login_manager.py", line 170, in unauthorized
    return self.unauthorized_callback()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/venv/lib/python3.12/site-packages/flask_security/decorators.py", line 97, in default_unauthn_handler
    next_url = simplify_url(login_url, request.url)
                                       ^^^^^^^^^^^
  File "/venv/lib/python3.12/site-packages/werkzeug/utils.py", line 107, in __get__
    value = self.fget(obj)  # type: ignore
            ^^^^^^^^^^^^^^
  File "/venv/lib/python3.12/site-packages/werkzeug/sansio/request.py", line 210, in url
    return get_current_url(
           ^^^^^^^^^^^^^^^^
  File "/venv/lib/python3.12/site-packages/werkzeug/sansio/utils.py", line 137, in get_current_url
    return uri_to_iri("".join(url))
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/venv/lib/python3.12/site-packages/werkzeug/urls.py", line 98, in uri_to_iri
    if parts.port:
       ^^^^^^^^^^
  File "/usr/lib/python3.12/urllib/parse.py", line 182, in port
    raise ValueError(f"Port could not be cast to integer value as {port!r}")`

How can resolve this error ?

**Comment by emoxam** [comment]
`docker run -p 80:80 -v /opt/pgadmin:/var/lib/pgadmin --restart always -e 'PGADMIN_DEFAULT_EMAIL=user@domain.com' -e 'PGADMIN_DEFAULT_PASSWORD=password' -e 'PGADMIN_LISTEN_PORT=80' -d dpage/pgadmin4:8.12`

Worked.
