### ISSUE TITLE
OIDC setup with EntraID not working since version 8.2

### ISSUE THREAD

**Issue by oldboys92** [pgadmin-org/pgadmin4#8240]
**_Please note that security bugs or issues should be reported to security@pgadmin.org._**

**Describe the bug**

We have pgadmin deployed via helm chart into a K8S cluster as a shared solution for applications to access PGSQL databases. Users need to login via OIDC using Azure AD (B2B / EntraID) tenant as IDP. The setup stopped working with pgadmin4 version 8.2 and is still existing in latest version.

The user gets redirected to Azure AD login, but after login this error is shown in Web UI

```
{
    "success": 0,
    "errormsg": "'auth_obj'",
    "info": "",
    "result": null,
    "data": null
}
```

**To Reproduce**

Sometimes switching the deployed version from 8.1 (which works) to higher version (which is not working) works in same browser session, but stops working if the existing cookies are cleared.

I don't know if this can be reproduced on your side, here the OIDC pgadmin config:

```
    OAUTH2_CONFIG = [
      {
        'OAUTH2_NAME': 'azure',
        'OAUTH2_DISPLAY_NAME': 'SSO via EntraID',
        'OAUTH2_CLIENT_ID': os.environ['OIDC_CLIENT_ID'],
        'OAUTH2_CLIENT_SECRET': os.environ['OIDC_CLIENT_SECRET'],
        'OAUTH2_SERVER_METADATA_URL': 'https://login.microsoftonline.com/xxxx-tenant-id-xxxx/v2.0/.well-known/openid-configuration',
        'OAUTH2_TOKEN_URL': 'https://login.microsoftonline.com/xxxx-tenant-id-xxxx/oauth2/v2.0/token',
        'OAUTH2_AUTHORIZATION_URL': 'https://login.microsoftonline.com/xxxx-tenant-id-xxxx/oauth2/v2.0/authorize',
        'OAUTH2_API_BASE_URL': 'https://graph.microsoft.com/v1.0/',
        'OAUTH2_USERINFO_ENDPOINT': 'me',
        'OAUTH2_SCOPE': 'User.Read',
        'OAUTH2_USERNAME_CLAIM': 'userPrincipalName',
        'OAUTH2_ICON': 'fa-microsoft',
        'OAUTH2_BUTTON_COLOR': '#0080ff',
      }
    ]

```

**Expected behavior**

Would be nice if OIDC login starts working also with latest pgadmin versions. We are stuck with version 8.1 for now.

**Error message**

```
{ "TIMESTAMP": "2024-12-05 11:02:10,513", "SEVERITY": "DEBUG", "APPLICATION": "pgadmin4", "CLASS": "pgadmin", "MESSAGE": "Authentication initiated via source: oauth2" }
{ "TIMESTAMP": "2024-12-05 11:02:10,514", "SEVERITY": "DEBUG", "APPLICATION": "pgadmin4", "CLASS": "pgadmin", "MESSAGE": "Authentication initiated via source: oauth2 is failed." }
172.16.128.4 - - [05/Dec/2024:11:02:10 +0000] "POST /authenticate/login HTTP/1.1" 302 807 "https://pgadmin.xxx-dev.xxx.xxx.net/login?next=/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36 Edg/129.0.0.0"
{ "TIMESTAMP": "2024-12-05 11:02:13,346", "SEVERITY": "ERROR", "APPLICATION": "pgadmin4", "CLASS": "pgadmin", "MESSAGE": "'auth_obj'" }
Traceback (most recent call last):
  File "/venv/lib/python3.12/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/venv/lib/python3.12/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/pgadmin4/pgadmin/authenticate/oauth2.py", line 54, in oauth_authorize
    auth_obj = session['auth_obj']
               ~~~~~~~^^^^^^^^^^^^
KeyError: 'auth_obj'
172.16.128.4 - - [05/Dec/2024:11:02:13 +0000] "GET /oauth2/authorize?code=1.AYEAU8pcxxxxxxxxxxxxx HTTP/1.1" 500 73 "https://login.microsoftonline.com/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36 Edg/129.0.0.0"

```

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Ubuntu Linux (AKS nodes)
 - Version: 22.04.5
 - Mode: Server
 - Browser (if running in server mode): MS Edge
 - Package type: Container

**Comment by yogeshmahajan-1903** [comment]
Can you please check user endpoint? It should be - 
```'OAUTH2_USERINFO_ENDPOINT': 'oidc/userinfo',```  in case of OIDC setup

**Comment by khushboovashi** [comment]
You are using a very old version of pgAdmin. I would suggest upgrading to the latest version.
This looks like a redirection issue. Please share your pgAdmin hosting details.

**Comment by oldboys92** [comment]
> You are using a very old version of pgAdmin. I would suggest upgrading to the latest version. This looks like a redirection issue. Please share your pgAdmin hosting details.

I am trying but OIDC setup is not working since ver 8.2, so stuck with 8.1 version for now. I've already did search repo change history for [oauth2.py](https://github.com/pgadmin-org/pgadmin4/blob/master/web/pgadmin/authenticate/oauth2.py), but did not found any changes which might cause my issue.

**Comment by oldboys92** [comment]
> Can you please check user endpoint? It should be - `'OAUTH2_USERINFO_ENDPOINT': 'oidc/userinfo',` in case of OIDC setup

I have created 2 login methods via Graph API, one for `me` and one for `oidc/userinfo`. Both have same issue, here my config:

```
    OAUTH2_CONFIG = [
      {
        'OAUTH2_NAME': 'azure1',
        'OAUTH2_DISPLAY_NAME': 'SSO - Graph API',
        'OAUTH2_CLIENT_ID': os.environ['OIDC_CLIENT_ID'],
        'OAUTH2_CLIENT_SECRET': os.environ['OIDC_CLIENT_SECRET'],
        'OAUTH2_SERVER_METADATA_URL': 'https://login.microsoftonline.com/tenant-id/v2.0/.well-known/openid-configuration',
        'OAUTH2_TOKEN_URL': 'https://login.microsoftonline.com/tenant-id/oauth2/v2.0/token',
        'OAUTH2_AUTHORIZATION_URL': 'https://login.microsoftonline.com/tenant-id/oauth2/v2.0/authorize',
        'OAUTH2_API_BASE_URL': 'https://graph.microsoft.com/v1.0/',
        'OAUTH2_USERINFO_ENDPOINT': 'me',
        'OAUTH2_SCOPE': 'User.Read openid email profile offline_access',
        'OAUTH2_USERNAME_CLAIM': 'userPrincipalName',
        'OAUTH2_ICON': 'fa-microsoft',
        'OAUTH2_BUTTON_COLOR': '#0080ff',
      },
      {
        'OAUTH2_NAME': 'azure2',
        'OAUTH2_DISPLAY_NAME': 'SSO - OIDC Userinfo',
        'OAUTH2_CLIENT_ID': os.environ['OIDC_CLIENT_ID'],
        'OAUTH2_CLIENT_SECRET': os.environ['OIDC_CLIENT_SECRET'],
        'OAUTH2_SERVER_METADATA_URL': 'https://login.microsoftonline.com/tenant-id/v2.0/.well-known/openid-configuration',
        'OAUTH2_TOKEN_URL': 'https://login.microsoftonline.com/tenant-id/oauth2/v2.0/token',
        'OAUTH2_AUTHORIZATION_URL': 'https://login.microsoftonline.com/tenant-id/oauth2/v2.0/authorize',
        'OAUTH2_API_BASE_URL': 'https://graph.microsoft.com',
        'OAUTH2_USERINFO_ENDPOINT': 'oidc/userinfo',
        'OAUTH2_USERNAME_CLAIM': 'email',
        'OAUTH2_SCOPE': 'User.Read openid email profile offline_access',
        'OAUTH2_ICON': 'fa-microsoft',
        'OAUTH2_BUTTON_COLOR': '#0080ff',
      },
    ]
```

If I understand the code in oauth2.py correctly, the authentication method is expecting `auth_obj` in the session, but the key is not part of session dict.

I don't know how to debug this. Authlib used by pgadmin for OAuth is not having similar issues in their repo issues.

**Comment by yogeshmahajan-1903** [comment]
Can you please share your webserver details? Is your pgadmin running behind any proxy servers? Can you please share your AKS yaml?

**Comment by oldboys92** [comment]
@yogeshmahajan-1903 my latest test was with this version and I can confirm, for me the error still exists in 8.13.
 
reproducible? this is challenging since it might be something in the EntraID OIDC setup itself. There are so many settings there and no description what exactly is required for pgadmin4. I remember I had to try out till that worked.

Now is possible something changed in a library from version 8.1 to 8.2 since there it stops working. And I've tested since then every new pgadmin4 version and I am still stuck with the error.

**Comment by yogeshmahajan-1903** [comment]
@oldboys92 
Can you please try setting ```PGADMIN_CONFIG_PROXY_X_HOST_COUNT = 1``` ? This is required because request from client routes Browser > Azure LB > Ingress > pgadmin service.

**Comment by oldboys92** [comment]
@yogeshmahajan-1903 we don't use `X-Forward-For` http request attributes at all. is this mandatory?

**Comment by oldboys92** [comment]
@khushboovashi yes, did not help. same error.

**Comment by pravesh-sharma** [comment]
Hi @oldboys92,

We can set a call between 10 to 5 PM IST.

**Comment by anilsahoo20** [comment]
No response from author, hence closing the issue.

**Comment by oldboys92** [comment]
sorry was on a long vacation, can we reopen this. I would like to use your offer and to have a call.

**Comment by oldboys92** [comment]
@am07 to have a link to this issue

**Comment by baoduy** [comment]
This happened from v9. I have rolled back to the version 8 and it is working fine with the EntrID

**Comment by yogeshmahajan-1903** [comment]
@baoduy 
Can you please share logs? OAuth2 config and pgadmin config?
