### ISSUE TITLE
Not working after upgrade

### ISSUE THREAD

**Issue by MomentQYC** [pgadmin-org/pgadmin4#8256]
**Describe the bug**

When I perform the upgrade, opening pgadmin4-desktop shows `{"success":0,"errormsg":"'creatable'","info":"","result":null,"data":null}` and doesn't work.

**To Reproduce**

1. Works fine in version 8.13
2. Use apt to upgrade via the official repository
3. See the message

**Expected behavior**

Works just as it did in version 8.13.

**Error message**

`{"success":0,"errormsg":"'creatable'","info":"","result":null,"data":null}`

**Screenshots**

![image](https://github.com/user-attachments/assets/40da7d4b-6fed-4525-964c-817422a6ae3f)

**Desktop (please complete the following information):**
 - OS: Debian 12 backports
 - Version: 8.14
 - Mode: Desktop
 - Browser (if running in server mode): Not related
 - Package type: DEB (APT)

**Comment by khushboovashi** [comment]
Hi @MomentQYC,

Can you please share the proper reproduction steps?
Were you able to upgrade the pgAdmin 4?
Is the pgAdmin 4 app opening for you?

**Comment by MomentQYC** [comment]
> Hi @MomentQYC,
> 
> 
> 
> Can you please share the proper reproduction steps?
> 
> Were you able to upgrade the pgAdmin 4?
> 
> Is the pgAdmin 4 app opening for you?
> 
> 

As outrageous as it may seem, this is the full steps. The screenshot is what shows up when I open the app, all features are unavailable.

**Comment by MomentQYC** [comment]
> Hi @MomentQYC,
> 
> Can you please share the proper reproduction steps? Were you able to upgrade the pgAdmin 4? Is the pgAdmin 4 app opening for you?

```
Total spawn time to start the pgAdmin4 server: 0.005 Sec
2024-12-14 09:23:27,560: WARNING	werkzeug:	Werkzeug appears to be used in a production deployment. Consider switching to a production web server instead.

 * Serving Flask app 'pgadmin'
 * Debug mode: off

------------------------------------------
Total time taken to ping pgAdmin4 server: 4.02 Sec
------------------------------------------
Total launch time of pgAdmin4: 4.115 Sec
------------------------------------------
Application Server URL: http://127.0.0.1:46619/?key=e342078e-dcbb-4ab1-b4b5-5cb2dfa77d70
2024-12-14 09:23:27,958: ERROR	pgadmin:	'creatable'
Traceback (most recent call last):
  File "/usr/pgadmin4/venv/lib/python3.11/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/pgadmin4/venv/lib/python3.11/site-packages/flask/app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/pgadmin4/venv/lib/python3.11/site-packages/flask_login/utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/pgadmin4/web/pgadmin/authenticate/mfa/utils.py", line 304, in inner
    return mfa_enabled(
           ^^^^^^^^^^^^
  File "/usr/pgadmin4/web/pgadmin/authenticate/mfa/utils.py", line 171, in mfa_enabled
    return execute_if_disabled()
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/pgadmin4/web/pgadmin/authenticate/mfa/utils.py", line 297, in execute_func
    return wrapped(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/pgadmin4/web/pgadmin/user_login_check.py", line 22, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/pgadmin4/web/pgadmin/browser/__init__.py", line 417, in index
    language = user_languages.get() or 'en'
               ^^^^^^^^^^^^^^^^^^^^
  File "/usr/pgadmin4/web/pgadmin/utils/preferences.py", line 118, in get
    is_format_data, data = self._get_format_data(res)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/pgadmin4/web/pgadmin/utils/preferences.py", line 152, in _get_format_data
    if self.control_props and self.control_props['creatable']:
                              ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
KeyError: 'creatable'
```

**Comment by 6LWa6ZKx** [comment]
win10 , to 
the bad to my work

**Comment by 6LWa6ZKx** [comment]
Just now, I uninstalled and reinstalled and it still doesn't work.
I had a bad day. It affected my work

**Comment by 6LWa6ZKx** [comment]
“C:\Users\xxx\AppData\Roaming\pgAdmin t\sessions” ，del，is work。

but ，All connection configurations are lost

**Comment by 6LWa6ZKx** [comment]
del “C:\Users\spooo\AppData\Roaming\pgAdmin\pgadmin4.db” 。
work，but All connection configurations are lost

**Comment by Lhy-ao** [comment]
I have the same problem too  on Win11 23H2

**Comment by yi-huan** [comment]
> del “C:\Users\xx\AppData\Roaming\pgAdmin\pgadmin4.db” 。 work，but All connection configurations are lost

Thanks, It can be run after deletion.
The server was exported before installation, but the import still requires a password.

**Comment by TinyPeanut** [comment]
OS: Win11 23H2 
Version: pgadmin4-8.14-x64

I have the same problem
![image](https://github.com/user-attachments/assets/cfcea66c-79f5-40f9-bddc-4333bc509040)

**Comment by TinyPeanut** [comment]
2024-12-20 15:32:48,152: WARNING	werkzeug:	Werkzeug appears to be used in a production deployment. Consider switching to a production web server instead.
2024-12-20 15:32:48,817: ERROR	pgadmin:	'creatable'
Traceback (most recent call last):
  File "D:\Applications\pgAdmin 4\python\Lib\site-packages\flask\app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Applications\pgAdmin 4\python\Lib\site-packages\flask\app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Applications\pgAdmin 4\python\Lib\site-packages\flask_login\utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Applications\pgAdmin 4\web\pgadmin\authenticate\mfa\utils.py", line 304, in inner
    return mfa_enabled(
           ^^^^^^^^^^^^
  File "D:\Applications\pgAdmin 4\web\pgadmin\authenticate\mfa\utils.py", line 171, in mfa_enabled
    return execute_if_disabled()
           ^^^^^^^^^^^^^^^^^^^^^
  File "D:\Applications\pgAdmin 4\web\pgadmin\authenticate\mfa\utils.py", line 297, in execute_func
    return wrapped(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Applications\pgAdmin 4\web\pgadmin\user_login_check.py", line 22, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "D:\Applications\pgAdmin 4\web\pgadmin\browser\__init__.py", line 417, in index
    language = user_languages.get() or 'en'
               ^^^^^^^^^^^^^^^^^^^^
  File "D:\Applications\pgAdmin 4\web\pgadmin\utils\preferences.py", line 118, in get
    is_format_data, data = self._get_format_data(res)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Applications\pgAdmin 4\web\pgadmin\utils\preferences.py", line 152, in _get_format_data
    if self.control_props and self.control_props['creatable']:
                              ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
KeyError: 'creatable'

**Comment by linlom025** [comment]
How do you solve this problem? I'm having the same issue, and it's December 25th.

**Comment by Lhy-ao** [comment]
> del “C:\Users\xx\AppData\Roaming\pgAdmin\pgadmin4.db” 。
> work，but All connection configurations are lost

del “C:\Users\xx\AppData\Roaming\pgAdmin\pgadmin4.db” 。
work，but All connection configurations are lost

**Comment by RohitBhati8269** [comment]
Tested and verified on :- https://www.postgresql.org/ftp/pgadmin/pgadmin4/snapshots/2025-01-16
Package:- wheel & dmg
OS:- macOs Sequoia 15.0.1
